import os, json, asyncio, logging, re, sqlite3, datetime
from pathlib import Path
from typing import List, Optional
import httpx
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse
from pydantic import BaseModel
import uvicorn
from bs4 import BeautifulSoup

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger(__name__)

BASE_DIR = Path(__file__).resolve().parent
DB_PATH  = BASE_DIR / "local_db" / "nutriken_cache.db"
Path("local_db").mkdir(exist_ok=True)

# ── LOCAL DATABASES — cargadas al inicio desde archivos locales ───────────────
HERB_DRUG_DB = {}     # herb name -> list of drug interactions (from tapirro/herb-drug-interaction-checker)
PHARMGKB_DB  = {}     # gene -> list of chemical relationships (from PharmGKB)

def load_local_databases():
    global HERB_DRUG_DB, PHARMGKB_DB
    db_dir = BASE_DIR / "local_db"

    # 1. Herb-drug interactions (tapirro MIT — 204 herbs, 592 interactions)
    hdi_file = db_dir / "herb_drug_interactions.json"
    if hdi_file.exists():
        try:
            data = json.loads(hdi_file.read_text(encoding="utf-8"))
            HERB_DRUG_DB = data.get("interactions_by_herb", {})
            logger.info(f"Herb-drug DB cargada: {len(HERB_DRUG_DB)} hierbas, fuente: tapirro/herb-drug-interaction-checker (MIT)")
        except Exception as e:
            logger.warning(f"Error cargando herb_drug_interactions.json: {e}")

    # 2. PharmGKB nutrition relationships (CC BY-SA 4.0)
    pgkb_file = db_dir / "pharmgkb_nutrition.json"
    if pgkb_file.exists():
        try:
            rows = json.loads(pgkb_file.read_text(encoding="utf-8"))
            for row in rows:
                gene = row.get("gene","").upper()
                if gene:
                    PHARMGKB_DB.setdefault(gene, []).append(row)
            logger.info(f"PharmGKB DB cargada: {len(PHARMGKB_DB)} genes, {len(rows)} relaciones")
        except Exception as e:
            logger.warning(f"Error cargando pharmgkb_nutrition.json: {e}")



# ── TRADUCCIÓN ES→EN ──────────────────────────────────────────────────────────
ES_EN = {
    "trigliceridos":"triglycerides","triglicéridos":"triglycerides",
    "colesterol":"cholesterol","obesidad":"obesity","diabetes":"diabetes",
    "inflamacion":"inflammation","inflamación":"inflammation",
    "higado":"liver","hígado":"liver","hepatico":"hepatic","hepático":"hepatic",
    "riñon":"kidney","riñón":"kidney","renal":"renal",
    "corazon":"heart","corazón":"heart","cardiovascular":"cardiovascular",
    "presion arterial":"blood pressure","presión arterial":"blood pressure",
    "hipertension":"hypertension","hipertensión":"hypertension",
    "azucar":"blood sugar","azúcar":"blood sugar","glucosa":"glucose",
    "insulina":"insulin","resistencia insulina":"insulin resistance",
    "tiroides":"thyroid","hipotiroidismo":"hypothyroidism","hipertiroidismo":"hyperthyroidism",
    "artritis":"arthritis","reumatoide":"rheumatoid",
    "anemia":"anemia","hierro":"iron","ferritina":"ferritin",
    "vitamina d":"vitamin D","vitamina c":"vitamin C","vitamina e":"vitamin E",
    "vitamina b12":"vitamin B12","vitamina b6":"vitamin B6",
    "acido folico":"folic acid","ácido fólico":"folic acid","folato":"folate",
    "magnesio":"magnesium","calcio":"calcium","zinc":"zinc","selenio":"selenium",
    "omega 3":"omega-3","acidos grasos":"fatty acids","ácidos grasos":"fatty acids",
    "curcuma":"turmeric","cúrcuma":"turmeric","jengibre":"ginger",
    "ajo":"garlic","canela":"cinnamon","te verde":"green tea","té verde":"green tea",
    "cardo mariano":"milk thistle","silimarina":"silymarin",
    "berberina":"berberine","probioticos":"probiotics","probióticos":"probiotics",
    "carnitina":"carnitine","coq10":"coenzyme Q10","ubiquinol":"ubiquinol",
    "melatonina":"melatonin","equinacea":"echinacea","ginseng":"ginseng",
    "acido lipoico":"lipoic acid","ácido lipoico":"lipoic acid",
    "linaza":"flaxseed","alcachofa":"artichoke","diente de leon":"dandelion",
    "fenogreco":"fenugreek","gymnema":"gymnema",
    "atorvastatina":"atorvastatin","rosuvastatina":"rosuvastatin",
    "simvastatina":"simvastatin","estatina":"statin","estatinas":"statins",
    "metformina":"metformin","warfarina":"warfarin","aspirina":"aspirin",
    "ibuprofeno":"ibuprofen","naproxeno":"naproxen","prednisona":"prednisone",
    "perdida de peso":"weight loss","pérdida de peso":"weight loss",
    "intolerancia lactosa":"lactose intolerance",
    "enfermedad celiaca":"celiac disease","celiaca":"celiac",
    "microbiota":"gut microbiota","intestino":"intestine",
    "embarazo":"pregnancy","lactancia":"breastfeeding",
    "menopausia":"menopause","osteoporosis":"osteoporosis",
    "cancer":"cancer","cáncer":"cancer","tumor":"tumor",
    "toronja":"grapefruit","granada":"pomegranate","alcohol":"alcohol",
    "cafeina":"caffeine","cafeína":"caffeine",
    "calculos biliares":"gallstones","cálculos biliares":"gallstones",
    "vesícula":"gallbladder","vesicula":"gallbladder",
    "udca":"ursodeoxycholic acid","acido ursodesoxicolico":"ursodeoxycholic acid",
    "miopatia":"myopathy","miopatía":"myopathy",
}

# MSK slug map — slugs verificados 2026
MSK_SLUGS = {
    "omega-3":"omega-3","omega3":"omega-3","fish oil":"omega-3","fish-oil":"omega-3","aceite de pescado":"omega-3","omega 3":"omega-3","epa":"omega-3","dha":"omega-3","pescado":"omega-3",
    "red yeast rice":"red-yeast-rice","red-yeast-rice":"red-yeast-rice","arroz levadura roja":"red-yeast-rice","levadura roja":"red-yeast-rice",
    "coenzyme q10":"coenzyme-q10","coenzyme-q10":"coenzyme-q10","coq10":"coenzyme-q10","ubiquinol":"coenzyme-q10","coenzima q10":"coenzyme-q10","ubiquinona":"coenzyme-q10",
    "berberine":"berberine","berberina":"berberine","berberis":"berberine",
    "garlic":"garlic","ajo":"garlic","allium":"garlic",
    "flaxseed":"flaxseed","linaza":"flaxseed","lino":"flaxseed","flax":"flaxseed",
    "resveratrol":"resveratrol",
    "artichoke":"artichoke","alcachofa":"artichoke","alcaucil":"artichoke",
    "niacin":"niacin","niacina":"niacin","nicotinic acid":"niacin","acido nicotinico":"niacin",
    "chromium":"chromium","cromo":"chromium","chromium picolinate":"chromium","picolinato de cromo":"chromium",
    "cinnamon":"cinnamon","canela":"cinnamon","cinnamon bark":"cinnamon",
    "fenugreek":"fenugreek","fenogreco":"fenugreek","alholva":"fenugreek",
    "bitter melon":"bitter-melon","bitter-melon":"bitter-melon","amargoso":"bitter-melon","melon amargo":"bitter-melon","momordica":"bitter-melon",
    "gymnema":"gymnema","gymnema sylvestre":"gymnema",
    "alpha lipoic acid":"alpha-lipoic-acid","alpha-lipoic-acid":"alpha-lipoic-acid","acido lipoico":"alpha-lipoic-acid","lipoic acid":"alpha-lipoic-acid","ala":"alpha-lipoic-acid",
    "milk thistle":"milk-thistle","milk-thistle":"milk-thistle","cardo mariano":"milk-thistle","silimarina":"milk-thistle","silymarin":"milk-thistle","silybum":"milk-thistle",
    "dandelion":"dandelion","diente de leon":"dandelion","taraxacum":"dandelion",
    "vitamin d":"vitamin-d","vitamin-d":"vitamin-d","vitamina d":"vitamin-d","vitamin d3":"vitamin-d","colecalciferol":"vitamin-d","vit d":"vitamin-d",
    "vitamin c":"vitamin-c","vitamin-c":"vitamin-c","vitamina c":"vitamin-c","ascorbic acid":"vitamin-c","ascorbato":"vitamin-c",
    "vitamin e":"vitamin-e","vitamin-e":"vitamin-e","vitamina e":"vitamin-e","tocopherol":"vitamin-e","tocoferol":"vitamin-e",
    "vitamin b12":"vitamin-b12","vitamin-b12":"vitamin-b12","b12":"vitamin-b12","cobalamina":"vitamin-b12","cianocobalamina":"vitamin-b12","metilcobalamina":"vitamin-b12",
    "vitamin b6":"vitamin-b6","vitamin-b6":"vitamin-b6","piridoxina":"vitamin-b6","pyridoxine":"vitamin-b6","b6":"vitamin-b6",
    "folic acid":"folate","folic-acid":"folate","folato":"folate","acido folico":"folate","folate":"folate","methylfolate":"folate","metilfolato":"folate","5-mthf":"folate",
    "magnesium":"magnesium","magnesio":"magnesium","mg":"magnesium",
    "zinc":"zinc","cinc":"zinc",
    "selenium":"selenium","selenio":"selenium","selenometionina":"selenium",
    "calcium":"calcium","calcio":"calcium","carbonato de calcio":"calcium",
    "iron":"iron","hierro":"iron","ferrous":"iron","ferroso":"iron",
    "ashwagandha":"ashwagandha","withania":"ashwagandha","ginseng indio":"ashwagandha",
    "rhodiola":"rhodiola","rhodiola rosea":"rhodiola","rodiola":"rhodiola",
    "valerian":"valerian","valeriana":"valerian","valerian root":"valerian",
    "kava":"kava","kava kava":"kava","kawa":"kava",
    "melatonin":"melatonin","melatonina":"melatonin","melatонin":"melatonin",
    "turmeric":"turmeric","curcuma":"turmeric","curcumin":"turmeric","curcumina":"turmeric","cúrcuma":"turmeric",
    "ginger":"ginger","jengibre":"ginger","zingiber":"ginger",
    "boswellia":"boswellia","incienso":"boswellia","frankincense":"boswellia",
    "quercetin":"quercetin","quercetina":"quercetin","quercetol":"quercetin",
    "echinacea":"echinacea","equinacea":"echinacea","echinacea purpurea":"echinacea",
    "ginseng":"ginseng","panax ginseng":"ginseng","panax":"ginseng","red ginseng":"ginseng",
    "green tea":"green-tea","green-tea":"green-tea","te verde":"green-tea","té verde":"green-tea","egcg":"green-tea","camellia sinensis":"green-tea",
    "aloe vera":"aloe-vera","aloe-vera":"aloe-vera","sabila":"aloe-vera","sábila":"aloe-vera","aloe":"aloe-vera",
    "probiotics":"probiotics","probioticos":"probiotics","probióticos":"probiotics","lactobacillus":"probiotics","bifidobacterium":"probiotics",
    "l-carnitine":"l-carnitine","carnitina":"l-carnitine","carnitine":"l-carnitine","levocarnitine":"l-carnitine",
    "5-htp":"5-htp-01","5htp":"5-htp-01","serotonina":"5-htp-01","5 htp":"5-htp-01",
    "glucosamine":"glucosamine","glucosamina":"glucosamine",
    "dhea":"dhea","dehydroepiandrosterone":"dhea",
    "saw palmetto":"saw-palmetto","serenoa":"saw-palmetto","palmito":"saw-palmetto",
    "black cohosh":"black-cohosh","cohosh negro":"black-cohosh","cimicifuga":"black-cohosh",
    "evening primrose":"evening-primrose-oil","onagra":"evening-primrose-oil","aceite de onagra":"evening-primrose-oil",
    "ginkgo":"ginkgo","ginkgo biloba":"ginkgo","maidenhair":"ginkgo",
    "st johns wort":"st-johns-wort","st. johns wort":"st-johns-wort","hierba san juan":"st-johns-wort","hypericum":"st-johns-wort","hipérico":"st-johns-wort",
    "glucomannan":"glucomannan","konjac":"glucomannan","glucomanano":"glucomannan",
    "conjugated linoleic acid":"conjugated-linoleic-acid","cla":"conjugated-linoleic-acid","acido linoleico conjugado":"conjugated-linoleic-acid",
    "garcinia":"garcinia","garcinia cambogia":"garcinia",
    "acai":"acai-berry","acai berry":"acai-berry","acai-berry":"acai-berry","açaí":"acai-berry",
    "spirulina":"spirulina","espirulina":"spirulina",
    "chlorella":"chlorella","clorela":"chlorella",
    "collagen":"collagen","colageno":"collagen","colágeno":"collagen",
    "hyaluronic acid":"hyaluronic-acid","acido hialuronico":"hyaluronic-acid","acido hialurónico":"hyaluronic-acid",
    "chondroitin":"chondroitin","condroitina":"chondroitin",
    "prebiotics":"probiotics","prebioticos":"probiotics","inulin":"probiotics","fos":"probiotics",
    "ahcc":"ahcc","agaricus":"agaricus","agarico":"agaricus",
    "astragalus":"astragalus","astragalo":"astragalus",
    "milk-thistle":"milk-thistle","silymarin":"milk-thistle",
    "alpha-lipoic-acid":"alpha-lipoic-acid",
}

GENE_DB = {
  "ABCB1": {
    "symbol": "ABCB1",
    "gene_id": "5243",
    "ensembl_id": "ENSG00000085563",
    "pharmgkb_id": "PA267",
    "name": "ATP binding cassette subfamily B member 1",
    "chromosome": "7",
    "location": "7q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "ATP binding cassette subfamily B member 1. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/5243",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000085563",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA267",
    "snpedia_url": "https://www.snpedia.com/index.php/ABCB1",
    "omim_url": "https://omim.org/search?index=entry&search=ABCB1"
  },
  "ABCG5": {
    "symbol": "ABCG5",
    "gene_id": "64240",
    "ensembl_id": "ENSG00000138075",
    "pharmgkb_id": "PA24411",
    "name": "ATP binding cassette subfamily G member 5",
    "chromosome": "2",
    "location": "2q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "ATP binding cassette subfamily G member 5. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/64240",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000138075",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA24411",
    "snpedia_url": "https://www.snpedia.com/index.php/ABCG5",
    "omim_url": "https://omim.org/search?index=entry&search=ABCG5"
  },
  "ABCG8": {
    "symbol": "ABCG8",
    "gene_id": "64241",
    "ensembl_id": "ENSG00000143921",
    "pharmgkb_id": "PA24412",
    "name": "ATP binding cassette subfamily G member 8",
    "chromosome": "2",
    "location": "2q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "ATP binding cassette subfamily G member 8. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/64241",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000143921",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA24412",
    "snpedia_url": "https://www.snpedia.com/index.php/ABCG8",
    "omim_url": "https://omim.org/search?index=entry&search=ABCG8"
  },
  "ACE": {
    "symbol": "ACE",
    "gene_id": "1636",
    "ensembl_id": "ENSG00000159640",
    "pharmgkb_id": "PA139",
    "name": "angiotensin I converting enzyme",
    "chromosome": "17",
    "location": "17q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "angiotensin I converting enzyme. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/1636",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000159640",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA139",
    "snpedia_url": "https://www.snpedia.com/index.php/ACE",
    "omim_url": "https://omim.org/search?index=entry&search=ACE"
  },
  "ADD1": {
    "symbol": "ADD1",
    "gene_id": "118",
    "ensembl_id": "ENSG00000087274",
    "pharmgkb_id": "PA31",
    "name": "adducin 1",
    "chromosome": "4",
    "location": "4q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "adducin 1. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/118",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000087274",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA31",
    "snpedia_url": "https://www.snpedia.com/index.php/ADD1",
    "omim_url": "https://omim.org/search?index=entry&search=ADD1"
  },
  "ADIPOQ": {
    "symbol": "ADIPOQ",
    "gene_id": "9370",
    "ensembl_id": "ENSG00000181092",
    "pharmgkb_id": "PA134933118",
    "name": "adiponectin, C1Q and collagen domain containing",
    "chromosome": "3",
    "location": "3q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "adiponectin, C1Q and collagen domain containing. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/9370",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000181092",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA134933118",
    "snpedia_url": "https://www.snpedia.com/index.php/ADIPOQ",
    "omim_url": "https://omim.org/search?index=entry&search=ADIPOQ"
  },
  "ADRB1": {
    "symbol": "ADRB1",
    "gene_id": "153",
    "ensembl_id": "ENSG00000043591",
    "pharmgkb_id": "PA38",
    "name": "adrenoceptor beta 1",
    "chromosome": "10",
    "location": "10q",
    "is_vip": True,
    "has_cpic": True,
    "summary": "adrenoceptor beta 1. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/153",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000043591",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA38",
    "snpedia_url": "https://www.snpedia.com/index.php/ADRB1",
    "omim_url": "https://omim.org/search?index=entry&search=ADRB1"
  },
  "ADRB2": {
    "symbol": "ADRB2",
    "gene_id": "154",
    "ensembl_id": "ENSG00000169252",
    "pharmgkb_id": "PA39",
    "name": "adrenoceptor beta 2",
    "chromosome": "5",
    "location": "5q",
    "is_vip": True,
    "has_cpic": True,
    "summary": "adrenoceptor beta 2. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/154",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000169252",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA39",
    "snpedia_url": "https://www.snpedia.com/index.php/ADRB2",
    "omim_url": "https://omim.org/search?index=entry&search=ADRB2"
  },
  "AGT": {
    "symbol": "AGT",
    "gene_id": "183",
    "ensembl_id": "ENSG00000135744",
    "pharmgkb_id": "PA42",
    "name": "angiotensinogen",
    "chromosome": "1",
    "location": "1q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "angiotensinogen. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/183",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000135744",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA42",
    "snpedia_url": "https://www.snpedia.com/index.php/AGT",
    "omim_url": "https://omim.org/search?index=entry&search=AGT"
  },
  "AGTR1": {
    "symbol": "AGTR1",
    "gene_id": "185",
    "ensembl_id": "ENSG00000144891",
    "pharmgkb_id": "PA43",
    "name": "angiotensin II receptor type 1",
    "chromosome": "3",
    "location": "3q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "angiotensin II receptor type 1. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/185",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000144891",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA43",
    "snpedia_url": "https://www.snpedia.com/index.php/AGTR1",
    "omim_url": "https://omim.org/search?index=entry&search=AGTR1"
  },
  "APOA1": {
    "symbol": "APOA1",
    "gene_id": "335",
    "ensembl_id": "ENSG00000118137",
    "pharmgkb_id": "PA49",
    "name": "apolipoprotein A1",
    "chromosome": "11",
    "location": "11q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "apolipoprotein A1. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/335",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000118137",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA49",
    "snpedia_url": "https://www.snpedia.com/index.php/APOA1",
    "omim_url": "https://omim.org/search?index=entry&search=APOA1"
  },
  "APOA5": {
    "symbol": "APOA5",
    "gene_id": "116519",
    "ensembl_id": "ENSG00000110243",
    "pharmgkb_id": "PA24888",
    "name": "apolipoprotein A5",
    "chromosome": "11",
    "location": "11q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "apolipoprotein A5. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/116519",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000110243",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA24888",
    "snpedia_url": "https://www.snpedia.com/index.php/APOA5",
    "omim_url": "https://omim.org/search?index=entry&search=APOA5"
  },
  "APOB": {
    "symbol": "APOB",
    "gene_id": "338",
    "ensembl_id": "ENSG00000084674",
    "pharmgkb_id": "PA50",
    "name": "apolipoprotein B",
    "chromosome": "2",
    "location": "2q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "apolipoprotein B. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/338",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000084674",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA50",
    "snpedia_url": "https://www.snpedia.com/index.php/APOB",
    "omim_url": "https://omim.org/search?index=entry&search=APOB"
  },
  "APOC2": {
    "symbol": "APOC2",
    "gene_id": "344",
    "ensembl_id": "ENSG00000234906",
    "pharmgkb_id": "PA52",
    "name": "apolipoprotein C2",
    "chromosome": "19",
    "location": "19q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "apolipoprotein C2. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/344",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000234906",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA52",
    "snpedia_url": "https://www.snpedia.com/index.php/APOC2",
    "omim_url": "https://omim.org/search?index=entry&search=APOC2"
  },
  "APOC3": {
    "symbol": "APOC3",
    "gene_id": "345",
    "ensembl_id": "ENSG00000110245",
    "pharmgkb_id": "PA53",
    "name": "apolipoprotein C3",
    "chromosome": "11",
    "location": "11q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "apolipoprotein C3. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/345",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000110245",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA53",
    "snpedia_url": "https://www.snpedia.com/index.php/APOC3",
    "omim_url": "https://omim.org/search?index=entry&search=APOC3"
  },
  "APOE": {
    "symbol": "APOE",
    "gene_id": "348",
    "ensembl_id": "ENSG00000130203",
    "pharmgkb_id": "PA55",
    "name": "apolipoprotein E",
    "chromosome": "19",
    "location": "19q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "apolipoprotein E. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/348",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000130203",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA55",
    "snpedia_url": "https://www.snpedia.com/index.php/APOE",
    "omim_url": "https://omim.org/search?index=entry&search=APOE"
  },
  "ATG16L1": {
    "symbol": "ATG16L1",
    "gene_id": "55054",
    "ensembl_id": "ENSG00000085978",
    "pharmgkb_id": "PA134902949",
    "name": "autophagy related 16 like 1",
    "chromosome": "2",
    "location": "2q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "autophagy related 16 like 1. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/55054",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000085978",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA134902949",
    "snpedia_url": "https://www.snpedia.com/index.php/ATG16L1",
    "omim_url": "https://omim.org/search?index=entry&search=ATG16L1"
  },
  "BCO1": {
    "symbol": "BCO1",
    "gene_id": "53630",
    "ensembl_id": "ENSG00000135697",
    "pharmgkb_id": "PA37812",
    "name": "beta-carotene oxygenase 1",
    "chromosome": "16",
    "location": "16q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "beta-carotene oxygenase 1. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/53630",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000135697",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA37812",
    "snpedia_url": "https://www.snpedia.com/index.php/BCO1",
    "omim_url": "https://omim.org/search?index=entry&search=BCO1"
  },
  "CARD9": {
    "symbol": "CARD9",
    "gene_id": "64170",
    "ensembl_id": "ENSG00000187796",
    "pharmgkb_id": "PA26077",
    "name": "caspase recruitment domain family member 9",
    "chromosome": "9",
    "location": "9q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "caspase recruitment domain family member 9. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/64170",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000187796",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA26077",
    "snpedia_url": "https://www.snpedia.com/index.php/CARD9",
    "omim_url": "https://omim.org/search?index=entry&search=CARD9"
  },
  "CAT": {
    "symbol": "CAT",
    "gene_id": "847",
    "ensembl_id": "ENSG00000121691",
    "pharmgkb_id": "PA26099",
    "name": "catalase",
    "chromosome": "11",
    "location": "11q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "catalase. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/847",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000121691",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA26099",
    "snpedia_url": "https://www.snpedia.com/index.php/CAT",
    "omim_url": "https://omim.org/search?index=entry&search=CAT"
  },
  "CDKAL1": {
    "symbol": "CDKAL1",
    "gene_id": "54901",
    "ensembl_id": "ENSG00000145996",
    "pharmgkb_id": "PA134871999",
    "name": "CDK5 regulatory subunit associated protein 1 like 1",
    "chromosome": "6",
    "location": "6q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "CDK5 regulatory subunit associated protein 1 like 1. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/54901",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000145996",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA134871999",
    "snpedia_url": "https://www.snpedia.com/index.php/CDKAL1",
    "omim_url": "https://omim.org/search?index=entry&search=CDKAL1"
  },
  "CDKN2A": {
    "symbol": "CDKN2A",
    "gene_id": "1029",
    "ensembl_id": "ENSG00000147889",
    "pharmgkb_id": "PA106",
    "name": "cyclin dependent kinase inhibitor 2A",
    "chromosome": "9",
    "location": "9q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "cyclin dependent kinase inhibitor 2A. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/1029",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000147889",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA106",
    "snpedia_url": "https://www.snpedia.com/index.php/CDKN2A",
    "omim_url": "https://omim.org/search?index=entry&search=CDKN2A"
  },
  "COMT": {
    "symbol": "COMT",
    "gene_id": "1312",
    "ensembl_id": "ENSG00000093010",
    "pharmgkb_id": "PA117",
    "name": "catechol-O-methyltransferase",
    "chromosome": "22",
    "location": "22q",
    "is_vip": True,
    "has_cpic": True,
    "summary": "catechol-O-methyltransferase. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/1312",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000093010",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA117",
    "snpedia_url": "https://www.snpedia.com/index.php/COMT",
    "omim_url": "https://omim.org/search?index=entry&search=COMT"
  },
  "CRP": {
    "symbol": "CRP",
    "gene_id": "1401",
    "ensembl_id": "ENSG00000132693",
    "pharmgkb_id": "PA120",
    "name": "C-reactive protein",
    "chromosome": "1",
    "location": "1q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "C-reactive protein. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/1401",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000132693",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA120",
    "snpedia_url": "https://www.snpedia.com/index.php/CRP",
    "omim_url": "https://omim.org/search?index=entry&search=CRP"
  },
  "CYP11B2": {
    "symbol": "CYP11B2",
    "gene_id": "1585",
    "ensembl_id": "ENSG00000179142",
    "pharmgkb_id": "PA134",
    "name": "cytochrome P450 family 11 subfamily B member 2",
    "chromosome": "8",
    "location": "8q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "cytochrome P450 family 11 subfamily B member 2. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/1585",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000179142",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA134",
    "snpedia_url": "https://www.snpedia.com/index.php/CYP11B2",
    "omim_url": "https://omim.org/search?index=entry&search=CYP11B2"
  },
  "CYP1A2": {
    "symbol": "CYP1A2",
    "gene_id": "1544",
    "ensembl_id": "ENSG00000140505",
    "pharmgkb_id": "PA27093",
    "name": "cytochrome P450 family 1 subfamily A member 2",
    "chromosome": "15",
    "location": "15q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "cytochrome P450 family 1 subfamily A member 2. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/1544",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000140505",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA27093",
    "snpedia_url": "https://www.snpedia.com/index.php/CYP1A2",
    "omim_url": "https://omim.org/search?index=entry&search=CYP1A2"
  },
  "CYP24A1": {
    "symbol": "CYP24A1",
    "gene_id": "1591",
    "ensembl_id": "ENSG00000019186",
    "pharmgkb_id": "PA27097",
    "name": "cytochrome P450 family 24 subfamily A member 1",
    "chromosome": "20",
    "location": "20q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "cytochrome P450 family 24 subfamily A member 1. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/1591",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000019186",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA27097",
    "snpedia_url": "https://www.snpedia.com/index.php/CYP24A1",
    "omim_url": "https://omim.org/search?index=entry&search=CYP24A1"
  },
  "CYP27B1": {
    "symbol": "CYP27B1",
    "gene_id": "1594",
    "ensembl_id": "ENSG00000111012",
    "pharmgkb_id": "PA27099",
    "name": "cytochrome P450 family 27 subfamily B member 1",
    "chromosome": "12",
    "location": "12q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "cytochrome P450 family 27 subfamily B member 1. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/1594",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000111012",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA27099",
    "snpedia_url": "https://www.snpedia.com/index.php/CYP27B1",
    "omim_url": "https://omim.org/search?index=entry&search=CYP27B1"
  },
  "CYP2C19": {
    "symbol": "CYP2C19",
    "gene_id": "1557",
    "ensembl_id": "ENSG00000165841",
    "pharmgkb_id": "PA124",
    "name": "cytochrome P450 family 2 subfamily C member 19",
    "chromosome": "10",
    "location": "10q",
    "is_vip": True,
    "has_cpic": True,
    "summary": "cytochrome P450 family 2 subfamily C member 19. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/1557",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000165841",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA124",
    "snpedia_url": "https://www.snpedia.com/index.php/CYP2C19",
    "omim_url": "https://omim.org/search?index=entry&search=CYP2C19"
  },
  "CYP2C9": {
    "symbol": "CYP2C9",
    "gene_id": "1559",
    "ensembl_id": "ENSG00000138109",
    "pharmgkb_id": "PA126",
    "name": "cytochrome P450 family 2 subfamily C member 9",
    "chromosome": "10",
    "location": "10q",
    "is_vip": True,
    "has_cpic": True,
    "summary": "cytochrome P450 family 2 subfamily C member 9. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/1559",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000138109",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA126",
    "snpedia_url": "https://www.snpedia.com/index.php/CYP2C9",
    "omim_url": "https://omim.org/search?index=entry&search=CYP2C9"
  },
  "CYP2D6": {
    "symbol": "CYP2D6",
    "gene_id": "1565",
    "ensembl_id": "ENSG00000100197",
    "pharmgkb_id": "PA128",
    "name": "cytochrome P450 family 2 subfamily D member 6",
    "chromosome": "22",
    "location": "22q",
    "is_vip": True,
    "has_cpic": True,
    "summary": "cytochrome P450 family 2 subfamily D member 6. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/1565",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000100197",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA128",
    "snpedia_url": "https://www.snpedia.com/index.php/CYP2D6",
    "omim_url": "https://omim.org/search?index=entry&search=CYP2D6"
  },
  "CYP2R1": {
    "symbol": "CYP2R1",
    "gene_id": "120227",
    "ensembl_id": "ENSG00000186104",
    "pharmgkb_id": "PA134986407",
    "name": "cytochrome P450 family 2 subfamily R member 1",
    "chromosome": "11",
    "location": "11q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "cytochrome P450 family 2 subfamily R member 1. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/120227",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000186104",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA134986407",
    "snpedia_url": "https://www.snpedia.com/index.php/CYP2R1",
    "omim_url": "https://omim.org/search?index=entry&search=CYP2R1"
  },
  "CYP3A4": {
    "symbol": "CYP3A4",
    "gene_id": "1576",
    "ensembl_id": "ENSG00000160868",
    "pharmgkb_id": "PA130",
    "name": "cytochrome P450 family 3 subfamily A member 4",
    "chromosome": "7",
    "location": "7q",
    "is_vip": True,
    "has_cpic": True,
    "summary": "cytochrome P450 family 3 subfamily A member 4. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/1576",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000160868",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA130",
    "snpedia_url": "https://www.snpedia.com/index.php/CYP3A4",
    "omim_url": "https://omim.org/search?index=entry&search=CYP3A4"
  },
  "DHFR": {
    "symbol": "DHFR",
    "gene_id": "1719",
    "ensembl_id": "ENSG00000228716",
    "pharmgkb_id": "PA143",
    "name": "dihydrofolate reductase",
    "chromosome": "5",
    "location": "5q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "dihydrofolate reductase. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/1719",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000228716",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA143",
    "snpedia_url": "https://www.snpedia.com/index.php/DHFR",
    "omim_url": "https://omim.org/search?index=entry&search=DHFR"
  },
  "DPYD": {
    "symbol": "DPYD",
    "gene_id": "1806",
    "ensembl_id": "ENSG00000188641",
    "pharmgkb_id": "PA145",
    "name": "dihydropyrimidine dehydrogenase",
    "chromosome": "1",
    "location": "1q",
    "is_vip": True,
    "has_cpic": True,
    "summary": "dihydropyrimidine dehydrogenase. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/1806",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000188641",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA145",
    "snpedia_url": "https://www.snpedia.com/index.php/DPYD",
    "omim_url": "https://omim.org/search?index=entry&search=DPYD"
  },
  "ELOVL2": {
    "symbol": "ELOVL2",
    "gene_id": "54898",
    "ensembl_id": "ENSG00000197977",
    "pharmgkb_id": "PA27761",
    "name": "ELOVL fatty acid elongase 2",
    "chromosome": "6",
    "location": "6q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "ELOVL fatty acid elongase 2. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/54898",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000197977",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA27761",
    "snpedia_url": "https://www.snpedia.com/index.php/ELOVL2",
    "omim_url": "https://omim.org/search?index=entry&search=ELOVL2"
  },
  "FADS1": {
    "symbol": "FADS1",
    "gene_id": "3992",
    "ensembl_id": "ENSG00000149485",
    "pharmgkb_id": "PA27973",
    "name": "fatty acid desaturase 1",
    "chromosome": "11",
    "location": "11q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "fatty acid desaturase 1. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/3992",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000149485",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA27973",
    "snpedia_url": "https://www.snpedia.com/index.php/FADS1",
    "omim_url": "https://omim.org/search?index=entry&search=FADS1"
  },
  "FADS2": {
    "symbol": "FADS2",
    "gene_id": "9415",
    "ensembl_id": "ENSG00000134824",
    "pharmgkb_id": "PA27974",
    "name": "fatty acid desaturase 2",
    "chromosome": "11",
    "location": "11q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "fatty acid desaturase 2. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/9415",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000134824",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA27974",
    "snpedia_url": "https://www.snpedia.com/index.php/FADS2",
    "omim_url": "https://omim.org/search?index=entry&search=FADS2"
  },
  "FOLH1": {
    "symbol": "FOLH1",
    "gene_id": "2346",
    "ensembl_id": "ENSG00000086205",
    "pharmgkb_id": "PA28205",
    "name": "folate hydrolase 1",
    "chromosome": "11",
    "location": "11q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "folate hydrolase 1. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/2346",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000086205",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA28205",
    "snpedia_url": "https://www.snpedia.com/index.php/FOLH1",
    "omim_url": "https://omim.org/search?index=entry&search=FOLH1"
  },
  "FTO": {
    "symbol": "FTO",
    "gene_id": "79068",
    "ensembl_id": "ENSG00000140718",
    "pharmgkb_id": "PA152208656",
    "name": "FTO alpha-ketoglutarate dependent dioxygenase",
    "chromosome": "16",
    "location": "16q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "FTO alpha-ketoglutarate dependent dioxygenase. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/79068",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000140718",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA152208656",
    "snpedia_url": "https://www.snpedia.com/index.php/FTO",
    "omim_url": "https://omim.org/search?index=entry&search=FTO"
  },
  "FUT2": {
    "symbol": "FUT2",
    "gene_id": "2524",
    "ensembl_id": "ENSG00000176920",
    "pharmgkb_id": "PA28429",
    "name": "fucosyltransferase 2 (H blood group)",
    "chromosome": "19",
    "location": "19q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "fucosyltransferase 2 (H blood group). Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/2524",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000176920",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA28429",
    "snpedia_url": "https://www.snpedia.com/index.php/FUT2",
    "omim_url": "https://omim.org/search?index=entry&search=FUT2"
  },
  "GC": {
    "symbol": "GC",
    "gene_id": "2638",
    "ensembl_id": "ENSG00000145321",
    "pharmgkb_id": "PA28601",
    "name": "GC vitamin D binding protein",
    "chromosome": "4",
    "location": "4q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "GC vitamin D binding protein. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/2638",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000145321",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA28601",
    "snpedia_url": "https://www.snpedia.com/index.php/GC",
    "omim_url": "https://omim.org/search?index=entry&search=GC"
  },
  "GCKR": {
    "symbol": "GCKR",
    "gene_id": "2646",
    "ensembl_id": "ENSG00000084734",
    "pharmgkb_id": "PA28611",
    "name": "glucokinase regulator",
    "chromosome": "2",
    "location": "2q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "glucokinase regulator. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/2646",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000084734",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA28611",
    "snpedia_url": "https://www.snpedia.com/index.php/GCKR",
    "omim_url": "https://omim.org/search?index=entry&search=GCKR"
  },
  "GHRL": {
    "symbol": "GHRL",
    "gene_id": "51738",
    "ensembl_id": "ENSG00000157017",
    "pharmgkb_id": "PA142671740",
    "name": "ghrelin and obestatin prepropeptide",
    "chromosome": "3",
    "location": "3q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "ghrelin and obestatin prepropeptide. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/51738",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000157017",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA142671740",
    "snpedia_url": "https://www.snpedia.com/index.php/GHRL",
    "omim_url": "https://omim.org/search?index=entry&search=GHRL"
  },
  "GNB3": {
    "symbol": "GNB3",
    "gene_id": "2784",
    "ensembl_id": "ENSG00000111664",
    "pharmgkb_id": "PA176",
    "name": "G protein subunit beta 3",
    "chromosome": "12",
    "location": "12q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "G protein subunit beta 3. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/2784",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000111664",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA176",
    "snpedia_url": "https://www.snpedia.com/index.php/GNB3",
    "omim_url": "https://omim.org/search?index=entry&search=GNB3"
  },
  "GPX1": {
    "symbol": "GPX1",
    "gene_id": "2876",
    "ensembl_id": "ENSG00000233276",
    "pharmgkb_id": "PA28949",
    "name": "glutathione peroxidase 1",
    "chromosome": "3",
    "location": "3q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "glutathione peroxidase 1. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/2876",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000233276",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA28949",
    "snpedia_url": "https://www.snpedia.com/index.php/GPX1",
    "omim_url": "https://omim.org/search?index=entry&search=GPX1"
  },
  "GSTM1": {
    "symbol": "GSTM1",
    "gene_id": "2944",
    "ensembl_id": "ENSG00000134184",
    "pharmgkb_id": "PA182",
    "name": "glutathione S-transferase mu 1",
    "chromosome": "1",
    "location": "1q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "glutathione S-transferase mu 1. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/2944",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000134184",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA182",
    "snpedia_url": "https://www.snpedia.com/index.php/GSTM1",
    "omim_url": "https://omim.org/search?index=entry&search=GSTM1"
  },
  "GSTT1": {
    "symbol": "GSTT1",
    "gene_id": "2952",
    "ensembl_id": "ENSG00000277656",
    "pharmgkb_id": "PA183",
    "name": "glutathione S-transferase theta 1",
    "chromosome": "22",
    "location": "22q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "glutathione S-transferase theta 1. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/2952",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000277656",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA183",
    "snpedia_url": "https://www.snpedia.com/index.php/GSTT1",
    "omim_url": "https://omim.org/search?index=entry&search=GSTT1"
  },
  "HLA-DQA1": {
    "symbol": "HLA-DQA1",
    "gene_id": "3117",
    "ensembl_id": "ENSG00000196735",
    "pharmgkb_id": "PA35066",
    "name": "major histocompatibility complex, class II, DQ alpha 1",
    "chromosome": "6",
    "location": "6q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "major histocompatibility complex, class II, DQ alpha 1. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/3117",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000196735",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA35066",
    "snpedia_url": "https://www.snpedia.com/index.php/HLA-DQA1",
    "omim_url": "https://omim.org/search?index=entry&search=HLA-DQA1"
  },
  "HLA-DQB1": {
    "symbol": "HLA-DQB1",
    "gene_id": "3119",
    "ensembl_id": "ENSG00000179344",
    "pharmgkb_id": "PA35068",
    "name": "major histocompatibility complex, class II, DQ beta 1",
    "chromosome": "6",
    "location": "6q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "major histocompatibility complex, class II, DQ beta 1. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/3119",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000179344",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA35068",
    "snpedia_url": "https://www.snpedia.com/index.php/HLA-DQB1",
    "omim_url": "https://omim.org/search?index=entry&search=HLA-DQB1"
  },
  "HMGCR": {
    "symbol": "HMGCR",
    "gene_id": "3156",
    "ensembl_id": "ENSG00000113161",
    "pharmgkb_id": "PA189",
    "name": "3-hydroxy-3-methylglutaryl-CoA reductase",
    "chromosome": "5",
    "location": "5q",
    "is_vip": True,
    "has_cpic": True,
    "summary": "3-hydroxy-3-methylglutaryl-CoA reductase. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/3156",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000113161",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA189",
    "snpedia_url": "https://www.snpedia.com/index.php/HMGCR",
    "omim_url": "https://omim.org/search?index=entry&search=HMGCR"
  },
  "HNF1A": {
    "symbol": "HNF1A",
    "gene_id": "6927",
    "ensembl_id": "ENSG00000135100",
    "pharmgkb_id": "PA36380",
    "name": "HNF1 homeobox A",
    "chromosome": "12",
    "location": "12q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "HNF1 homeobox A. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/6927",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000135100",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA36380",
    "snpedia_url": "https://www.snpedia.com/index.php/HNF1A",
    "omim_url": "https://omim.org/search?index=entry&search=HNF1A"
  },
  "HNF4A": {
    "symbol": "HNF4A",
    "gene_id": "3172",
    "ensembl_id": "ENSG00000101076",
    "pharmgkb_id": "PA29349",
    "name": "hepatocyte nuclear factor 4 alpha",
    "chromosome": "20",
    "location": "20q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "hepatocyte nuclear factor 4 alpha. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/3172",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000101076",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA29349",
    "snpedia_url": "https://www.snpedia.com/index.php/HNF4A",
    "omim_url": "https://omim.org/search?index=entry&search=HNF4A"
  },
  "HSD17B13": {
    "symbol": "HSD17B13",
    "gene_id": "345275",
    "ensembl_id": "ENSG00000170509",
    "pharmgkb_id": "PA38634",
    "name": "hydroxysteroid 17-beta dehydrogenase 13",
    "chromosome": "4",
    "location": "4q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "hydroxysteroid 17-beta dehydrogenase 13. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/345275",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000170509",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA38634",
    "snpedia_url": "https://www.snpedia.com/index.php/HSD17B13",
    "omim_url": "https://omim.org/search?index=entry&search=HSD17B13"
  },
  "IGF2BP2": {
    "symbol": "IGF2BP2",
    "gene_id": "10644",
    "ensembl_id": "ENSG00000073792",
    "pharmgkb_id": "PA128394577",
    "name": "insulin like growth factor 2 mRNA binding protein 2",
    "chromosome": "3",
    "location": "3q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "insulin like growth factor 2 mRNA binding protein 2. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/10644",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000073792",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA128394577",
    "snpedia_url": "https://www.snpedia.com/index.php/IGF2BP2",
    "omim_url": "https://omim.org/search?index=entry&search=IGF2BP2"
  },
  "IL1B": {
    "symbol": "IL1B",
    "gene_id": "3553",
    "ensembl_id": "ENSG00000125538",
    "pharmgkb_id": "PA29808",
    "name": "interleukin 1 beta",
    "chromosome": "2",
    "location": "2q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "interleukin 1 beta. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/3553",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000125538",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA29808",
    "snpedia_url": "https://www.snpedia.com/index.php/IL1B",
    "omim_url": "https://omim.org/search?index=entry&search=IL1B"
  },
  "IL2": {
    "symbol": "IL2",
    "gene_id": "3558",
    "ensembl_id": "ENSG00000109471",
    "pharmgkb_id": "PA195",
    "name": "interleukin 2",
    "chromosome": "4",
    "location": "4q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "interleukin 2. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/3558",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000109471",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA195",
    "snpedia_url": "https://www.snpedia.com/index.php/IL2",
    "omim_url": "https://omim.org/search?index=entry&search=IL2"
  },
  "IL21": {
    "symbol": "IL21",
    "gene_id": "59067",
    "ensembl_id": "ENSG00000138684",
    "pharmgkb_id": "PA29820",
    "name": "interleukin 21",
    "chromosome": "4",
    "location": "4q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "interleukin 21. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/59067",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000138684",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA29820",
    "snpedia_url": "https://www.snpedia.com/index.php/IL21",
    "omim_url": "https://omim.org/search?index=entry&search=IL21"
  },
  "IL23R": {
    "symbol": "IL23R",
    "gene_id": "149233",
    "ensembl_id": "ENSG00000162594",
    "pharmgkb_id": "PA134935109",
    "name": "interleukin 23 receptor",
    "chromosome": "1",
    "location": "1q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "interleukin 23 receptor. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/149233",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000162594",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA134935109",
    "snpedia_url": "https://www.snpedia.com/index.php/IL23R",
    "omim_url": "https://omim.org/search?index=entry&search=IL23R"
  },
  "IL6": {
    "symbol": "IL6",
    "gene_id": "3569",
    "ensembl_id": "ENSG00000136244",
    "pharmgkb_id": "PA198",
    "name": "interleukin 6",
    "chromosome": "7",
    "location": "7q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "interleukin 6. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/3569",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000136244",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA198",
    "snpedia_url": "https://www.snpedia.com/index.php/IL6",
    "omim_url": "https://omim.org/search?index=entry&search=IL6"
  },
  "KCNJ11": {
    "symbol": "KCNJ11",
    "gene_id": "3767",
    "ensembl_id": "ENSG00000187486",
    "pharmgkb_id": "PA217",
    "name": "potassium inwardly rectifying channel subfamily J member 11",
    "chromosome": "11",
    "location": "11q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "potassium inwardly rectifying channel subfamily J member 11. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/3767",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000187486",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA217",
    "snpedia_url": "https://www.snpedia.com/index.php/KCNJ11",
    "omim_url": "https://omim.org/search?index=entry&search=KCNJ11"
  },
  "LCT": {
    "symbol": "LCT",
    "gene_id": "3938",
    "ensembl_id": "ENSG00000115850",
    "pharmgkb_id": "PA30315",
    "name": "lactase",
    "chromosome": "2",
    "location": "2q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "lactase. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/3938",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000115850",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA30315",
    "snpedia_url": "https://www.snpedia.com/index.php/LCT",
    "omim_url": "https://omim.org/search?index=entry&search=LCT"
  },
  "LDLR": {
    "symbol": "LDLR",
    "gene_id": "3949",
    "ensembl_id": "ENSG00000130164",
    "pharmgkb_id": "PA227",
    "name": "low density lipoprotein receptor",
    "chromosome": "19",
    "location": "19q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "low density lipoprotein receptor. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/3949",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000130164",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA227",
    "snpedia_url": "https://www.snpedia.com/index.php/LDLR",
    "omim_url": "https://omim.org/search?index=entry&search=LDLR"
  },
  "LEP": {
    "symbol": "LEP",
    "gene_id": "3952",
    "ensembl_id": "ENSG00000174697",
    "pharmgkb_id": "PA228",
    "name": "leptin",
    "chromosome": "7",
    "location": "7q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "leptin. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/3952",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000174697",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA228",
    "snpedia_url": "https://www.snpedia.com/index.php/LEP",
    "omim_url": "https://omim.org/search?index=entry&search=LEP"
  },
  "LEPR": {
    "symbol": "LEPR",
    "gene_id": "3953",
    "ensembl_id": "ENSG00000116678",
    "pharmgkb_id": "PA229",
    "name": "leptin receptor",
    "chromosome": "1",
    "location": "1q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "leptin receptor. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/3953",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000116678",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA229",
    "snpedia_url": "https://www.snpedia.com/index.php/LEPR",
    "omim_url": "https://omim.org/search?index=entry&search=LEPR"
  },
  "LPL": {
    "symbol": "LPL",
    "gene_id": "4023",
    "ensembl_id": "ENSG00000175445",
    "pharmgkb_id": "PA232",
    "name": "lipoprotein lipase",
    "chromosome": "8",
    "location": "8q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "lipoprotein lipase. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/4023",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000175445",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA232",
    "snpedia_url": "https://www.snpedia.com/index.php/LPL",
    "omim_url": "https://omim.org/search?index=entry&search=LPL"
  },
  "MBOAT7": {
    "symbol": "MBOAT7",
    "gene_id": "79143",
    "ensembl_id": "ENSG00000125505",
    "pharmgkb_id": "PA162395057",
    "name": "membrane bound O-acyltransferase domain containing 7",
    "chromosome": "19",
    "location": "19q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "membrane bound O-acyltransferase domain containing 7. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/79143",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000125505",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA162395057",
    "snpedia_url": "https://www.snpedia.com/index.php/MBOAT7",
    "omim_url": "https://omim.org/search?index=entry&search=MBOAT7"
  },
  "MC4R": {
    "symbol": "MC4R",
    "gene_id": "4160",
    "ensembl_id": "ENSG00000166603",
    "pharmgkb_id": "PA30676",
    "name": "melanocortin 4 receptor",
    "chromosome": "18",
    "location": "18q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "melanocortin 4 receptor. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/4160",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000166603",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA30676",
    "snpedia_url": "https://www.snpedia.com/index.php/MC4R",
    "omim_url": "https://omim.org/search?index=entry&search=MC4R"
  },
  "MCM6": {
    "symbol": "MCM6",
    "gene_id": "4175",
    "ensembl_id": "ENSG00000076003",
    "pharmgkb_id": "PA30696",
    "name": "minichromosome maintenance complex component 6",
    "chromosome": "2",
    "location": "2q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "minichromosome maintenance complex component 6. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/4175",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000076003",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA30696",
    "snpedia_url": "https://www.snpedia.com/index.php/MCM6",
    "omim_url": "https://omim.org/search?index=entry&search=MCM6"
  },
  "MTHFR": {
    "symbol": "MTHFR",
    "gene_id": "4524",
    "ensembl_id": "ENSG00000177000",
    "pharmgkb_id": "PA245",
    "name": "methylenetetrahydrofolate reductase",
    "chromosome": "1",
    "location": "1q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "methylenetetrahydrofolate reductase. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/4524",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000177000",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA245",
    "snpedia_url": "https://www.snpedia.com/index.php/MTHFR",
    "omim_url": "https://omim.org/search?index=entry&search=MTHFR"
  },
  "MTR": {
    "symbol": "MTR",
    "gene_id": "4548",
    "ensembl_id": "ENSG00000116984",
    "pharmgkb_id": "PA31272",
    "name": "5-methyltetrahydrofolate-homocysteine methyltransferase",
    "chromosome": "1",
    "location": "1q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "5-methyltetrahydrofolate-homocysteine methyltransferase. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/4548",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000116984",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA31272",
    "snpedia_url": "https://www.snpedia.com/index.php/MTR",
    "omim_url": "https://omim.org/search?index=entry&search=MTR"
  },
  "MTRR": {
    "symbol": "MTRR",
    "gene_id": "4552",
    "ensembl_id": "ENSG00000124275",
    "pharmgkb_id": "PA31277",
    "name": "5-methyltetrahydrofolate-homocysteine methyltransferase reductase",
    "chromosome": "5",
    "location": "5q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "5-methyltetrahydrofolate-homocysteine methyltransferase reductase. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/4552",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000124275",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA31277",
    "snpedia_url": "https://www.snpedia.com/index.php/MTRR",
    "omim_url": "https://omim.org/search?index=entry&search=MTRR"
  },
  "NAT2": {
    "symbol": "NAT2",
    "gene_id": "10",
    "ensembl_id": "ENSG00000156006",
    "pharmgkb_id": "PA18",
    "name": "N-acetyltransferase 2",
    "chromosome": "8",
    "location": "8q",
    "is_vip": True,
    "has_cpic": True,
    "summary": "N-acetyltransferase 2. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/10",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000156006",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA18",
    "snpedia_url": "https://www.snpedia.com/index.php/NAT2",
    "omim_url": "https://omim.org/search?index=entry&search=NAT2"
  },
  "NFE2L2": {
    "symbol": "NFE2L2",
    "gene_id": "4780",
    "ensembl_id": "ENSG00000116044",
    "pharmgkb_id": "PA31588",
    "name": "NFE2 like bZIP transcription factor 2",
    "chromosome": "2",
    "location": "2q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "NFE2 like bZIP transcription factor 2. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/4780",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000116044",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA31588",
    "snpedia_url": "https://www.snpedia.com/index.php/NFE2L2",
    "omim_url": "https://omim.org/search?index=entry&search=NFE2L2"
  },
  "NOD2": {
    "symbol": "NOD2",
    "gene_id": "64127",
    "ensembl_id": "ENSG00000167207",
    "pharmgkb_id": "PA26074",
    "name": "nucleotide binding oligomerization domain containing 2",
    "chromosome": "16",
    "location": "16q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "nucleotide binding oligomerization domain containing 2. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/64127",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000167207",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA26074",
    "snpedia_url": "https://www.snpedia.com/index.php/NOD2",
    "omim_url": "https://omim.org/search?index=entry&search=NOD2"
  },
  "NOS3": {
    "symbol": "NOS3",
    "gene_id": "4846",
    "ensembl_id": "ENSG00000164867",
    "pharmgkb_id": "PA254",
    "name": "nitric oxide synthase 3",
    "chromosome": "7",
    "location": "7q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "nitric oxide synthase 3. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/4846",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000164867",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA254",
    "snpedia_url": "https://www.snpedia.com/index.php/NOS3",
    "omim_url": "https://omim.org/search?index=entry&search=NOS3"
  },
  "NPY": {
    "symbol": "NPY",
    "gene_id": "4852",
    "ensembl_id": "ENSG00000122585",
    "pharmgkb_id": "PA255",
    "name": "neuropeptide Y",
    "chromosome": "7",
    "location": "7q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "neuropeptide Y. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/4852",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000122585",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA255",
    "snpedia_url": "https://www.snpedia.com/index.php/NPY",
    "omim_url": "https://omim.org/search?index=entry&search=NPY"
  },
  "PCSK9": {
    "symbol": "PCSK9",
    "gene_id": "255738",
    "ensembl_id": "ENSG00000169174",
    "pharmgkb_id": "PA38617",
    "name": "proprotein convertase subtilisin/kexin type 9",
    "chromosome": "1",
    "location": "1q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "proprotein convertase subtilisin/kexin type 9. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/255738",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000169174",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA38617",
    "snpedia_url": "https://www.snpedia.com/index.php/PCSK9",
    "omim_url": "https://omim.org/search?index=entry&search=PCSK9"
  },
  "PNPLA3": {
    "symbol": "PNPLA3",
    "gene_id": "80339",
    "ensembl_id": "ENSG00000100344",
    "pharmgkb_id": "PA38592",
    "name": "patatin like phospholipase domain containing 3",
    "chromosome": "22",
    "location": "22q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "patatin like phospholipase domain containing 3. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/80339",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000100344",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA38592",
    "snpedia_url": "https://www.snpedia.com/index.php/PNPLA3",
    "omim_url": "https://omim.org/search?index=entry&search=PNPLA3"
  },
  "POMC": {
    "symbol": "POMC",
    "gene_id": "5443",
    "ensembl_id": "ENSG00000115138",
    "pharmgkb_id": "PA33526",
    "name": "proopiomelanocortin",
    "chromosome": "2",
    "location": "2q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "proopiomelanocortin. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/5443",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000115138",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA33526",
    "snpedia_url": "https://www.snpedia.com/index.php/POMC",
    "omim_url": "https://omim.org/search?index=entry&search=POMC"
  },
  "PPARG": {
    "symbol": "PPARG",
    "gene_id": "5468",
    "ensembl_id": "ENSG00000132170",
    "pharmgkb_id": "PA281",
    "name": "peroxisome proliferator activated receptor gamma",
    "chromosome": "3",
    "location": "3q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "peroxisome proliferator activated receptor gamma. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/5468",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000132170",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA281",
    "snpedia_url": "https://www.snpedia.com/index.php/PPARG",
    "omim_url": "https://omim.org/search?index=entry&search=PPARG"
  },
  "PTGIS": {
    "symbol": "PTGIS",
    "gene_id": "5740",
    "ensembl_id": "ENSG00000124212",
    "pharmgkb_id": "PA292",
    "name": "prostaglandin I2 synthase",
    "chromosome": "20",
    "location": "20q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "prostaglandin I2 synthase. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/5740",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000124212",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA292",
    "snpedia_url": "https://www.snpedia.com/index.php/PTGIS",
    "omim_url": "https://omim.org/search?index=entry&search=PTGIS"
  },
  "PTGS2": {
    "symbol": "PTGS2",
    "gene_id": "5743",
    "ensembl_id": "ENSG00000073756",
    "pharmgkb_id": "PA293",
    "name": "prostaglandin-endoperoxide synthase 2",
    "chromosome": "1",
    "location": "1q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "prostaglandin-endoperoxide synthase 2. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/5743",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000073756",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA293",
    "snpedia_url": "https://www.snpedia.com/index.php/PTGS2",
    "omim_url": "https://omim.org/search?index=entry&search=PTGS2"
  },
  "RBP4": {
    "symbol": "RBP4",
    "gene_id": "5950",
    "ensembl_id": "ENSG00000138207",
    "pharmgkb_id": "PA34289",
    "name": "retinol binding protein 4",
    "chromosome": "10",
    "location": "10q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "retinol binding protein 4. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/5950",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000138207",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA34289",
    "snpedia_url": "https://www.snpedia.com/index.php/RBP4",
    "omim_url": "https://omim.org/search?index=entry&search=RBP4"
  },
  "SLC19A1": {
    "symbol": "SLC19A1",
    "gene_id": "6573",
    "ensembl_id": "ENSG00000173638",
    "pharmgkb_id": "PA327",
    "name": "solute carrier family 19 member 1",
    "chromosome": "21",
    "location": "21q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "solute carrier family 19 member 1. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/6573",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000173638",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA327",
    "snpedia_url": "https://www.snpedia.com/index.php/SLC19A1",
    "omim_url": "https://omim.org/search?index=entry&search=SLC19A1"
  },
  "SLC30A8": {
    "symbol": "SLC30A8",
    "gene_id": "169026",
    "ensembl_id": "ENSG00000164756",
    "pharmgkb_id": "PA134915546",
    "name": "solute carrier family 30 member 8",
    "chromosome": "8",
    "location": "8q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "solute carrier family 30 member 8. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/169026",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000164756",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA134915546",
    "snpedia_url": "https://www.snpedia.com/index.php/SLC30A8",
    "omim_url": "https://omim.org/search?index=entry&search=SLC30A8"
  },
  "SLCO1B1": {
    "symbol": "SLCO1B1",
    "gene_id": "10599",
    "ensembl_id": "ENSG00000134538",
    "pharmgkb_id": "PA134865839",
    "name": "solute carrier organic anion transporter family member 1B1",
    "chromosome": "12",
    "location": "12q",
    "is_vip": True,
    "has_cpic": True,
    "summary": "solute carrier organic anion transporter family member 1B1. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/10599",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000134538",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA134865839",
    "snpedia_url": "https://www.snpedia.com/index.php/SLCO1B1",
    "omim_url": "https://omim.org/search?index=entry&search=SLCO1B1"
  },
  "SOD1": {
    "symbol": "SOD1",
    "gene_id": "6647",
    "ensembl_id": "ENSG00000142168",
    "pharmgkb_id": "PA334",
    "name": "superoxide dismutase 1",
    "chromosome": "21",
    "location": "21q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "superoxide dismutase 1. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/6647",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000142168",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA334",
    "snpedia_url": "https://www.snpedia.com/index.php/SOD1",
    "omim_url": "https://omim.org/search?index=entry&search=SOD1"
  },
  "SOD2": {
    "symbol": "SOD2",
    "gene_id": "6648",
    "ensembl_id": "ENSG00000112096",
    "pharmgkb_id": "PA36017",
    "name": "superoxide dismutase 2",
    "chromosome": "6",
    "location": "6q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "superoxide dismutase 2. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/6648",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000112096",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA36017",
    "snpedia_url": "https://www.snpedia.com/index.php/SOD2",
    "omim_url": "https://omim.org/search?index=entry&search=SOD2"
  },
  "TCF7L2": {
    "symbol": "TCF7L2",
    "gene_id": "6934",
    "ensembl_id": "ENSG00000148737",
    "pharmgkb_id": "PA36394",
    "name": "transcription factor 7 like 2",
    "chromosome": "10",
    "location": "10q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "transcription factor 7 like 2. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/6934",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000148737",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA36394",
    "snpedia_url": "https://www.snpedia.com/index.php/TCF7L2",
    "omim_url": "https://omim.org/search?index=entry&search=TCF7L2"
  },
  "TCN2": {
    "symbol": "TCN2",
    "gene_id": "6948",
    "ensembl_id": "ENSG00000185339",
    "pharmgkb_id": "PA36404",
    "name": "transcobalamin 2",
    "chromosome": "22",
    "location": "22q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "transcobalamin 2. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/6948",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000185339",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA36404",
    "snpedia_url": "https://www.snpedia.com/index.php/TCN2",
    "omim_url": "https://omim.org/search?index=entry&search=TCN2"
  },
  "TM6SF2": {
    "symbol": "TM6SF2",
    "gene_id": "53345",
    "ensembl_id": "ENSG00000213996",
    "pharmgkb_id": "PA36562",
    "name": "transmembrane 6 superfamily member 2",
    "chromosome": "19",
    "location": "19q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "transmembrane 6 superfamily member 2. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/53345",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000213996",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA36562",
    "snpedia_url": "https://www.snpedia.com/index.php/TM6SF2",
    "omim_url": "https://omim.org/search?index=entry&search=TM6SF2"
  },
  "TNF": {
    "symbol": "TNF",
    "gene_id": "7124",
    "ensembl_id": "ENSG00000204490, ENSG00000206439, ENSG00000223952, ENSG00000228321, ENSG00000228849, ENSG00000230108, ENSG00000232810",
    "pharmgkb_id": "PA435",
    "name": "tumor necrosis factor",
    "chromosome": "6",
    "location": "6q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "tumor necrosis factor. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/7124",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000204490, ENSG00000206439, ENSG00000223952, ENSG00000228321, ENSG00000228849, ENSG00000230108, ENSG00000232810",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA435",
    "snpedia_url": "https://www.snpedia.com/index.php/TNF",
    "omim_url": "https://omim.org/search?index=entry&search=TNF"
  },
  "TPMT": {
    "symbol": "TPMT",
    "gene_id": "7172",
    "ensembl_id": "ENSG00000137364",
    "pharmgkb_id": "PA356",
    "name": "thiopurine S-methyltransferase",
    "chromosome": "6",
    "location": "6q",
    "is_vip": True,
    "has_cpic": True,
    "summary": "thiopurine S-methyltransferase. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/7172",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000137364",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA356",
    "snpedia_url": "https://www.snpedia.com/index.php/TPMT",
    "omim_url": "https://omim.org/search?index=entry&search=TPMT"
  },
  "TRIB1": {
    "symbol": "TRIB1",
    "gene_id": "10221",
    "ensembl_id": "ENSG00000173334",
    "pharmgkb_id": "PA134963922",
    "name": "tribbles pseudokinase 1",
    "chromosome": "8",
    "location": "8q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "tribbles pseudokinase 1. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/10221",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000173334",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA134963922",
    "snpedia_url": "https://www.snpedia.com/index.php/TRIB1",
    "omim_url": "https://omim.org/search?index=entry&search=TRIB1"
  },
  "TTR": {
    "symbol": "TTR",
    "gene_id": "7276",
    "ensembl_id": "ENSG00000118271",
    "pharmgkb_id": "PA37069",
    "name": "transthyretin",
    "chromosome": "18",
    "location": "18q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "transthyretin. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/7276",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000118271",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA37069",
    "snpedia_url": "https://www.snpedia.com/index.php/TTR",
    "omim_url": "https://omim.org/search?index=entry&search=TTR"
  },
  "UGT1A1": {
    "symbol": "UGT1A1",
    "gene_id": "54658",
    "ensembl_id": "ENSG00000241635",
    "pharmgkb_id": "PA420",
    "name": "UDP glucuronosyltransferase 1 family, polypeptide A1",
    "chromosome": "2",
    "location": "2q",
    "is_vip": True,
    "has_cpic": True,
    "summary": "UDP glucuronosyltransferase 1 family, polypeptide A1. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/54658",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000241635",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA420",
    "snpedia_url": "https://www.snpedia.com/index.php/UGT1A1",
    "omim_url": "https://omim.org/search?index=entry&search=UGT1A1"
  },
  "VDR": {
    "symbol": "VDR",
    "gene_id": "7421",
    "ensembl_id": "ENSG00000111424",
    "pharmgkb_id": "PA37301",
    "name": "vitamin D receptor",
    "chromosome": "12",
    "location": "12q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "vitamin D receptor. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/7421",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000111424",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA37301",
    "snpedia_url": "https://www.snpedia.com/index.php/VDR",
    "omim_url": "https://omim.org/search?index=entry&search=VDR"
  },
  "VKORC1": {
    "symbol": "VKORC1",
    "gene_id": "79001",
    "ensembl_id": "ENSG00000167397",
    "pharmgkb_id": "PA133787052",
    "name": "vitamin K epoxide reductase complex subunit 1",
    "chromosome": "16",
    "location": "16q",
    "is_vip": True,
    "has_cpic": True,
    "summary": "vitamin K epoxide reductase complex subunit 1. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/79001",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000167397",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA133787052",
    "snpedia_url": "https://www.snpedia.com/index.php/VKORC1",
    "omim_url": "https://omim.org/search?index=entry&search=VKORC1"
  },
  "WFS1": {
    "symbol": "WFS1",
    "gene_id": "7466",
    "ensembl_id": "ENSG00000109501",
    "pharmgkb_id": "PA37365",
    "name": "wolframin ER transmembrane glycoprotein",
    "chromosome": "4",
    "location": "4q",
    "is_vip": True,
    "has_cpic": False,
    "summary": "wolframin ER transmembrane glycoprotein. Gen relevante en farmacogenetica y nutricion clinica.",
    "ncbi_url": "https://www.ncbi.nlm.nih.gov/gene/7466",
    "ensembl_url": "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000109501",
    "pharmgkb_url": "https://www.pharmgkb.org/gene/PA37365",
    "snpedia_url": "https://www.snpedia.com/index.php/WFS1",
    "omim_url": "https://omim.org/search?index=entry&search=WFS1"
  }
}
