"""
Genera local_db/supplement_dosing.json â€” base de DOSIS de suplementos y hierbas.
Dosis basadas en literatura clÃ­nica (EFSA/NIH-ODS/Examine/Cochrane/monografÃ­as EMA).
BilingÃ¼e ES/EN. Ejecuta:  python scripts/build_dosing_db.py
"""
import json, os

# Campos por fila (tupla):
# slug, name, category_es, category_en, standard, therapeutic, form_es, form_en,
# timing_es, timing_en, upper_limit, evidence, interactions_es, interactions_en,
# notes_es, notes_en
R = [
("omega3","Omega-3 (EPA/DHA)","Ãcido graso","Fatty acid",
 "250â€“[DOSIS_CLINICA_REMOVIDA] EPA+DHA/dÃ­a","2â€“[DOSIS_CLINICA_REMOVIDA] EPA+DHA/dÃ­a (hipertrigliceridemia)",
 "Aceite de pescado (TG o Ã©ster etÃ­lico)","Fish oil (TG or ethyl ester)",
 "Con comida grasa","With a fatty meal","â‰¤[DOSIS_CLINICA_REMOVIDA]/dÃ­a (EFSA)","ClÃ­nico (meta-anÃ¡lisis)",
 "Anticoagulantes/antiplaquetarios a dosis altas","Anticoagulants/antiplatelets at high doses",
 "Reduce TG 20â€“30% con 2â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a. Elegir ratio EPA:DHA segÃºn objetivo (EPAâ†’TG/Ã¡nimo).",
 "Lowers TG 20â€“30% at 2â€“[DOSIS_CLINICA_REMOVIDA]y. Pick EPA:DHA ratio by goal (EPAâ†’TG/mood)."),
("vitd","Vitamina D3","Vitamina liposoluble","Fat-soluble vitamin",
 "800â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a","4000â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (dÃ©ficit, con control 25-OH-D)",
 "Colecalciferol (D3)","Cholecalciferol (D3)","Con comida grasa","With a fatty meal",
 "[DOSIS_CLINICA_REMOVIDA]/dÃ­a (UL EFSA adultos)","ClÃ­nico",
 "Tiazidas (hipercalcemia); dosis altas con calcio","Thiazides (hypercalcemia); high dose with calcium",
 "Objetivo 25-OH-D 30â€“50 ng/mL. Cofactores: magnesio y K2.",
 "Target 25-OH-D 30â€“50 ng/mL. Cofactors: magnesium and K2."),
("magnesium","Magnesio","Mineral","Mineral",
 "200â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (elemental)","300â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (migraÃ±a, calambres, sueÃ±o)",
 "Glicinato/citrato/malato","Glycinate/citrate/malate","Noche (glicinato) o con comida","Evening (glycinate) or with food",
 "[DOSIS_CLINICA_REMOVIDA]/dÃ­a suplementario (UL, solo suplemento)","ClÃ­nico",
 "AntibiÃ³ticos (quinolonas/tetraciclinas): separar 2â€“4 h","Antibiotics (quinolones/tetracyclines): separate 2â€“4 h",
 "Ã“xido tiene baja absorciÃ³n; glicinato mejor tolerado. Citrato si estreÃ±imiento.",
 "Oxide poorly absorbed; glycinate best tolerated. Citrate if constipation."),
("berberine","Berberina","Alcaloide vegetal","Plant alkaloid",
 "[DOSIS_CLINICA_REMOVIDA] 2â€“3Ã—/dÃ­a","[DOSIS_CLINICA_REMOVIDA]/dÃ­a repartido (glucosa/lÃ­pidos)",
 "Berberina HCl","Berberine HCl","Antes de comidas principales","Before main meals","No establecido (usar â‰¤3 meses y reevaluar)","ClÃ­nico",
 "Inhibe CYP3A4 (ciclosporina, estatinas); metformina (sinergia glucÃ©mica)","Inhibits CYP3A4 (cyclosporine, statins); metformin (glycemic synergy)",
 "Baja HbA1c ~0.7â€“1%. Efecto tipo metformina. GI si dosis Ãºnica alta â†’ repartir.",
 "Lowers HbA1c ~0.7â€“1%. Metformin-like. GI upset if single high dose â†’ split."),
("curcumin","Curcumina","Polifenol","Polyphenol",
 "500â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (extracto)","1000â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (con piperina o formulaciÃ³n)",
 "Extracto 95% curcuminoides + piperina/fitosomas","95% curcuminoid extract + piperine/phytosome",
 "Con comida grasa","With a fatty meal","No establecido","ClÃ­nico/preclÃ­nico",
 "Anticoagulantes; sustratos CYP; suspender antes de cirugÃ­a","Anticoagulants; CYP substrates; stop before surgery",
 "Baja biodisponibilidad â†’ usar piperina, fitosoma o nanoemulsiÃ³n.",
 "Low bioavailability â†’ use piperine, phytosome or nanoemulsion."),
("coq10","Coenzima Q10","Ubiquinona","Ubiquinone",
 "100â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a","[DOSIS_CLINICA_REMOVIDA]/dÃ­a (miopatÃ­a por estatinas, IC)",
 "Ubiquinol (reducido) o ubiquinona","Ubiquinol (reduced) or ubiquinone","Con comida grasa","With a fatty meal","No establecido","ClÃ­nico (mixto)",
 "Warfarina (puede reducir INR)","Warfarin (may reduce INR)",
 "Ubiquinol mejor absorbido >50 aÃ±os. Ãštil en mialgia por estatinas.",
 "Ubiquinol better absorbed >50 y. Useful for statin myalgia."),
("creatine","Creatina","AminoÃ¡cido derivado","Amino acid derivative",
 "3â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (mantenimiento)","[DOSIS_CLINICA_REMOVIDA]/dÃ­a 5â€“7 d (carga, opcional)",
 "Monohidrato","Monohydrate","Cualquier hora; constante","Any time; consistent","No aplica (seguro a 3â€“[DOSIS_CLINICA_REMOVIDA])","ClÃ­nico (fuerte)",
 "Ninguna clÃ­nicamente relevante","None clinically relevant",
 "Fuerza/masa y cogniciÃ³n. Monohidrato es el estÃ¡ndar de oro. HidrataciÃ³n.",
 "Strength/mass and cognition. Monohydrate is gold standard. Hydrate."),
("melatonin","Melatonina","Neurohormona","Neurohormone",
 "0.5â€“[DOSIS_CLINICA_REMOVIDA]","0.5â€“[DOSIS_CLINICA_REMOVIDA] (jet lag, insomnio de inicio)",
 "LiberaciÃ³n inmediata o prolongada","Immediate or prolonged release","30â€“60 min antes de dormir","30â€“60 min before bed","No establecido; empezar bajo","ClÃ­nico",
 "Sedantes; anticoagulantes; inmunosupresores","Sedatives; anticoagulants; immunosuppressants",
 "Dosis baja suele bastar; mÃ¡s no es mejor. CronobiÃ³tico (regula fase).",
 "Low dose usually enough; more isn't better. Chronobiotic (phase-shifts)."),
("zinc","Zinc","Mineral","Mineral",
 "8â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a","25â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (corto plazo, resfriado)",
 "Citrato/picolinato/gluconato","Citrate/picolinate/gluconate","Con comida (evita nÃ¡usea)","With food (avoids nausea)","[DOSIS_CLINICA_REMOVIDA]/dÃ­a (UL)","ClÃ­nico",
 "AntibiÃ³ticos (quinolonas); cobre (deplece con uso crÃ³nico)","Antibiotics (quinolones); copper (depletes with chronic use)",
 ">[DOSIS_CLINICA_REMOVIDA]/dÃ­a crÃ³nico â†’ aÃ±adir 1â€“[DOSIS_CLINICA_REMOVIDA] cobre. AbsorciÃ³n compite con hierro.",
 ">[DOSIS_CLINICA_REMOVIDA] chronic â†’ add 1â€“[DOSIS_CLINICA_REMOVIDA] copper. Absorption competes with iron."),
("vitc","Vitamina C","Vitamina hidrosoluble","Water-soluble vitamin",
 "75â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (RDA)","500â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (antioxidante)",
 "Ãcido ascÃ³rbico / liposomal","Ascorbic acid / liposomal","Repartida; con comida","Split; with food","[DOSIS_CLINICA_REMOVIDA]/dÃ­a (UL)","ClÃ­nico",
 "Dosis altas: riesgo de oxalato (cÃ¡lculos)","High dose: oxalate risk (stones)",
 "Mejora absorciÃ³n de hierro no-hemo. Repartir mejora tolerancia.",
 "Improves non-heme iron absorption. Splitting improves tolerance."),
("b12","Vitamina B12","Vitamina hidrosoluble","Water-soluble vitamin",
 "2.4 Âµg/dÃ­a (RDA)","500â€“1000 Âµg/dÃ­a (dÃ©ficit, veganos, malabsorciÃ³n)",
 "Metilcobalamina / cianocobalamina","Methylcobalamin / cyanocobalamin","Cualquier hora","Any time","No establecido (segura)","ClÃ­nico",
 "Metformina e IBP reducen absorciÃ³n","Metformin and PPIs reduce absorption",
 "Sublingual o IM si malabsorciÃ³n. Verificar con Ã¡cido metilmalÃ³nico.",
 "Sublingual or IM if malabsorption. Confirm with methylmalonic acid."),
("folate","Folato (B9)","Vitamina hidrosoluble","Water-soluble vitamin",
 "400 Âµg DFE/dÃ­a","400â€“800 Âµg/dÃ­a (embarazo/dÃ©ficit)",
 "Metilfolato (5-MTHF) o Ã¡cido fÃ³lico","Methylfolate (5-MTHF) or folic acid","Cualquier hora","Any time","1000 Âµg/dÃ­a Ã¡cido fÃ³lico (UL)","ClÃ­nico",
 "Metotrexato, antiepilÃ©pticos","Methotrexate, antiepileptics",
 "En MTHFR C677T preferir metilfolato. No enmascarar dÃ©ficit de B12.",
 "In MTHFR C677T prefer methylfolate. Don't mask B12 deficiency."),
("iron","Hierro","Mineral","Mineral",
 "8â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (RDA)","40â€“[DOSIS_CLINICA_REMOVIDA] elemental (dÃ©ficit, dÃ­as alternos)",
 "Bisglicinato / sulfato ferroso","Bisglycinate / ferrous sulfate","En ayunas + vit C; dÃ­as alternos","Fasting + vit C; alternate days","[DOSIS_CLINICA_REMOVIDA]/dÃ­a (UL)","ClÃ­nico",
 "Separar de calcio, cafÃ©, tÃ©, IBP, levotiroxina","Separate from calcium, coffee, tea, PPIs, levothyroxine",
 "DÃ­as alternos mejora absorciÃ³n y tolerancia. Confirmar con ferritina.",
 "Alternate-day dosing improves absorption/tolerance. Confirm with ferritin."),
("calcium","Calcio","Mineral","Mineral",
 "1000â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (dieta+suplemento)","â‰¤[DOSIS_CLINICA_REMOVIDA] por toma (fraccionar)",
 "Citrato (mejor si IBP) / carbonato","Citrate (better with PPIs) / carbonate","Citrato cualquier hora; carbonato con comida","Citrate anytime; carbonate with food","[DOSIS_CLINICA_REMOVIDA]/dÃ­a (UL)","ClÃ­nico",
 "Reduce absorciÃ³n de hierro, zinc, levotiroxina, quinolonas","Reduces iron, zinc, levothyroxine, quinolone absorption",
 "Fraccionar â‰¤[DOSIS_CLINICA_REMOVIDA]. AcompaÃ±ar de vit D y K2.",
 "Split â‰¤[DOSIS_CLINICA_REMOVIDA]. Pair with vit D and K2."),
("k2","Vitamina K2 (MK-7)","Vitamina liposoluble","Fat-soluble vitamin",
 "90â€“120 Âµg/dÃ­a","180 Âµg/dÃ­a (salud Ã³sea/vascular)",
 "MK-7 (menaquinona-7)","MK-7 (menaquinone-7)","Con comida grasa","With a fatty meal","No establecido","ClÃ­nico/preclÃ­nico",
 "Contraindicado con warfarina (antagonismo)","Contraindicated with warfarin (antagonism)",
 "Dirige el calcio al hueso. Sinergia con D3.",
 "Directs calcium to bone. Synergy with D3."),
("ashwagandha","Ashwagandha","AdaptÃ³geno (hierba)","Adaptogen (herb)",
 "300â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (extracto KSM-66/Sensoril)","[DOSIS_CLINICA_REMOVIDA]/dÃ­a (estrÃ©s/cortisol)",
 "Extracto de raÃ­z estandarizado","Standardized root extract","Con comida; noche si sueÃ±o","With food; evening for sleep","No establecido; ciclar","ClÃ­nico",
 "Sedantes, tiroides (puede subir T4), inmunosupresores","Sedatives, thyroid (may raise T4), immunosuppressants",
 "Reduce cortisol y ansiedad. PrecauciÃ³n en hipertiroidismo y embarazo.",
 "Lowers cortisol and anxiety. Caution in hyperthyroidism and pregnancy."),
("rhodiola","Rhodiola rosea","AdaptÃ³geno (hierba)","Adaptogen (herb)",
 "200â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (3% rosavinas/1% salidrÃ³sido)","400â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (fatiga)",
 "Extracto de raÃ­z","Root extract","MaÃ±ana, en ayunas","Morning, fasting","No establecido","ClÃ­nico (moderado)",
 "Estimulantes; antidepresivos (teÃ³rico)","Stimulants; antidepressants (theoretical)",
 "Anti-fatiga y rendimiento cognitivo bajo estrÃ©s. Puede activar â†’ evitar noche.",
 "Anti-fatigue and cognition under stress. May be activating â†’ avoid at night."),
("probiotics","ProbiÃ³ticos","Microorganismos","Microorganisms",
 "1â€“10 mil millones UFC/dÃ­a","10â€“50 mil millones UFC/dÃ­a (cepas especÃ­ficas)",
 "CÃ¡psula multicepa/monocepa","Multi/single-strain capsule","Con o antes de comida","With or before a meal","No aplica","ClÃ­nico (cepa-dependiente)",
 "InmunosupresiÃ³n severa (riesgo bacteriemia)","Severe immunosuppression (bacteremia risk)",
 "Efecto es CEPA-especÃ­fico: elegir cepa segÃºn indicaciÃ³n, no 'genÃ©rico'.",
 "Effect is STRAIN-specific: choose strain by indication, not 'generic'."),
("psyllium","Psyllium (fibra)","Fibra soluble","Soluble fiber",
 "[DOSIS_CLINICA_REMOVIDA] 1â€“3Ã—/dÃ­a","10â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (colesterol/glucemia)",
 "CÃ¡scara de Plantago ovata","Plantago ovata husk","Con agua abundante, antes de comidas","With plenty of water, before meals","No aplica","ClÃ­nico",
 "Separar de fÃ¡rmacos 2â€“4 h (reduce absorciÃ³n)","Separate from drugs 2â€“4 h (reduces absorption)",
 "Baja LDL y glucosa posprandial. Subir dosis gradual (gases).",
 "Lowers LDL and postprandial glucose. Titrate up gradually (gas)."),
("nac","N-acetilcisteÃ­na (NAC)","AminoÃ¡cido modificado","Modified amino acid",
 "[DOSIS_CLINICA_REMOVIDA]/dÃ­a","1200â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (mucolÃ­tico, hepatoprotecciÃ³n)",
 "NAC","NAC","Con o sin comida","With or without food","No establecido","ClÃ­nico",
 "Nitroglicerina (hipotensiÃ³n); anticoagulantes","Nitroglycerin (hypotension); anticoagulants",
 "Precursor de glutatiÃ³n. Antioxidante; Ãºtil en hÃ­gado y respiratorio.",
 "Glutathione precursor. Antioxidant; useful for liver and respiratory."),
("ala","Ãcido alfa-lipoico","Antioxidante","Antioxidant",
 "300â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a","600â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (neuropatÃ­a diabÃ©tica)",
 "R-ALA o racÃ©mico","R-ALA or racemic","En ayunas, antes de comida","Fasting, before a meal","No establecido","ClÃ­nico",
 "Puede bajar glucosa (ajustar antidiabÃ©ticos); tiroides","May lower glucose (adjust antidiabetics); thyroid",
 "R-ALA mÃ¡s biodisponible. Mejora sensibilidad a insulina y neuropatÃ­a.",
 "R-ALA more bioavailable. Improves insulin sensitivity and neuropathy."),
("quercetin","Quercetina","Flavonoide","Flavonoid",
 "[DOSIS_CLINICA_REMOVIDA]/dÃ­a","[DOSIS_CLINICA_REMOVIDA] 2Ã—/dÃ­a (alergia, rendimiento)",
 "Con bromelina/vit C para absorciÃ³n","With bromelain/vit C for absorption","Con comida","With food","No establecido","PreclÃ­nico/clÃ­nico",
 "Inhibe CYP3A4/P-gp (ciclosporina, algunos fÃ¡rmacos)","Inhibits CYP3A4/P-gp (cyclosporine, some drugs)",
 "Antiinflamatorio/antihistamÃ­nico natural. Baja biodisponibilidad.",
 "Natural anti-inflammatory/antihistamine. Low bioavailability."),
("resveratrol","Resveratrol","Polifenol (estilbeno)","Polyphenol (stilbene)",
 "150â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a","[DOSIS_CLINICA_REMOVIDA]/dÃ­a (estudios metabÃ³licos)",
 "Trans-resveratrol","Trans-resveratrol","Con comida grasa","With a fatty meal","No establecido; GI a dosis altas","PreclÃ­nico (clÃ­nico mixto)",
 "Anticoagulantes; sustratos CYP","Anticoagulants; CYP substrates",
 "Activador de SIRT1 in vitro; evidencia humana modesta. Trans- es la forma activa.",
 "SIRT1 activator in vitro; modest human evidence. Trans- is the active form."),
("egcg","EGCG (tÃ© verde)","Catequina","Catechin",
 "300â€“[DOSIS_CLINICA_REMOVIDA] EGCG/dÃ­a","Hasta [DOSIS_CLINICA_REMOVIDA]/dÃ­a (con precauciÃ³n hepÃ¡tica)",
 "Extracto estandarizado de tÃ© verde","Standardized green tea extract","Con comida (reduce riesgo hepÃ¡tico)","With food (lowers liver risk)","â‰¤[DOSIS_CLINICA_REMOVIDA] EGCG/dÃ­a (EFSA, extracto)","ClÃ­nico",
 "HepatotÃ³xico en ayunas a dosis altas; reduce hierro","Hepatotoxic fasting at high dose; reduces iron",
 "Tomar CON comida. Vigilar transaminasas si dosis alta prolongada.",
 "Take WITH food. Monitor transaminases if prolonged high dose."),
("milkthistle","Cardo mariano (silimarina)","Hepatoprotector (hierba)","Hepatoprotector (herb)",
 "200â€“[DOSIS_CLINICA_REMOVIDA] silimarina/dÃ­a","420â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (hepatopatÃ­a)",
 "Extracto 70â€“80% silimarina","70â€“80% silymarin extract","Con comida","With food","No establecido","ClÃ­nico (moderado)",
 "Inhibe CYP2C9/3A4 (leve)","Inhibits CYP2C9/3A4 (mild)",
 "Hepatoprotector antioxidante. Evidencia mixta pero buen perfil de seguridad.",
 "Antioxidant hepatoprotector. Mixed evidence but good safety."),
("sawpalmetto","Saw palmetto","Fitoterapia (hierba)","Phytotherapy (herb)",
 "[DOSIS_CLINICA_REMOVIDA]/dÃ­a (extracto liposterÃ³lico)","[DOSIS_CLINICA_REMOVIDA]/dÃ­a (HPB)",
 "Extracto de Serenoa repens","Serenoa repens extract","Con comida","With food","No establecido","ClÃ­nico (mixto)",
 "Anticoagulantes; hormonal","Anticoagulants; hormonal",
 "SÃ­ntomas de HPB; evidencia inconsistente. Puede alterar PSA.",
 "BPH symptoms; inconsistent evidence. May alter PSA."),
("ginkgo","Ginkgo biloba","NootrÃ³pico (hierba)","Nootropic (herb)",
 "120â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (EGb 761)","[DOSIS_CLINICA_REMOVIDA]/dÃ­a (cogniciÃ³n/circulaciÃ³n)",
 "Extracto estandarizado 24/6","Standardized extract 24/6","Repartido, con comida","Split, with food","No establecido","ClÃ­nico (moderado)",
 "Alto riesgo con anticoagulantes/antiplaquetarios; suspender 7â€“10 d antes de cirugÃ­a","High risk with anticoagulants/antiplatelets; stop 7â€“10 d before surgery",
 "Antiagregante: Â¡cuidado con warfarina! Sangrado documentado.",
 "Antiplatelet: caution with warfarin! Documented bleeding."),
("ginseng","Ginseng (Panax)","AdaptÃ³geno (hierba)","Adaptogen (herb)",
 "200â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (4â€“7% ginsenÃ³sidos)","[DOSIS_CLINICA_REMOVIDA]/dÃ­a (fatiga/glucemia)",
 "Extracto de raÃ­z estandarizado","Standardized root extract","MaÃ±ana","Morning","No establecido; ciclar","ClÃ­nico (moderado)",
 "Warfarina (reduce INR); antidiabÃ©ticos; estimulantes","Warfarin (reduces INR); antidiabetics; stimulants",
 "Puede bajar glucosa. Activador â†’ evitar noche. Ciclar uso.",
 "May lower glucose. Activating â†’ avoid at night. Cycle use."),
("garlic","Ajo (alicina)","Fitoterapia (hierba)","Phytotherapy (herb)",
 "600â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (extracto)","â‰ˆ3.6â€“5.[DOSIS_CLINICA_REMOVIDA] alicina/dÃ­a","Extracto aÃ±ejado/comprimido con recubrimiento entÃ©rico","Aged extract/enteric-coated tablet","Con comida","With food","No establecido","ClÃ­nico",
 "Anticoagulantes/antiplaquetarios; suspender 7â€“10 d antes de cirugÃ­a; antirretrovirales","Anticoagulants/antiplatelets; stop 7â€“10 d before surgery; antiretrovirals",
 "Baja PA levemente y lÃ­pidos. Efecto antiplaquetario relevante en cirugÃ­a.",
 "Mild BP and lipid reduction. Antiplatelet effect relevant for surgery."),
("cinnamon","Canela (Ceylan)","Especia funcional","Functional spice",
 "1â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a","â‰¤[DOSIS_CLINICA_REMOVIDA]/dÃ­a corto plazo (glucemia)","CeylÃ¡n (baja cumarina) preferido sobre Cassia","Ceylon (low coumarin) preferred over Cassia","Con comidas con carbohidratos","With carb-containing meals","Cassia: cumarina hepatotÃ³xica â†’ limitar","ClÃ­nico (modesto)",
 "AntidiabÃ©ticos (aditivo); hepatotÃ³xicos (Cassia)","Antidiabetics (additive); hepatotoxics (Cassia)",
 "Usar CeylÃ¡n para evitar cumarina. Efecto glucÃ©mico modesto.",
 "Use Ceylon to avoid coumarin. Modest glycemic effect."),
("chromium","Cromo (picolinato)","Mineral traza","Trace mineral",
 "200 Âµg/dÃ­a","200â€“1000 Âµg/dÃ­a (resistencia a insulina)","Picolinato de cromo","Chromium picolinate","Con comida","With food","No establecido","ClÃ­nico (mixto)",
 "AntidiabÃ©ticos (aditivo); levotiroxina (separar)","Antidiabetics (additive); levothyroxine (separate)",
 "Puede mejorar sensibilidad a insulina; evidencia heterogÃ©nea.",
 "May improve insulin sensitivity; heterogeneous evidence."),
("inositol","Mio-inositol","Poliol","Polyol",
 "[DOSIS_CLINICA_REMOVIDA] 2Ã—/dÃ­a ([DOSIS_CLINICA_REMOVIDA]/dÃ­a)","2â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (SOP, con D-chiro 40:1)","Mio-inositol (+ D-chiro-inositol 40:1)","Myo-inositol (+ D-chiro-inositol 40:1)","Repartido, con comida","Split, with food","No establecido (bien tolerado)","ClÃ­nico",
 "AntidiabÃ©ticos (aditivo)","Antidiabetics (additive)",
 "SOP: mejora ovulaciÃ³n y resistencia a insulina. Ratio 40:1 mio:D-chiro.",
 "PCOS: improves ovulation and insulin resistance. 40:1 myo:D-chiro ratio."),
("taurine","Taurina","AminoÃ¡cido","Amino acid",
 "500â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a","3â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (rendimiento/cardiometabÃ³lico)","Taurina","Taurine","Cualquier hora","Any time","No establecido (segura)","ClÃ­nico (emergente)",
 "Litio (excreciÃ³n)","Lithium (excretion)",
 "Cardio y metabÃ³lico; buen perfil de seguridad.",
 "Cardio and metabolic; good safety profile."),
("glycine","Glicina","AminoÃ¡cido","Amino acid",
 "[DOSIS_CLINICA_REMOVIDA] antes de dormir","3â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (sueÃ±o/metabÃ³lico)","Glicina","Glycine","Antes de dormir","Before bed","No establecido","ClÃ­nico (moderado)",
 "Clozapina (reduce eficacia)","Clozapine (reduces efficacy)",
 "Mejora calidad del sueÃ±o y sensibilidad a insulina.",
 "Improves sleep quality and insulin sensitivity."),
("ltheanine","L-teanina","AminoÃ¡cido","Amino acid",
 "100â€“[DOSIS_CLINICA_REMOVIDA]","200â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (ansiedad/foco)","L-teanina","L-theanine","Con o sin cafeÃ­na","With or without caffeine","No establecido (segura)","ClÃ­nico",
 "Antihipertensivos (aditivo leve)","Antihypertensives (mild additive)",
 "Calma sin sedaciÃ³n. Sinergia con cafeÃ­na para foco.",
 "Calm without sedation. Synergy with caffeine for focus."),
("5htp","5-HTP","Precursor de serotonina","Serotonin precursor",
 "50â€“[DOSIS_CLINICA_REMOVIDA]","100â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (Ã¡nimo/sueÃ±o)","5-hidroxitriptÃ³fano","5-hydroxytryptophan","Noche; con carbohidrato","Evening; with a carb","No establecido; empezar bajo","ClÃ­nico (limitado)",
 "ISRS/IMAO: riesgo de sÃ­ndrome serotoninÃ©rgico","SSRIs/MAOIs: serotonin syndrome risk",
 "NO combinar con antidepresivos serotoninÃ©rgicos. Empezar bajo.",
 "Do NOT combine with serotonergic antidepressants. Start low."),
("same","SAMe","Donante de metilo","Methyl donor",
 "[DOSIS_CLINICA_REMOVIDA]/dÃ­a","800â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (depresiÃ³n/artrosis)","S-adenosil-metionina entÃ©rica","Enteric S-adenosyl-methionine","En ayunas","Fasting","No establecido","ClÃ­nico (moderado)",
 "ISRS (sÃ­ndrome serotoninÃ©rgico); bipolar (manÃ­a)","SSRIs (serotonin syndrome); bipolar (mania)",
 "Ãnimo y articulaciones. PrecauciÃ³n en trastorno bipolar.",
 "Mood and joints. Caution in bipolar disorder."),
("glucosamine","Glucosamina","AminosacÃ¡rido","Amino sugar",
 "[DOSIS_CLINICA_REMOVIDA]/dÃ­a","[DOSIS_CLINICA_REMOVIDA]/dÃ­a (sulfato, artrosis)","Sulfato de glucosamina (preferido)","Glucosamine sulfate (preferred)","Con comida","With food","No establecido","ClÃ­nico (mixto)",
 "Warfarina (puede subir INR)","Warfarin (may raise INR)",
 "Sulfato > HCl en evidencia. Efecto lento (semanas).",
 "Sulfate > HCl in evidence. Slow onset (weeks)."),
("collagen","ColÃ¡geno (pÃ©ptidos)","ProteÃ­na","Protein",
 "[DOSIS_CLINICA_REMOVIDA]/dÃ­a","[DOSIS_CLINICA_REMOVIDA]/dÃ­a (piel/articulaciones) o [DOSIS_CLINICA_REMOVIDA] +vit C (tendÃ³n)","PÃ©ptidos hidrolizados","Hydrolyzed peptides","Cualquier hora; tendÃ³n: 30â€“60 min pre-ejercicio","Any time; tendon: 30â€“60 min pre-exercise","No aplica","ClÃ­nico (emergente)",
 "Ninguna relevante","None relevant",
 "Piel/articulaciones a 10â€“[DOSIS_CLINICA_REMOVIDA]. TendÃ³n: [DOSIS_CLINICA_REMOVIDA] + vit C antes de cargar.",
 "Skin/joints at 10â€“[DOSIS_CLINICA_REMOVIDA]. Tendon: [DOSIS_CLINICA_REMOVIDA] + vit C before loading."),
("vite","Vitamina E","Vitamina liposoluble","Fat-soluble vitamin",
 "[DOSIS_CLINICA_REMOVIDA] (22.[DOSIS_CLINICA_REMOVIDA])/dÃ­a","â‰¤[DOSIS_CLINICA_REMOVIDA] ([DOSIS_CLINICA_REMOVIDA])/dÃ­a","d-alfa-tocoferol (mezcla de tocoferoles)","d-alpha-tocopherol (mixed tocopherols)","Con comida grasa","With a fatty meal","[DOSIS_CLINICA_REMOVIDA]/dÃ­a (UL)","ClÃ­nico",
 "Anticoagulantes (sangrado a dosis altas)","Anticoagulants (bleeding at high doses)",
 "Dosis altas aisladas pueden ser perjudiciales; preferir mezcla natural.",
 "High isolated doses may be harmful; prefer natural mixed form."),
("selenium","Selenio","Mineral traza","Trace mineral",
 "55 Âµg/dÃ­a","100â€“200 Âµg/dÃ­a (tiroides autoinmune)","Selenometionina","Selenomethionine","Con comida","With food","400 Âµg/dÃ­a (UL)","ClÃ­nico",
 "Margen estrecho: no exceder UL","Narrow margin: do not exceed UL",
 "Ãštil en tiroiditis de Hashimoto. TÃ³xico por encima del UL.",
 "Useful in Hashimoto's thyroiditis. Toxic above UL."),
("iodine","Yodo","Mineral traza","Trace mineral",
 "150 Âµg/dÃ­a","150â€“220 Âµg/dÃ­a (embarazo/lactancia)","Yoduro potÃ¡sico / algas dosificadas","Potassium iodide / dosed kelp","Cualquier hora","Any time","1100 Âµg/dÃ­a (UL)","ClÃ­nico",
 "Antitiroideos; puede desencadenar disfunciÃ³n tiroidea","Antithyroid drugs; may trigger thyroid dysfunction",
 "Exceso tan daÃ±ino como dÃ©ficit. Cuidado con algas no dosificadas.",
 "Excess as harmful as deficiency. Beware undosed kelp."),
("potassium","Potasio","Electrolito","Electrolyte",
 "3500â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (dieta)","â‰¤[DOSIS_CLINICA_REMOVIDA]/dosis (suplemento OTC)","Citrato/cloruro (bajo control)","Citrate/chloride (monitored)","Con comida","With food","Suplemento limitado; riesgo cardÃ­aco","ClÃ­nico",
 "IECA/ARA-II, diurÃ©ticos ahorradores: hiperpotasemia","ACEi/ARB, K-sparing diuretics: hyperkalemia",
 "Preferir dieta. Suplementar solo con control (arritmias).",
 "Prefer diet. Supplement only with monitoring (arrhythmia)."),
("vita","Vitamina A","Vitamina liposoluble","Fat-soluble vitamin",
 "700â€“900 Âµg RAE/dÃ­a","â‰¤3000 Âµg/dÃ­a (dÃ©ficit, con control)","Retinol / betacaroteno","Retinol / beta-carotene","Con comida grasa","With a fatty meal","3000 Âµg RAE/dÃ­a (UL)","ClÃ­nico",
 "Retinoides; hepatotÃ³xicos; teratÃ³geno en embarazo","Retinoids; hepatotoxics; teratogen in pregnancy",
 "Betacaroteno mÃ¡s seguro (sin toxicidad aguda). Retinol: no exceder UL en embarazo.",
 "Beta-carotene safer (no acute toxicity). Retinol: don't exceed UL in pregnancy."),
("b1","Vitamina B1 (tiamina)","Vitamina hidrosoluble","Water-soluble vitamin",
 "1.1â€“1.[DOSIS_CLINICA_REMOVIDA]/dÃ­a","100â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (dÃ©ficit, alcoholismo)","Tiamina / benfotiamina","Thiamine / benfotiamine","Con comida","With food","No establecido (segura)","ClÃ­nico",
 "Ninguna relevante","None relevant",
 "Benfotiamina (liposoluble) mejor en neuropatÃ­a. DÃ©ficit comÃºn en alcoholismo.",
 "Benfotiamine (fat-soluble) better for neuropathy. Deficiency common in alcoholism."),
("b2","Vitamina B2 (riboflavina)","Vitamina hidrosoluble","Water-soluble vitamin",
 "1.1â€“1.[DOSIS_CLINICA_REMOVIDA]/dÃ­a","[DOSIS_CLINICA_REMOVIDA]/dÃ­a (profilaxis de migraÃ±a)","Riboflavina","Riboflavin","Con comida","With food","No establecido","ClÃ­nico",
 "Ninguna relevante","None relevant",
 "[DOSIS_CLINICA_REMOVIDA]/dÃ­a reduce frecuencia de migraÃ±a (efecto a 3 meses). Orina amarilla fluor.",
 "[DOSIS_CLINICA_REMOVIDA] reduces migraine frequency (effect at 3 months). Bright yellow urine."),
("b3","Vitamina B3 (niacina)","Vitamina hidrosoluble","Water-soluble vitamin",
 "14â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a","500â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (dislipidemia, con control)","Niacina / nicotinamida","Niacin / nicotinamide","Con comida","With food","[DOSIS_CLINICA_REMOVIDA]/dÃ­a niacina como suplemento (UL flushing)","ClÃ­nico",
 "Estatinas (miopatÃ­a); hepatotoxicidad a dosis altas","Statins (myopathy); hepatotoxicity at high doses",
 "Niacina sube HDL/baja Lp(a) pero causa flushing; vigilar hÃ­gado y glucosa.",
 "Niacin raises HDL/lowers Lp(a) but causes flushing; monitor liver and glucose."),
("b6","Vitamina B6 (piridoxina)","Vitamina hidrosoluble","Water-soluble vitamin",
 "1.3â€“1.[DOSIS_CLINICA_REMOVIDA]/dÃ­a","10â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (SPM, nÃ¡usea gestacional)","Piridoxina / P5P","Pyridoxine / P5P","Con comida","With food","[DOSIS_CLINICA_REMOVIDA]/dÃ­a (UL EFSA)","ClÃ­nico",
 "Levodopa (sin carbidopa); antiepilÃ©pticos","Levodopa (without carbidopa); antiepileptics",
 "No exceder crÃ³nicamente: neuropatÃ­a sensitiva por exceso. P5P forma activa.",
 "Don't exceed chronically: sensory neuropathy from excess. P5P is active form."),
("biotin","Biotina (B7)","Vitamina hidrosoluble","Water-soluble vitamin",
 "30 Âµg/dÃ­a","2.5â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (pelo/uÃ±as, evidencia limitada)","Biotina","Biotin","Con comida","With food","No establecido","DÃ©bil/clÃ­nico",
 "INTERFIERE en anÃ¡lisis de laboratorio (tiroides, troponina)","INTERFERES with lab assays (thyroid, troponin)",
 "Suspender 48â€“72 h antes de anÃ¡lisis de sangre (falsea resultados).",
 "Stop 48â€“72 h before blood tests (skews results)."),
("choline","Colina","Nutriente esencial","Essential nutrient",
 "425â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a","1â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (hÃ­gado graso, cogniciÃ³n)","Citicolina / alfa-GPC / bitartrato","Citicoline / alpha-GPC / bitartrate","Con comida","With food","[DOSIS_CLINICA_REMOVIDA]/dÃ­a (UL)","ClÃ­nico",
 "Ninguna relevante","None relevant",
 "Alfa-GPC y citicolina para cogniciÃ³n. Exceso â†’ olor corporal a pescado (TMAO).",
 "Alpha-GPC and citicoline for cognition. Excess â†’ fishy body odor (TMAO)."),
("copper","Cobre","Mineral traza","Trace mineral",
 "0.[DOSIS_CLINICA_REMOVIDA]/dÃ­a","1â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (con zinc crÃ³nico)","Bisglicinato de cobre","Copper bisglycinate","Con comida","With food","[DOSIS_CLINICA_REMOVIDA]/dÃ­a (UL)","ClÃ­nico",
 "Zinc en exceso deplece cobre","Excess zinc depletes copper",
 "AÃ±adir si tomas zinc alto crÃ³nico. Ratio zinc:cobre ~10:1.",
 "Add if on chronic high zinc. Zinc:copper ratio ~10:1."),
("manganese","Manganeso","Mineral traza","Trace mineral",
 "1.8â€“2.[DOSIS_CLINICA_REMOVIDA]/dÃ­a","No suele suplementarse aislado","Gluconato/quelato","Gluconate/chelate","Con comida","With food","[DOSIS_CLINICA_REMOVIDA]/dÃ­a (UL)","ClÃ­nico",
 "Neurotoxicidad por exceso (parkinsonismo)","Neurotoxicity from excess (parkinsonism)",
 "Rara vez deficitario (abundante en dieta). No exceder UL.",
 "Rarely deficient (abundant in diet). Don't exceed UL."),
("boron","Boro","Mineral traza","Trace mineral",
 "1â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a","3â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (hueso, testosterona)","Borato / fructoborato","Borate / fructoborate","Con comida","With food","[DOSIS_CLINICA_REMOVIDA]/dÃ­a (UL)","ClÃ­nico (limitado)",
 "Ninguna relevante","None relevant",
 "Modula vitamina D, magnesio y hormonas esteroideas. Dosis baja.",
 "Modulates vitamin D, magnesium and steroid hormones. Low dose."),
("tmg","BetaÃ­na (TMG)","Donante de metilo","Methyl donor",
 "1â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a","3â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (homocisteÃ­na, rendimiento)","Trimetilglicina","Trimethylglycine","Con comida","With food","No establecido","ClÃ­nico",
 "Ninguna relevante","None relevant",
 "Baja homocisteÃ­na (sinergia con B12/folato). Puede subir LDL a dosis altas.",
 "Lowers homocysteine (synergy with B12/folate). May raise LDL at high doses."),
("beta_alanine","Beta-alanina","AminoÃ¡cido","Amino acid",
 "3â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (repartido)","4â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (rendimiento anaerÃ³bico)","Beta-alanina","Beta-alanine","Repartido para evitar parestesia","Split to avoid paresthesia","No establecido (seguro)","ClÃ­nico (fuerte)",
 "Ninguna relevante","None relevant",
 "Sube carnosina muscular; mejora esfuerzos 1â€“4 min. Hormigueo (inofensivo) â†’ repartir.",
 "Raises muscle carnosine; improves 1â€“4 min efforts. Tingling (harmless) â†’ split."),
("citrulline","L-citrulina","AminoÃ¡cido","Amino acid",
 "3â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a","6â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (rendimiento, malato)","L-citrulina / citrulina malato","L-citrulline / citrulline malate","30â€“60 min pre-ejercicio","30â€“60 min pre-exercise","No establecido (segura)","ClÃ­nico",
 "Antihipertensivos; PDE5 (sildenafilo)","Antihypertensives; PDE5 (sildenafil)",
 "Sube Ã³xido nÃ­trico (mejor que arginina oral). Flujo sanguÃ­neo y bomba.",
 "Raises nitric oxide (better than oral arginine). Blood flow and pump."),
("carnitine","L-carnitina","AminoÃ¡cido derivado","Amino acid derivative",
 "500â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a","2â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (segÃºn objetivo)","L-carnitina / tartrato / ALCAR","L-carnitine / tartrate / ALCAR","Con carbohidrato para absorciÃ³n","With a carb for absorption","No establecido","ClÃ­nico (mixto)",
 "Hormona tiroidea (antagonismo leve); anticoagulantes","Thyroid hormone (mild antagonism); anticoagulants",
 "ALCAR cruza BHE (cogniciÃ³n); tartrato para recuperaciÃ³n. TMAO en exceso.",
 "ALCAR crosses BBB (cognition); tartrate for recovery. TMAO in excess."),
("tyrosine","L-tirosina","AminoÃ¡cido","Amino acid",
 "500â€“[DOSIS_CLINICA_REMOVIDA]","100â€“[DOSIS_CLINICA_REMOVIDA]/kg (estrÃ©s agudo/cogniciÃ³n)","L-tirosina","L-tyrosine","En ayunas, antes de estrÃ©s","Fasting, before stressor","No establecido","ClÃ­nico",
 "IMAO (crisis hipertensiva); hormona tiroidea","MAOIs (hypertensive crisis); thyroid hormone",
 "Precursor de dopamina/noradrenalina; Ãºtil bajo estrÃ©s/privaciÃ³n de sueÃ±o.",
 "Dopamine/noradrenaline precursor; useful under stress/sleep loss."),
("bacopa","Bacopa monnieri","NootrÃ³pico (hierba)","Nootropic (herb)",
 "[DOSIS_CLINICA_REMOVIDA]/dÃ­a (50% bacÃ³sidos)","300â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (memoria)","Extracto estandarizado","Standardized extract","Con comida grasa","With a fatty meal","No establecido","ClÃ­nico",
 "Sedantes; tiroides; anticolinÃ©rgicos","Sedatives; thyroid; anticholinergics",
 "Mejora memoria a 8â€“12 semanas (efecto lento). Puede dar molestia GI.",
 "Improves memory at 8â€“12 weeks (slow onset). May cause GI upset."),
("lions_mane","Melena de leÃ³n","Hongo funcional","Functional mushroom",
 "500â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a","1â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (cogniciÃ³n/nervio)","Extracto de Hericium erinaceus","Hericium erinaceus extract","Con comida","With food","No establecido","PreclÃ­nico/clÃ­nico",
 "Anticoagulantes (teÃ³rico)","Anticoagulants (theoretical)",
 "NGF/neurogÃ©nesis in vitro; evidencia humana emergente. Buscar cuerpo fructÃ­fero.",
 "NGF/neurogenesis in vitro; emerging human evidence. Seek fruiting body."),
("cordyceps","Cordyceps","Hongo funcional","Functional mushroom",
 "1â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a","3â€“4.[DOSIS_CLINICA_REMOVIDA]/dÃ­a (rendimiento/energÃ­a)","CS-4 / militaris","CS-4 / militaris","Con comida","With food","No establecido","ClÃ­nico (limitado)",
 "Anticoagulantes; inmunosupresores","Anticoagulants; immunosuppressants",
 "VO2max/energÃ­a; evidencia moderada. Militaris con mÃ¡s cordicepina.",
 "VO2max/energy; moderate evidence. Militaris has more cordycepin."),
("spirulina","Espirulina","Alga (superalimento)","Algae (superfood)",
 "1â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a","4â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (lÃ­pidos/alergia)","Polvo/comprimido (fuente segura)","Powder/tablet (safe source)","Con comida","With food","No establecido","ClÃ­nico (moderado)",
 "Inmunosupresores; anticoagulantes","Immunosuppressants; anticoagulants",
 "Baja LDL levemente; antioxidante. Riesgo de contaminaciÃ³n â†’ marca certificada.",
 "Mildly lowers LDL; antioxidant. Contamination risk â†’ certified brand."),
("boswellia","Boswellia (incienso)","Antiinflamatorio (hierba)","Anti-inflammatory (herb)",
 "300â€“[DOSIS_CLINICA_REMOVIDA] 2â€“3Ã—/dÃ­a","100â€“[DOSIS_CLINICA_REMOVIDA] AKBA/dÃ­a (artrosis)","Extracto (30â€“65% Ã¡c. boswÃ©licos, AKBA)","Extract (30â€“65% boswellic acids, AKBA)","Con comida grasa","With a fatty meal","No establecido","ClÃ­nico",
 "Antiinflamatorios; sustratos CYP","Anti-inflammatories; CYP substrates",
 "Inhibe 5-LOX; Ãºtil en artrosis y EII. Buscar alto AKBA.",
 "Inhibits 5-LOX; useful in osteoarthritis and IBD. Seek high AKBA."),
("msm","MSM (metilsulfonilmetano)","Compuesto azufrado","Sulfur compound",
 "1â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a","3â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (artrosis, dolor)","MSM","MSM","Con comida","With food","No establecido (seguro)","ClÃ­nico (moderado)",
 "Anticoagulantes (teÃ³rico)","Anticoagulants (theoretical)",
 "Dolor articular y rango de movimiento; sinergia con glucosamina.",
 "Joint pain and range of motion; synergy with glucosamine."),
("lutein","LuteÃ­na + zeaxantina","Carotenoide","Carotenoid",
 "[DOSIS_CLINICA_REMOVIDA] luteÃ­na + [DOSIS_CLINICA_REMOVIDA] zeaxantina/dÃ­a","[DOSIS_CLINICA_REMOVIDA]/dÃ­a (DMAE)","Con comida grasa","With a fatty meal","Con comida grasa","With a fatty meal","No establecido","ClÃ­nico (AREDS2)",
 "Ninguna relevante","None relevant",
 "ProtecciÃ³n macular (AREDS2). Ratio 5:1 luteÃ­na:zeaxantina.",
 "Macular protection (AREDS2). 5:1 lutein:zeaxanthin ratio."),
("astaxanthin","Astaxantina","Carotenoide","Carotenoid",
 "4â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a","8â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (piel/recuperaciÃ³n)","De Haematococcus pluvialis","From Haematococcus pluvialis","Con comida grasa","With a fatty meal","No establecido","ClÃ­nico (limitado)",
 "Anticoagulantes (teÃ³rico); 5-alfa-reductasa","Anticoagulants (theoretical); 5-alpha-reductase",
 "Antioxidante potente; fotoprotecciÃ³n de piel. Liposoluble.",
 "Potent antioxidant; skin photoprotection. Fat-soluble."),
("pqq","PQQ","Cofactor redox","Redox cofactor",
 "10â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a","[DOSIS_CLINICA_REMOVIDA]/dÃ­a (mitocondrial/cogniciÃ³n)","Pirroloquinolina quinona","Pyrroloquinoline quinone","Con comida","With food","No establecido","PreclÃ­nico/clÃ­nico",
 "Ninguna relevante","None relevant",
 "BiogÃ©nesis mitocondrial; sinergia con CoQ10. Evidencia emergente.",
 "Mitochondrial biogenesis; synergy with CoQ10. Emerging evidence."),
("nmn","NMN","Precursor de NAD+","NAD+ precursor",
 "250â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a","500â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (longevidad, estudios)","Nicotinamida mononucleÃ³tido","Nicotinamide mononucleotide","MaÃ±ana, en ayunas","Morning, fasting","No establecido","PreclÃ­nico (clÃ­nico emergente)",
 "Ninguna relevante conocida","None known",
 "Sube NAD+; evidencia humana temprana. Estatus regulatorio variable.",
 "Raises NAD+; early human evidence. Regulatory status varies."),
("nr","Nicotinamida ribÃ³sido (NR)","Precursor de NAD+","NAD+ precursor",
 "250â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a","300â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a","Niagen","Niagen","MaÃ±ana","Morning","[DOSIS_CLINICA_REMOVIDA]/dÃ­a (evaluado seguro)","ClÃ­nico",
 "Ninguna relevante conocida","None known",
 "Sube NAD+ de forma robusta en humanos; buen perfil de seguridad.",
 "Robustly raises NAD+ in humans; good safety profile."),
("dmannose","D-manosa","AzÃºcar simple","Simple sugar",
 "[DOSIS_CLINICA_REMOVIDA]/dÃ­a (prevenciÃ³n ITU)","1.[DOSIS_CLINICA_REMOVIDA] 2â€“3Ã—/dÃ­a (ITU aguda)","D-manosa","D-mannose","Con agua abundante","With plenty of water","No establecido (bien tolerada)","ClÃ­nico (moderado)",
 "AntidiabÃ©ticos (mÃ­nimo impacto glucÃ©mico)","Antidiabetics (minimal glycemic impact)",
 "Previene ITU por E. coli (impide adhesiÃ³n). No sustituye antibiÃ³tico en ITU grave.",
 "Prevents E. coli UTI (blocks adhesion). Not a substitute for antibiotics in severe UTI."),
("cranberry","ArÃ¡ndano rojo","Fitoterapia (fruta)","Phytotherapy (fruit)",
 "[DOSIS_CLINICA_REMOVIDA] PAC/dÃ­a","36â€“[DOSIS_CLINICA_REMOVIDA] proantocianidinas (PAC)/dÃ­a","Extracto estandarizado en PAC","PAC-standardized extract","Con comida","With food","No establecido","ClÃ­nico (moderado)",
 "Warfarina (posible aumento de INR)","Warfarin (possible INR increase)",
 "PrevenciÃ³n de ITU recurrente. Estandarizar por PAC, no por 'mg de fruta'.",
 "Recurrent UTI prevention. Standardize by PAC, not 'mg of fruit'."),
("elderberry","SaÃºco (elderberry)","Fitoterapia (fruta)","Phytotherapy (fruit)",
 "300â€“[DOSIS_CLINICA_REMOVIDA] extracto/dÃ­a","3.8â€“15 mL jarabe 2â€“4Ã—/dÃ­a (resfriado)","Extracto de Sambucus nigra","Sambucus nigra extract","A los primeros sÃ­ntomas","At first symptoms","No establecido","ClÃ­nico (limitado)",
 "Inmunosupresores (teÃ³rico)","Immunosuppressants (theoretical)",
 "Puede acortar sÃ­ntomas de gripe/resfriado. Solo fruta cocida (cruda es tÃ³xica).",
 "May shorten cold/flu symptoms. Cooked fruit only (raw is toxic)."),
("echinacea","EquinÃ¡cea","Inmunomodulador (hierba)","Immunomodulator (herb)",
 "300â€“[DOSIS_CLINICA_REMOVIDA] 3Ã—/dÃ­a","Al inicio del resfriado, corto plazo","Extracto de E. purpurea","E. purpurea extract","A los primeros sÃ­ntomas","At first symptoms","Uso â‰¤10 dÃ­as","ClÃ­nico (mixto)",
 "Inmunosupresores; sustratos CYP1A2/3A4","Immunosuppressants; CYP1A2/3A4 substrates",
 "Evidencia inconsistente; posible reducciÃ³n leve de duraciÃ³n. No en autoinmunidad.",
 "Inconsistent evidence; possible mild duration reduction. Not in autoimmunity."),
("valerian","Valeriana","Sedante (hierba)","Sedative (herb)",
 "300â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a","400â€“[DOSIS_CLINICA_REMOVIDA] 30â€“60 min antes de dormir","Extracto de raÃ­z","Root extract","Antes de dormir","Before bed","No establecido","ClÃ­nico (mixto)",
 "Sedantes, alcohol, benzodiacepinas (aditivo)","Sedatives, alcohol, benzodiazepines (additive)",
 "Insomnio de inicio; efecto puede tardar 2 semanas. Somnolencia matutina posible.",
 "Sleep-onset insomnia; effect may take 2 weeks. Possible morning grogginess."),
("lemon_balm","Melisa (toronjil)","AnsiolÃ­tico (hierba)","Anxiolytic (herb)",
 "300â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a","[DOSIS_CLINICA_REMOVIDA] (estrÃ©s agudo) / [DOSIS_CLINICA_REMOVIDA] dividido","Extracto de Melissa officinalis","Melissa officinalis extract","SegÃºn necesidad; noche para sueÃ±o","As needed; evening for sleep","No establecido","ClÃ­nico (limitado)",
 "Sedantes; hormona tiroidea (teÃ³rico)","Sedatives; thyroid hormone (theoretical)",
 "Calma y sueÃ±o; sinergia con valeriana. Buen perfil de seguridad.",
 "Calm and sleep; synergy with valerian. Good safety profile."),
("ps","Fosfatidilserina","FosfolÃ­pido","Phospholipid",
 "[DOSIS_CLINICA_REMOVIDA] 3Ã—/dÃ­a ([DOSIS_CLINICA_REMOVIDA]/dÃ­a)","[DOSIS_CLINICA_REMOVIDA]/dÃ­a (cogniciÃ³n/cortisol)","PS de girasol","Sunflower-derived PS","Con comida","With food","No establecido","ClÃ­nico (moderado)",
 "Anticoagulantes; anticolinesterÃ¡sicos","Anticoagulants; cholinesterase inhibitors",
 "CogniciÃ³n en mayores y amortigua cortisol por ejercicio. Preferir de girasol.",
 "Cognition in elderly and blunts exercise cortisol. Prefer sunflower source."),
("fenugreek","Fenogreco","Fitoterapia (hierba)","Phytotherapy (herb)",
 "500â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a","5â€“[DOSIS_CLINICA_REMOVIDA] semilla/dÃ­a (glucemia, lactancia)","Extracto o semilla","Extract or seed","Con comidas","With meals","No establecido","ClÃ­nico (moderado)",
 "AntidiabÃ©ticos (aditivo); anticoagulantes","Antidiabetics (additive); anticoagulants",
 "Baja glucosa posprandial; galactogogo. Puede dar olor a jarabe de arce.",
 "Lowers postprandial glucose; galactagogue. May cause maple-syrup odor."),
("maca","Maca","AdaptÃ³geno (raÃ­z)","Adaptogen (root)",
 "1.5â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a","[DOSIS_CLINICA_REMOVIDA]/dÃ­a (libido, energÃ­a)","Polvo de raÃ­z gelatinizado","Gelatinized root powder","Con comida","With food","No establecido","ClÃ­nico (limitado)",
 "Hormonal (teÃ³rico)","Hormonal (theoretical)",
 "Libido y energÃ­a; no altera hormonas directamente. Gelatinizada mejor tolerada.",
 "Libido and energy; doesn't directly alter hormones. Gelatinized better tolerated."),
("nitrate","Remolacha (nitrato)","Nitrato dietÃ©tico","Dietary nitrate",
 "300â€“[DOSIS_CLINICA_REMOVIDA] nitrato/dÃ­a","6.4â€“12.8 mmol nitrato (rendimiento)","Zumo de remolacha / concentrado","Beetroot juice / concentrate","2â€“3 h antes de ejercicio","2â€“3 h before exercise","No establecido","ClÃ­nico (fuerte)",
 "PDE5, antihipertensivos; evita enjuague bucal antibacteriano","PDE5, antihypertensives; avoid antibacterial mouthwash",
 "Sube Ã³xido nÃ­trico â†’ resistencia y presiÃ³n. No usar colutorio (mata bacterias orales).",
 "Raises nitric oxide â†’ endurance and BP. Skip mouthwash (kills oral bacteria)."),
("bromelain","Bromelina","Enzima proteolÃ­tica","Proteolytic enzyme",
 "[DOSIS_CLINICA_REMOVIDA]/dÃ­a","500â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (inflamaciÃ³n/edema)","De tallo de piÃ±a (GDU/MCU)","From pineapple stem (GDU/MCU)","En ayunas (antiinflamatorio)","Fasting (anti-inflammatory)","No establecido","ClÃ­nico (moderado)",
 "Anticoagulantes; antibiÃ³ticos (aumenta absorciÃ³n)","Anticoagulants; antibiotics (increases absorption)",
 "Antiinflamatorio/antiedema (postquirÃºrgico). En ayunas para efecto sistÃ©mico.",
 "Anti-inflammatory/anti-edema (post-surgery). Fasting for systemic effect."),
("saffron","AzafrÃ¡n","Fitoterapia (especia)","Phytotherapy (spice)",
 "[DOSIS_CLINICA_REMOVIDA]/dÃ­a","[DOSIS_CLINICA_REMOVIDA]/dÃ­a (Ã¡nimo, dividido)","Extracto estandarizado (safranal/crocina)","Standardized extract (safranal/crocin)","Con comida, dividido","With food, divided","â‰¤1.[DOSIS_CLINICA_REMOVIDA]/dÃ­a (dosis altas tÃ³xicas)","ClÃ­nico (moderado)",
 "Antidepresivos (aditivo); anticoagulantes","Antidepressants (additive); anticoagulants",
 "[DOSIS_CLINICA_REMOVIDA]/dÃ­a comparable a ISRS leve en depresiÃ³n leve-moderada. No exceder dosis.",
 "[DOSIS_CLINICA_REMOVIDA] comparable to mild SSRI in mild-moderate depression. Don't exceed dose."),
("vitk1","Vitamina K1 (filoquinona)","Vitamina liposoluble","Fat-soluble vitamin",
 "90â€“120 Âµg/dÃ­a","1â€“[DOSIS_CLINICA_REMOVIDA] (revertir sobre-anticoagulaciÃ³n, mÃ©dico)","Filoquinona","Phylloquinone","Con comida grasa","With a fatty meal","No establecido","ClÃ­nico",
 "Antagoniza warfarina (mantener ingesta CONSTANTE)","Antagonizes warfarin (keep intake CONSTANT)",
 "En warfarina no suspender de golpe: mantener aporte estable de vitamina K.",
 "On warfarin don't stop abruptly: keep vitamin K intake stable."),
("lysine","L-lisina","AminoÃ¡cido esencial","Essential amino acid",
 "[DOSIS_CLINICA_REMOVIDA]/dÃ­a","1â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (herpes labial)","L-lisina","L-lysine","En ayunas","Fasting","No establecido","ClÃ­nico (moderado)",
 "Ninguna relevante","None relevant",
 "Reduce recurrencia de herpes simple. Compite con arginina.",
 "Reduces herpes simplex recurrence. Competes with arginine."),
("glutamine","L-glutamina","AminoÃ¡cido","Amino acid",
 "[DOSIS_CLINICA_REMOVIDA]/dÃ­a","10â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (intestino, catabolismo)","L-glutamina","L-glutamine","Repartido, en ayunas","Split, fasting","No establecido","ClÃ­nico (mixto)",
 "Ninguna relevante","None relevant",
 "Integridad intestinal en estrÃ©s/quemados; evidencia deportiva dÃ©bil.",
 "Gut integrity in stress/burns; weak sports evidence."),
("hmb","HMB","Metabolito de leucina","Leucine metabolite",
 "[DOSIS_CLINICA_REMOVIDA]/dÃ­a","[DOSIS_CLINICA_REMOVIDA]/dÃ­a (anti-catabÃ³lico)","Beta-hidroxi-beta-metilbutirato","Beta-hydroxy-beta-methylbutyrate","Repartido con comidas","Split with meals","No establecido","ClÃ­nico",
 "Ninguna relevante","None relevant",
 "Reduce catabolismo muscular (mayores, dÃ©ficit calÃ³rico). Efecto modesto en entrenados.",
 "Reduces muscle catabolism (elderly, caloric deficit). Modest effect in trained."),
("bcaa","BCAA / EAA","AminoÃ¡cidos ramificados/esenciales","Branched/essential amino acids",
 "5â€“[DOSIS_CLINICA_REMOVIDA] BCAA","10â€“[DOSIS_CLINICA_REMOVIDA] EAA (mejor que BCAA)","EAA completos preferidos","Complete EAAs preferred","Alrededor del ejercicio","Around exercise","No establecido","ClÃ­nico",
 "Ninguna relevante","None relevant",
 "EAA > BCAA para sÃ­ntesis proteica. Innecesario si proteÃ­na dietÃ©tica es suficiente.",
 "EAA > BCAA for protein synthesis. Unnecessary if dietary protein is sufficient."),
("caffeine","CafeÃ­na","Estimulante","Stimulant",
 "40â€“[DOSIS_CLINICA_REMOVIDA]","3â€“[DOSIS_CLINICA_REMOVIDA]/kg (rendimiento)","Anhidra / natural","Anhydrous / natural","30â€“60 min pre-ejercicio; evitar 8 h antes de dormir","30â€“60 min pre-exercise; avoid 8 h before bed","[DOSIS_CLINICA_REMOVIDA]/dÃ­a (adultos)","ClÃ­nico (fuerte)",
 "Estimulantes; teofilina; ISRS; litio","Stimulants; theophylline; SSRIs; lithium",
 "ErgogÃ©nico robusto. Cortar 8 h antes de dormir para no daÃ±ar el sueÃ±o.",
 "Robust ergogenic. Cut 8 h before bed to protect sleep."),
("mucuna","Mucuna pruriens","Fitoterapia (L-DOPA)","Phytotherapy (L-DOPA)",
 "5% L-DOPA: ~200â€“[DOSIS_CLINICA_REMOVIDA] L-DOPA/dÃ­a","SegÃºn objetivo (Parkinson: con mÃ©dico)","Extracto estandarizado en L-DOPA","L-DOPA-standardized extract","En ayunas","Fasting","No establecido","ClÃ­nico (limitado)",
 "Levodopa, IMAO, antipsicÃ³ticos","Levodopa, MAOIs, antipsychotics",
 "Fuente natural de L-DOPA (dopamina). Cuidado con fÃ¡rmacos dopaminÃ©rgicos.",
 "Natural L-DOPA source (dopamine). Caution with dopaminergic drugs."),
("tulsi","Tulsi (albahaca sagrada)","AdaptÃ³geno (hierba)","Adaptogen (herb)",
 "300â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a","600â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (estrÃ©s/glucemia)","Extracto de Ocimum sanctum","Ocimum sanctum extract","Con comida","With food","No establecido","ClÃ­nico (limitado)",
 "AntidiabÃ©ticos; anticoagulantes","Antidiabetics; anticoagulants",
 "Reduce estrÃ©s y glucosa levemente. Buen perfil de seguridad.",
 "Reduces stress and glucose mildly. Good safety profile."),
("schisandra","Schisandra","AdaptÃ³geno (baya)","Adaptogen (berry)",
 "500â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a","1â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (hÃ­gado/estrÃ©s)","Extracto estandarizado (esquisandrinas)","Standardized extract (schisandrins)","Con comida","With food","No establecido","ClÃ­nico (limitado)",
 "Sustratos CYP3A4 (induce/inhibe segÃºn dosis)","CYP3A4 substrates (induces/inhibits by dose)",
 "Hepatoprotector y anti-estrÃ©s. Puede alterar metabolismo de fÃ¡rmacos.",
 "Hepatoprotector and anti-stress. May alter drug metabolism."),
("eleuthero","Eleuterococo (ginseng siberiano)","AdaptÃ³geno (hierba)","Adaptogen (herb)",
 "300â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a","2â€“[DOSIS_CLINICA_REMOVIDA] raÃ­z/dÃ­a (fatiga)","Extracto de Eleutherococcus","Eleutherococcus extract","MaÃ±ana","Morning","No establecido; ciclar","ClÃ­nico (mixto)",
 "Digoxina (falsea niveles); anticoagulantes; antidiabÃ©ticos","Digoxin (falsifies levels); anticoagulants; antidiabetics",
 "Anti-fatiga/resistencia. Evitar en hipertensiÃ³n no controlada.",
 "Anti-fatigue/endurance. Avoid in uncontrolled hypertension."),
("astragalus","AstrÃ¡galo","Inmunomodulador (hierba)","Immunomodulator (herb)",
 "[DOSIS_CLINICA_REMOVIDA] 2â€“3Ã—/dÃ­a","2â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (inmune)","Extracto de Astragalus membranaceus","Astragalus membranaceus extract","Con comida","With food","No establecido","ClÃ­nico (limitado)",
 "Inmunosupresores; anticoagulantes; litio","Immunosuppressants; anticoagulants; lithium",
 "InmunotÃ³nico; no usar en autoinmunidad ni trasplantados.",
 "Immune tonic; avoid in autoimmunity and transplant patients."),
("andrographis","Andrographis","Inmunomodulador (hierba)","Immunomodulator (herb)",
 "[DOSIS_CLINICA_REMOVIDA] 3Ã—/dÃ­a","60â€“[DOSIS_CLINICA_REMOVIDA] andrografÃ³lido/dÃ­a (resfriado)","Extracto (andrografÃ³lidos)","Extract (andrographolides)","A los primeros sÃ­ntomas","At first symptoms","Uso corto plazo","ClÃ­nico (moderado)",
 "Anticoagulantes; antihipertensivos; inmunosupresores","Anticoagulants; antihypertensives; immunosuppressants",
 "Reduce sÃ­ntomas de infecciÃ³n respiratoria alta. No en embarazo.",
 "Reduces upper respiratory infection symptoms. Not in pregnancy."),
("dim","DIM (diindolilmetano)","Metabolito de crucÃ­feras","Cruciferous metabolite",
 "[DOSIS_CLINICA_REMOVIDA]/dÃ­a","100â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (equilibrio estrogÃ©nico)","Diindolilmetano","Diindolylmethane","Con comida grasa","With a fatty meal","No establecido","PreclÃ­nico/clÃ­nico",
 "Sustratos CYP; hormonal","CYP substrates; hormonal",
 "Modula metabolismo de estrÃ³genos. Derivado de I3C del brÃ³coli.",
 "Modulates estrogen metabolism. Derived from broccoli I3C."),
("glutathione","GlutatiÃ³n","Antioxidante","Antioxidant",
 "250â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a","500â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (liposomal/acetilado)","Liposomal o S-acetil-glutatiÃ³n","Liposomal or S-acetyl-glutathione","En ayunas","Fasting","No establecido","ClÃ­nico (mixto)",
 "Ninguna relevante","None relevant",
 "Baja absorciÃ³n oral â†’ liposomal/acetilado o precursor NAC. Antioxidante maestro.",
 "Poor oral absorption â†’ liposomal/acetylated or NAC precursor. Master antioxidant."),
("tudca","TUDCA","Ãcido biliar","Bile acid",
 "250â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a","1000â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (colestasis, mÃ©dico)","Ãcido tauroursodesoxicÃ³lico","Tauroursodeoxycholic acid","Con comida","With food","No establecido","ClÃ­nico (limitado)",
 "Secuestrantes de Ã¡cidos biliares","Bile acid sequestrants",
 "Hepatoprotector y del retÃ­culo endoplÃ¡smico. Uso clÃ­nico en colestasis.",
 "Hepatoprotector and ER-stress protectant. Clinical use in cholestasis."),
("artichoke","Alcachofa","Fitoterapia (hierba)","Phytotherapy (herb)",
 "300â€“[DOSIS_CLINICA_REMOVIDA] 3Ã—/dÃ­a","[DOSIS_CLINICA_REMOVIDA]/dÃ­a (dispepsia/lÃ­pidos)","Extracto de hoja (cinarina)","Leaf extract (cynarin)","Antes de comidas","Before meals","No establecido","ClÃ­nico (moderado)",
 "ObstrucciÃ³n biliar (contraindicado)","Bile duct obstruction (contraindicated)",
 "Digestivo y baja colesterol levemente. Evitar en cÃ¡lculos biliares.",
 "Digestive and mildly lowers cholesterol. Avoid in gallstones."),
("red_yeast_rice","Levadura roja de arroz","Fitoterapia (estatina natural)","Phytotherapy (natural statin)",
 "1200â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a","[DOSIS_CLINICA_REMOVIDA]/dÃ­a (~[DOSIS_CLINICA_REMOVIDA] monacolina K)","Estandarizado en monacolina K","Standardized in monacolin K","Noche, con comida","Evening, with food","â‰¤[DOSIS_CLINICA_REMOVIDA] monacolina K/dÃ­a (EFSA)","ClÃ­nico",
 "Estatinas (NO combinar); fibratos; sustratos CYP3A4; toronja","Statins (do NOT combine); fibrates; CYP3A4 substrates; grapefruit",
 "Es una estatina natural (lovastatina). AÃ±adir CoQ10; vigilar hÃ­gado/CK.",
 "It IS a natural statin (lovastatin). Add CoQ10; monitor liver/CK."),
("plant_sterols","Fitoesteroles","Esterol vegetal","Plant sterol",
 "[DOSIS_CLINICA_REMOVIDA]/dÃ­a","2â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (LDL)","Esteroles/estanoles","Sterols/stanols","Con las comidas grasas","With fatty meals","â‰¤[DOSIS_CLINICA_REMOVIDA]/dÃ­a","ClÃ­nico (fuerte)",
 "Ezetimiba (aditivo); reduce absorciÃ³n de carotenoides","Ezetimibe (additive); reduces carotenoid absorption",
 "Bajan LDL 8â€“10%. Repartir con comidas. Compensar carotenoides.",
 "Lower LDL 8â€“10%. Split with meals. Offset carotenoids."),
("bergamot","Bergamota (Citrus bergamia)","Fitoterapia (polifenol)","Phytotherapy (polyphenol)",
 "[DOSIS_CLINICA_REMOVIDA]/dÃ­a","500â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (lÃ­pidos)","Extracto polifenÃ³lico estandarizado","Standardized polyphenolic extract","Antes de comidas","Before meals","No establecido","ClÃ­nico (moderado)",
 "Estatinas (aditivo); sustratos CYP","Statins (additive); CYP substrates",
 "Baja LDL y triglicÃ©ridos; alternativa/complemento a estatina.",
 "Lowers LDL and triglycerides; statin alternative/complement."),
("chondroitin","Condroitina","Glicosaminoglicano","Glycosaminoglycan",
 "800â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a","[DOSIS_CLINICA_REMOVIDA]/dÃ­a (artrosis, con glucosamina)","Sulfato de condroitina","Chondroitin sulfate","Con comida","With food","No establecido","ClÃ­nico (mixto)",
 "Warfarina (posible aumento INR)","Warfarin (possible INR increase)",
 "Sinergia con glucosamina; efecto lento (semanas).",
 "Synergy with glucosamine; slow onset (weeks)."),
("hyaluronic","Ãcido hialurÃ³nico","Glicosaminoglicano","Glycosaminoglycan",
 "120â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a","[DOSIS_CLINICA_REMOVIDA]/dÃ­a (piel/articulaciÃ³n)","Oral (bajo peso molecular)","Oral (low molecular weight)","Con comida","With food","No establecido","ClÃ­nico (moderado)",
 "Ninguna relevante","None relevant",
 "HidrataciÃ³n de piel y confort articular. Bajo peso molecular se absorbe mejor.",
 "Skin hydration and joint comfort. Low molecular weight absorbs better."),
("glucomannan","Glucomanano","Fibra soluble","Soluble fiber",
 "[DOSIS_CLINICA_REMOVIDA] 3Ã—/dÃ­a antes de comidas","3â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (saciedad/LDL/glucosa)","Konjac","Konjac","15â€“30 min antes con 1â€“2 vasos de agua","15â€“30 min before with 1â€“2 glasses of water","No aplica","ClÃ­nico",
 "Separar de fÃ¡rmacos 1â€“2 h; riesgo de obstrucciÃ³n si poco agua","Separate from drugs 1â€“2 h; obstruction risk with little water",
 "Saciedad y LDL. SIEMPRE con agua abundante (riesgo de atragantamiento).",
 "Satiety and LDL. ALWAYS with plenty of water (choking risk)."),
("capsaicin","Capsaicina","FitoquÃ­mico (pimiento)","Phytochemical (chili)",
 "2â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (oral)","TÃ³pico 0.025â€“0.075% (dolor)","CÃ¡psula oral o crema tÃ³pica","Oral capsule or topical cream","Con comida (oral)","With food (oral)","No establecido","ClÃ­nico (tÃ³pico)",
 "Antihipertensivos; irritaciÃ³n GI","Antihypertensives; GI irritation",
 "TÃ³pico para dolor neuropÃ¡tico/artrÃ³sico. TermogÃ©nico leve oral.",
 "Topical for neuropathic/osteoarthritic pain. Mild thermogenic orally."),
("cla","CLA (Ã¡cido linoleico conjugado)","Ãcido graso","Fatty acid",
 "3â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a","3.4â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (composiciÃ³n corporal)","IsÃ³meros c9,t11 / t10,c12","c9,t11 / t10,c12 isomers","Con comida","With food","No establecido","ClÃ­nico (mixto)",
 "Puede empeorar resistencia a insulina a dosis altas","May worsen insulin resistance at high doses",
 "Efecto modesto en grasa corporal; evidencia inconsistente.",
 "Modest effect on body fat; inconsistent evidence."),
("mct","Aceite MCT","Ãcido graso","Fatty acid",
 "1 cucharada ([DOSIS_CLINICA_REMOVIDA])/dÃ­a","15â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (cetosis/energÃ­a)","C8/C10 (caprÃ­lico/cÃ¡prico)","C8/C10 (caprylic/capric)","Empezar bajo (tolerancia GI)","Start low (GI tolerance)","No establecido","ClÃ­nico",
 "Ninguna relevante","None relevant",
 "EnergÃ­a rÃ¡pida y cetonas. Subir gradual para evitar diarrea. C8 mÃ¡s cetogÃ©nico.",
 "Fast energy and ketones. Titrate up to avoid diarrhea. C8 most ketogenic."),
("gotu_kola","Centella asiÃ¡tica (gotu kola)","Fitoterapia (hierba)","Phytotherapy (herb)",
 "60â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (triterpenos)","120â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (venoso/piel)","Extracto estandarizado","Standardized extract","Con comida","With food","No establecido","ClÃ­nico (moderado)",
 "HepatotÃ³xicos; sedantes; antidiabÃ©ticos","Hepatotoxics; sedatives; antidiabetics",
 "Insuficiencia venosa y cicatrizaciÃ³n. Cursos de â‰¤6 semanas.",
 "Venous insufficiency and wound healing. Courses â‰¤6 weeks."),
("sulforaphane","Sulforafano","Isotiocianato","Isothiocyanate",
 "10â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a","30â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (Nrf2/detox)","Brotes de brÃ³coli / mirosinasa activa","Broccoli sprouts / active myrosinase","Con comida","With food","No establecido","ClÃ­nico (emergente)",
 "Ninguna relevante","None relevant",
 "Activa Nrf2 (antioxidante/detox). Necesita mirosinasa para convertirse.",
 "Activates Nrf2 (antioxidant/detox). Needs myrosinase to convert."),
("policosanol","Policosanol","Alcohol graso (caÃ±a)","Fatty alcohol (sugarcane)",
 "5â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a","10â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (lÃ­pidos)","De cera de caÃ±a de azÃºcar","From sugarcane wax","Noche","Evening","No establecido","ClÃ­nico (controvertido)",
 "Anticoagulantes (efecto antiplaquetario)","Anticoagulants (antiplatelet effect)",
 "Evidencia sobre LDL mixta (positiva sobre todo en estudios cubanos).",
 "LDL evidence mixed (positive mainly in Cuban studies)."),
("apigenin","Apigenina","Flavonoide","Flavonoid",
 "[DOSIS_CLINICA_REMOVIDA]/dÃ­a","50â€“[DOSIS_CLINICA_REMOVIDA]/dÃ­a (sueÃ±o/ansiedad)","De manzanilla/perejil","From chamomile/parsley","Noche","Evening","No establecido","PreclÃ­nico",
 "Sedantes; sustratos CYP","Sedatives; CYP substrates",
 "Ligando de receptores GABA/benzodiacepina (calma). Evidencia preclÃ­nica.",
 "GABA/benzodiazepine receptor ligand (calming). Preclinical evidence."),
]

FIELDS = ["slug","name","category_es","category_en","standard_dose","therapeutic_dose",
          "form_es","form_en","timing_es","timing_en","upper_limit","evidence",
          "interactions_es","interactions_en","notes_es","notes_en"]

# â”€â”€ Capa de SEGURIDAD / HORARIO (reducir efectos adversos) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
# slug -> {stop_days_before_surgery, bleeding_risk, oncology_caution_es/en, separate_from}
SAFETY = {
    "omega3": {"stop_days_before_surgery": 7, "bleeding_risk": True},
    "vite":   {"stop_days_before_surgery": 7, "bleeding_risk": True},
    "vitk1":  {"note_es": "Antagoniza warfarina: mantener ingesta constante.", "note_en": "Antagonizes warfarin: keep intake constant."},
    "k2":     {"note_es": "Contraindicado con warfarina.", "note_en": "Contraindicated with warfarin."},
    "ginkgo": {"stop_days_before_surgery": 10, "bleeding_risk": True},
    "garlic": {"stop_days_before_surgery": 10, "bleeding_risk": True},
    "ginseng":{"stop_days_before_surgery": 7, "bleeding_risk": True},
    "curcumin":{"stop_days_before_surgery": 7, "bleeding_risk": True},
    "quercetin":{"bleeding_risk": True},
    "resveratrol":{"stop_days_before_surgery": 7, "bleeding_risk": True},
    "bromelain":{"stop_days_before_surgery": 7, "bleeding_risk": True},
    "policosanol":{"bleeding_risk": True},
    "vitc":   {"oncology_caution_es": "Dosis altas antioxidantes pueden interferir con radio/quimio pro-oxidante â€” separar del ciclo.",
               "oncology_caution_en": "High antioxidant doses may blunt pro-oxidant chemo/radiotherapy â€” separate from cycle."},
    "vite2":  {},
    "astaxanthin":{"oncology_caution_es": "Antioxidante potente: consultar oncÃ³logo durante radio/quimio.",
                   "oncology_caution_en": "Potent antioxidant: consult oncologist during chemo/radiotherapy."},
    "nac":    {"oncology_caution_es": "Antioxidante: puede interferir con quimio pro-oxidante â€” supervisiÃ³n oncolÃ³gica.",
               "oncology_caution_en": "Antioxidant: may interfere with pro-oxidant chemo â€” oncology supervision."},
    "glutathione":{"oncology_caution_es": "Antioxidante: separar de ciclos de quimio pro-oxidante.",
                   "oncology_caution_en": "Antioxidant: separate from pro-oxidant chemo cycles."},
    "hypericum":{"oncology_caution_es": "Inductor potente de CYP3A4: BAJA niveles de muchos citostÃ¡ticos.",
                 "oncology_caution_en": "Potent CYP3A4 inducer: LOWERS many chemo drug levels."},
    "iron":   {"separate_from_es": "Separar 4 h de levotiroxina, calcio, cafÃ©/tÃ© y quinolonas.",
               "separate_from_en": "Separate 4 h from levothyroxine, calcium, coffee/tea and quinolones."},
    "calcium":{"separate_from_es": "Separar 4 h de levotiroxina, hierro y quinolonas/tetraciclinas.",
               "separate_from_en": "Separate 4 h from levothyroxine, iron and quinolones/tetracyclines."},
    "magnesium":{"separate_from_es": "Separar 2â€“4 h de antibiÃ³ticos (quinolonas/tetraciclinas) y bifosfonatos.",
                 "separate_from_en": "Separate 2â€“4 h from antibiotics (quinolones/tetracyclines) and bisphosphonates."},
    "zinc":   {"separate_from_es": "Separar 2 h de quinolonas y del hierro.",
               "separate_from_en": "Separate 2 h from quinolones and iron."},
    "psyllium":{"separate_from_es": "Separar 2â€“4 h de cualquier fÃ¡rmaco (reduce absorciÃ³n).",
                "separate_from_en": "Separate 2â€“4 h from any drug (reduces absorption)."},
    "glucomannan":{"separate_from_es": "Separar 1â€“2 h de fÃ¡rmacos.",
                   "separate_from_en": "Separate 1â€“2 h from drugs."},
    "red_yeast_rice":{"oncology_caution_es": "Es lovastatina: NO combinar con estatinas.",
                      "oncology_caution_en": "It is lovastatin: do NOT combine with statins."},
    "biotin": {"note_es": "Suspender 48â€“72 h antes de anÃ¡lisis de sangre (falsea resultados).",
               "note_en": "Stop 48â€“72 h before blood tests (skews results)."},
    "vita":   {"note_es": "Retinol teratÃ³geno: no exceder en embarazo.",
               "note_en": "Retinol is teratogenic: don't exceed in pregnancy."},
}

def main():
    data = []
    for row in R:
        d = dict(zip(FIELDS, row))
        d["name_es"] = d["name"]; d["name_en"] = d["name"]
        if d["slug"] in SAFETY:
            d["safety"] = SAFETY[d["slug"]]
        data.append(d)
    out = {"version": "1.0", "count": len(data),
           "sources": "EFSA, NIH-ODS, EMA/HMPC, Examine, Cochrane, MSK About Herbs",
           "disclaimer_es": "Dosis educativas basadas en literatura. No sustituye criterio clÃ­nico.",
           "disclaimer_en": "Educational doses based on literature. Not a substitute for clinical judgment.",
           "items": data}
    dst = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                       "local_db", "supplement_dosing.json")
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    with open(dst, "w", encoding="utf-8") as f:
        json.dump(out, f, ensure_ascii=False, indent=2)
    print(f"OK: {len(data)} suplementos/hierbas -> {dst}")

if __name__ == "__main__":
    main()

