"""
Genera local_db/supplement_dosing.json — base de DOSIS de suplementos y hierbas.
Dosis basadas en literatura clínica (EFSA/NIH-ODS/Examine/Cochrane/monografías EMA).
Bilingüe ES/EN. Ejecuta:  python scripts/build_dosing_db.py
"""
import json, os

# Campos por fila (tupla):
# slug, name, category_es, category_en, standard, therapeutic, form_es, form_en,
# timing_es, timing_en, upper_limit, evidence, interactions_es, interactions_en,
# notes_es, notes_en
R = [
("omega3","Omega-3 (EPA/DHA)","Ácido graso","Fatty acid",
 "250–500 mg EPA+DHA/día","2–4 g EPA+DHA/día (hipertrigliceridemia)",
 "Aceite de pescado (TG o éster etílico)","Fish oil (TG or ethyl ester)",
 "Con comida grasa","With a fatty meal","≤5 g/día (EFSA)","Clínico (meta-análisis)",
 "Anticoagulantes/antiplaquetarios a dosis altas","Anticoagulants/antiplatelets at high doses",
 "Reduce TG 20–30% con 2–4 g/día. Elegir ratio EPA:DHA según objetivo (EPA→TG/ánimo).",
 "Lowers TG 20–30% at 2–4 g/day. Pick EPA:DHA ratio by goal (EPA→TG/mood)."),
("vitd","Vitamina D3","Vitamina liposoluble","Fat-soluble vitamin",
 "800–2000 UI/día","4000–10000 UI/día (déficit, con control 25-OH-D)",
 "Colecalciferol (D3)","Cholecalciferol (D3)","Con comida grasa","With a fatty meal",
 "4000 UI/día (UL EFSA adultos)","Clínico",
 "Tiazidas (hipercalcemia); dosis altas con calcio","Thiazides (hypercalcemia); high dose with calcium",
 "Objetivo 25-OH-D 30–50 ng/mL. Cofactores: magnesio y K2.",
 "Target 25-OH-D 30–50 ng/mL. Cofactors: magnesium and K2."),
("magnesium","Magnesio","Mineral","Mineral",
 "200–400 mg/día (elemental)","300–500 mg/día (migraña, calambres, sueño)",
 "Glicinato/citrato/malato","Glycinate/citrate/malate","Noche (glicinato) o con comida","Evening (glycinate) or with food",
 "350 mg/día suplementario (UL, solo suplemento)","Clínico",
 "Antibióticos (quinolonas/tetraciclinas): separar 2–4 h","Antibiotics (quinolones/tetracyclines): separate 2–4 h",
 "Óxido tiene baja absorción; glicinato mejor tolerado. Citrato si estreñimiento.",
 "Oxide poorly absorbed; glycinate best tolerated. Citrate if constipation."),
("berberine","Berberina","Alcaloide vegetal","Plant alkaloid",
 "500 mg 2–3×/día","1500 mg/día repartido (glucosa/lípidos)",
 "Berberina HCl","Berberine HCl","Antes de comidas principales","Before main meals","No establecido (usar ≤3 meses y reevaluar)","Clínico",
 "Inhibe CYP3A4 (ciclosporina, estatinas); metformina (sinergia glucémica)","Inhibits CYP3A4 (cyclosporine, statins); metformin (glycemic synergy)",
 "Baja HbA1c ~0.7–1%. Efecto tipo metformina. GI si dosis única alta → repartir.",
 "Lowers HbA1c ~0.7–1%. Metformin-like. GI upset if single high dose → split."),
("curcumin","Curcumina","Polifenol","Polyphenol",
 "500–1000 mg/día (extracto)","1000–2000 mg/día (con piperina o formulación)",
 "Extracto 95% curcuminoides + piperina/fitosomas","95% curcuminoid extract + piperine/phytosome",
 "Con comida grasa","With a fatty meal","No establecido","Clínico/preclínico",
 "Anticoagulantes; sustratos CYP; suspender antes de cirugía","Anticoagulants; CYP substrates; stop before surgery",
 "Baja biodisponibilidad → usar piperina, fitosoma o nanoemulsión.",
 "Low bioavailability → use piperine, phytosome or nanoemulsion."),
("coq10","Coenzima Q10","Ubiquinona","Ubiquinone",
 "100–200 mg/día","300 mg/día (miopatía por estatinas, IC)",
 "Ubiquinol (reducido) o ubiquinona","Ubiquinol (reduced) or ubiquinone","Con comida grasa","With a fatty meal","No establecido","Clínico (mixto)",
 "Warfarina (puede reducir INR)","Warfarin (may reduce INR)",
 "Ubiquinol mejor absorbido >50 años. Útil en mialgia por estatinas.",
 "Ubiquinol better absorbed >50 y. Useful for statin myalgia."),
("creatine","Creatina","Aminoácido derivado","Amino acid derivative",
 "3–5 g/día (mantenimiento)","20 g/día 5–7 d (carga, opcional)",
 "Monohidrato","Monohydrate","Cualquier hora; constante","Any time; consistent","No aplica (seguro a 3–5 g)","Clínico (fuerte)",
 "Ninguna clínicamente relevante","None clinically relevant",
 "Fuerza/masa y cognición. Monohidrato es el estándar de oro. Hidratación.",
 "Strength/mass and cognition. Monohydrate is gold standard. Hydrate."),
("melatonin","Melatonina","Neurohormona","Neurohormone",
 "0.5–3 mg","0.5–5 mg (jet lag, insomnio de inicio)",
 "Liberación inmediata o prolongada","Immediate or prolonged release","30–60 min antes de dormir","30–60 min before bed","No establecido; empezar bajo","Clínico",
 "Sedantes; anticoagulantes; inmunosupresores","Sedatives; anticoagulants; immunosuppressants",
 "Dosis baja suele bastar; más no es mejor. Cronobiótico (regula fase).",
 "Low dose usually enough; more isn't better. Chronobiotic (phase-shifts)."),
("zinc","Zinc","Mineral","Mineral",
 "8–11 mg/día","25–40 mg/día (corto plazo, resfriado)",
 "Citrato/picolinato/gluconato","Citrate/picolinate/gluconate","Con comida (evita náusea)","With food (avoids nausea)","40 mg/día (UL)","Clínico",
 "Antibióticos (quinolonas); cobre (deplece con uso crónico)","Antibiotics (quinolones); copper (depletes with chronic use)",
 ">40 mg/día crónico → añadir 1–2 mg cobre. Absorción compite con hierro.",
 ">40 mg/day chronic → add 1–2 mg copper. Absorption competes with iron."),
("vitc","Vitamina C","Vitamina hidrosoluble","Water-soluble vitamin",
 "75–90 mg/día (RDA)","500–1000 mg/día (antioxidante)",
 "Ácido ascórbico / liposomal","Ascorbic acid / liposomal","Repartida; con comida","Split; with food","2000 mg/día (UL)","Clínico",
 "Dosis altas: riesgo de oxalato (cálculos)","High dose: oxalate risk (stones)",
 "Mejora absorción de hierro no-hemo. Repartir mejora tolerancia.",
 "Improves non-heme iron absorption. Splitting improves tolerance."),
("b12","Vitamina B12","Vitamina hidrosoluble","Water-soluble vitamin",
 "2.4 µg/día (RDA)","500–1000 µg/día (déficit, veganos, malabsorción)",
 "Metilcobalamina / cianocobalamina","Methylcobalamin / cyanocobalamin","Cualquier hora","Any time","No establecido (segura)","Clínico",
 "Metformina e IBP reducen absorción","Metformin and PPIs reduce absorption",
 "Sublingual o IM si malabsorción. Verificar con ácido metilmalónico.",
 "Sublingual or IM if malabsorption. Confirm with methylmalonic acid."),
("folate","Folato (B9)","Vitamina hidrosoluble","Water-soluble vitamin",
 "400 µg DFE/día","400–800 µg/día (embarazo/déficit)",
 "Metilfolato (5-MTHF) o ácido fólico","Methylfolate (5-MTHF) or folic acid","Cualquier hora","Any time","1000 µg/día ácido fólico (UL)","Clínico",
 "Metotrexato, antiepilépticos","Methotrexate, antiepileptics",
 "En MTHFR C677T preferir metilfolato. No enmascarar déficit de B12.",
 "In MTHFR C677T prefer methylfolate. Don't mask B12 deficiency."),
("iron","Hierro","Mineral","Mineral",
 "8–18 mg/día (RDA)","40–65 mg elemental (déficit, días alternos)",
 "Bisglicinato / sulfato ferroso","Bisglycinate / ferrous sulfate","En ayunas + vit C; días alternos","Fasting + vit C; alternate days","45 mg/día (UL)","Clínico",
 "Separar de calcio, café, té, IBP, levotiroxina","Separate from calcium, coffee, tea, PPIs, levothyroxine",
 "Días alternos mejora absorción y tolerancia. Confirmar con ferritina.",
 "Alternate-day dosing improves absorption/tolerance. Confirm with ferritin."),
("calcium","Calcio","Mineral","Mineral",
 "1000–1200 mg/día (dieta+suplemento)","≤500 mg por toma (fraccionar)",
 "Citrato (mejor si IBP) / carbonato","Citrate (better with PPIs) / carbonate","Citrato cualquier hora; carbonato con comida","Citrate anytime; carbonate with food","2500 mg/día (UL)","Clínico",
 "Reduce absorción de hierro, zinc, levotiroxina, quinolonas","Reduces iron, zinc, levothyroxine, quinolone absorption",
 "Fraccionar ≤500 mg. Acompañar de vit D y K2.",
 "Split ≤500 mg. Pair with vit D and K2."),
("k2","Vitamina K2 (MK-7)","Vitamina liposoluble","Fat-soluble vitamin",
 "90–120 µg/día","180 µg/día (salud ósea/vascular)",
 "MK-7 (menaquinona-7)","MK-7 (menaquinone-7)","Con comida grasa","With a fatty meal","No establecido","Clínico/preclínico",
 "Contraindicado con warfarina (antagonismo)","Contraindicated with warfarin (antagonism)",
 "Dirige el calcio al hueso. Sinergia con D3.",
 "Directs calcium to bone. Synergy with D3."),
("ashwagandha","Ashwagandha","Adaptógeno (hierba)","Adaptogen (herb)",
 "300–600 mg/día (extracto KSM-66/Sensoril)","600 mg/día (estrés/cortisol)",
 "Extracto de raíz estandarizado","Standardized root extract","Con comida; noche si sueño","With food; evening for sleep","No establecido; ciclar","Clínico",
 "Sedantes, tiroides (puede subir T4), inmunosupresores","Sedatives, thyroid (may raise T4), immunosuppressants",
 "Reduce cortisol y ansiedad. Precaución en hipertiroidismo y embarazo.",
 "Lowers cortisol and anxiety. Caution in hyperthyroidism and pregnancy."),
("rhodiola","Rhodiola rosea","Adaptógeno (hierba)","Adaptogen (herb)",
 "200–400 mg/día (3% rosavinas/1% salidrósido)","400–600 mg/día (fatiga)",
 "Extracto de raíz","Root extract","Mañana, en ayunas","Morning, fasting","No establecido","Clínico (moderado)",
 "Estimulantes; antidepresivos (teórico)","Stimulants; antidepressants (theoretical)",
 "Anti-fatiga y rendimiento cognitivo bajo estrés. Puede activar → evitar noche.",
 "Anti-fatigue and cognition under stress. May be activating → avoid at night."),
("probiotics","Probióticos","Microorganismos","Microorganisms",
 "1–10 mil millones UFC/día","10–50 mil millones UFC/día (cepas específicas)",
 "Cápsula multicepa/monocepa","Multi/single-strain capsule","Con o antes de comida","With or before a meal","No aplica","Clínico (cepa-dependiente)",
 "Inmunosupresión severa (riesgo bacteriemia)","Severe immunosuppression (bacteremia risk)",
 "Efecto es CEPA-específico: elegir cepa según indicación, no 'genérico'.",
 "Effect is STRAIN-specific: choose strain by indication, not 'generic'."),
("psyllium","Psyllium (fibra)","Fibra soluble","Soluble fiber",
 "5 g 1–3×/día","10–20 g/día (colesterol/glucemia)",
 "Cáscara de Plantago ovata","Plantago ovata husk","Con agua abundante, antes de comidas","With plenty of water, before meals","No aplica","Clínico",
 "Separar de fármacos 2–4 h (reduce absorción)","Separate from drugs 2–4 h (reduces absorption)",
 "Baja LDL y glucosa posprandial. Subir dosis gradual (gases).",
 "Lowers LDL and postprandial glucose. Titrate up gradually (gas)."),
("nac","N-acetilcisteína (NAC)","Aminoácido modificado","Modified amino acid",
 "600 mg/día","1200–1800 mg/día (mucolítico, hepatoprotección)",
 "NAC","NAC","Con o sin comida","With or without food","No establecido","Clínico",
 "Nitroglicerina (hipotensión); anticoagulantes","Nitroglycerin (hypotension); anticoagulants",
 "Precursor de glutatión. Antioxidante; útil en hígado y respiratorio.",
 "Glutathione precursor. Antioxidant; useful for liver and respiratory."),
("ala","Ácido alfa-lipoico","Antioxidante","Antioxidant",
 "300–600 mg/día","600–1200 mg/día (neuropatía diabética)",
 "R-ALA o racémico","R-ALA or racemic","En ayunas, antes de comida","Fasting, before a meal","No establecido","Clínico",
 "Puede bajar glucosa (ajustar antidiabéticos); tiroides","May lower glucose (adjust antidiabetics); thyroid",
 "R-ALA más biodisponible. Mejora sensibilidad a insulina y neuropatía.",
 "R-ALA more bioavailable. Improves insulin sensitivity and neuropathy."),
("quercetin","Quercetina","Flavonoide","Flavonoid",
 "500 mg/día","500 mg 2×/día (alergia, rendimiento)",
 "Con bromelina/vit C para absorción","With bromelain/vit C for absorption","Con comida","With food","No establecido","Preclínico/clínico",
 "Inhibe CYP3A4/P-gp (ciclosporina, algunos fármacos)","Inhibits CYP3A4/P-gp (cyclosporine, some drugs)",
 "Antiinflamatorio/antihistamínico natural. Baja biodisponibilidad.",
 "Natural anti-inflammatory/antihistamine. Low bioavailability."),
("resveratrol","Resveratrol","Polifenol (estilbeno)","Polyphenol (stilbene)",
 "150–500 mg/día","1000 mg/día (estudios metabólicos)",
 "Trans-resveratrol","Trans-resveratrol","Con comida grasa","With a fatty meal","No establecido; GI a dosis altas","Preclínico (clínico mixto)",
 "Anticoagulantes; sustratos CYP","Anticoagulants; CYP substrates",
 "Activador de SIRT1 in vitro; evidencia humana modesta. Trans- es la forma activa.",
 "SIRT1 activator in vitro; modest human evidence. Trans- is the active form."),
("egcg","EGCG (té verde)","Catequina","Catechin",
 "300–400 mg EGCG/día","Hasta 800 mg/día (con precaución hepática)",
 "Extracto estandarizado de té verde","Standardized green tea extract","Con comida (reduce riesgo hepático)","With food (lowers liver risk)","≤800 mg EGCG/día (EFSA, extracto)","Clínico",
 "Hepatotóxico en ayunas a dosis altas; reduce hierro","Hepatotoxic fasting at high dose; reduces iron",
 "Tomar CON comida. Vigilar transaminasas si dosis alta prolongada.",
 "Take WITH food. Monitor transaminases if prolonged high dose."),
("milkthistle","Cardo mariano (silimarina)","Hepatoprotector (hierba)","Hepatoprotector (herb)",
 "200–400 mg silimarina/día","420–600 mg/día (hepatopatía)",
 "Extracto 70–80% silimarina","70–80% silymarin extract","Con comida","With food","No establecido","Clínico (moderado)",
 "Inhibe CYP2C9/3A4 (leve)","Inhibits CYP2C9/3A4 (mild)",
 "Hepatoprotector antioxidante. Evidencia mixta pero buen perfil de seguridad.",
 "Antioxidant hepatoprotector. Mixed evidence but good safety."),
("sawpalmetto","Saw palmetto","Fitoterapia (hierba)","Phytotherapy (herb)",
 "320 mg/día (extracto liposterólico)","320 mg/día (HPB)",
 "Extracto de Serenoa repens","Serenoa repens extract","Con comida","With food","No establecido","Clínico (mixto)",
 "Anticoagulantes; hormonal","Anticoagulants; hormonal",
 "Síntomas de HPB; evidencia inconsistente. Puede alterar PSA.",
 "BPH symptoms; inconsistent evidence. May alter PSA."),
("ginkgo","Ginkgo biloba","Nootrópico (hierba)","Nootropic (herb)",
 "120–240 mg/día (EGb 761)","240 mg/día (cognición/circulación)",
 "Extracto estandarizado 24/6","Standardized extract 24/6","Repartido, con comida","Split, with food","No establecido","Clínico (moderado)",
 "Alto riesgo con anticoagulantes/antiplaquetarios; suspender 7–10 d antes de cirugía","High risk with anticoagulants/antiplatelets; stop 7–10 d before surgery",
 "Antiagregante: ¡cuidado con warfarina! Sangrado documentado.",
 "Antiplatelet: caution with warfarin! Documented bleeding."),
("ginseng","Ginseng (Panax)","Adaptógeno (hierba)","Adaptogen (herb)",
 "200–400 mg/día (4–7% ginsenósidos)","400 mg/día (fatiga/glucemia)",
 "Extracto de raíz estandarizado","Standardized root extract","Mañana","Morning","No establecido; ciclar","Clínico (moderado)",
 "Warfarina (reduce INR); antidiabéticos; estimulantes","Warfarin (reduces INR); antidiabetics; stimulants",
 "Puede bajar glucosa. Activador → evitar noche. Ciclar uso.",
 "May lower glucose. Activating → avoid at night. Cycle use."),
("garlic","Ajo (alicina)","Fitoterapia (hierba)","Phytotherapy (herb)",
 "600–1200 mg/día (extracto)","≈3.6–5.4 mg alicina/día","Extracto añejado/comprimido con recubrimiento entérico","Aged extract/enteric-coated tablet","Con comida","With food","No establecido","Clínico",
 "Anticoagulantes/antiplaquetarios; suspender 7–10 d antes de cirugía; antirretrovirales","Anticoagulants/antiplatelets; stop 7–10 d before surgery; antiretrovirals",
 "Baja PA levemente y lípidos. Efecto antiplaquetario relevante en cirugía.",
 "Mild BP and lipid reduction. Antiplatelet effect relevant for surgery."),
("cinnamon","Canela (Ceylan)","Especia funcional","Functional spice",
 "1–2 g/día","≤6 g/día corto plazo (glucemia)","Ceylán (baja cumarina) preferido sobre Cassia","Ceylon (low coumarin) preferred over Cassia","Con comidas con carbohidratos","With carb-containing meals","Cassia: cumarina hepatotóxica → limitar","Clínico (modesto)",
 "Antidiabéticos (aditivo); hepatotóxicos (Cassia)","Antidiabetics (additive); hepatotoxics (Cassia)",
 "Usar Ceylán para evitar cumarina. Efecto glucémico modesto.",
 "Use Ceylon to avoid coumarin. Modest glycemic effect."),
("chromium","Cromo (picolinato)","Mineral traza","Trace mineral",
 "200 µg/día","200–1000 µg/día (resistencia a insulina)","Picolinato de cromo","Chromium picolinate","Con comida","With food","No establecido","Clínico (mixto)",
 "Antidiabéticos (aditivo); levotiroxina (separar)","Antidiabetics (additive); levothyroxine (separate)",
 "Puede mejorar sensibilidad a insulina; evidencia heterogénea.",
 "May improve insulin sensitivity; heterogeneous evidence."),
("inositol","Mio-inositol","Poliol","Polyol",
 "2 g 2×/día (4 g/día)","2–4 g/día (SOP, con D-chiro 40:1)","Mio-inositol (+ D-chiro-inositol 40:1)","Myo-inositol (+ D-chiro-inositol 40:1)","Repartido, con comida","Split, with food","No establecido (bien tolerado)","Clínico",
 "Antidiabéticos (aditivo)","Antidiabetics (additive)",
 "SOP: mejora ovulación y resistencia a insulina. Ratio 40:1 mio:D-chiro.",
 "PCOS: improves ovulation and insulin resistance. 40:1 myo:D-chiro ratio."),
("taurine","Taurina","Aminoácido","Amino acid",
 "500–2000 mg/día","3–6 g/día (rendimiento/cardiometabólico)","Taurina","Taurine","Cualquier hora","Any time","No establecido (segura)","Clínico (emergente)",
 "Litio (excreción)","Lithium (excretion)",
 "Cardio y metabólico; buen perfil de seguridad.",
 "Cardio and metabolic; good safety profile."),
("glycine","Glicina","Aminoácido","Amino acid",
 "3 g antes de dormir","3–5 g/día (sueño/metabólico)","Glicina","Glycine","Antes de dormir","Before bed","No establecido","Clínico (moderado)",
 "Clozapina (reduce eficacia)","Clozapine (reduces efficacy)",
 "Mejora calidad del sueño y sensibilidad a insulina.",
 "Improves sleep quality and insulin sensitivity."),
("ltheanine","L-teanina","Aminoácido","Amino acid",
 "100–200 mg","200–400 mg/día (ansiedad/foco)","L-teanina","L-theanine","Con o sin cafeína","With or without caffeine","No establecido (segura)","Clínico",
 "Antihipertensivos (aditivo leve)","Antihypertensives (mild additive)",
 "Calma sin sedación. Sinergia con cafeína para foco.",
 "Calm without sedation. Synergy with caffeine for focus."),
("5htp","5-HTP","Precursor de serotonina","Serotonin precursor",
 "50–100 mg","100–300 mg/día (ánimo/sueño)","5-hidroxitriptófano","5-hydroxytryptophan","Noche; con carbohidrato","Evening; with a carb","No establecido; empezar bajo","Clínico (limitado)",
 "ISRS/IMAO: riesgo de síndrome serotoninérgico","SSRIs/MAOIs: serotonin syndrome risk",
 "NO combinar con antidepresivos serotoninérgicos. Empezar bajo.",
 "Do NOT combine with serotonergic antidepressants. Start low."),
("same","SAMe","Donante de metilo","Methyl donor",
 "400 mg/día","800–1600 mg/día (depresión/artrosis)","S-adenosil-metionina entérica","Enteric S-adenosyl-methionine","En ayunas","Fasting","No establecido","Clínico (moderado)",
 "ISRS (síndrome serotoninérgico); bipolar (manía)","SSRIs (serotonin syndrome); bipolar (mania)",
 "Ánimo y articulaciones. Precaución en trastorno bipolar.",
 "Mood and joints. Caution in bipolar disorder."),
("glucosamine","Glucosamina","Aminosacárido","Amino sugar",
 "1500 mg/día","1500 mg/día (sulfato, artrosis)","Sulfato de glucosamina (preferido)","Glucosamine sulfate (preferred)","Con comida","With food","No establecido","Clínico (mixto)",
 "Warfarina (puede subir INR)","Warfarin (may raise INR)",
 "Sulfato > HCl en evidencia. Efecto lento (semanas).",
 "Sulfate > HCl in evidence. Slow onset (weeks)."),
("collagen","Colágeno (péptidos)","Proteína","Protein",
 "10 g/día","15 g/día (piel/articulaciones) o 40 g +vit C (tendón)","Péptidos hidrolizados","Hydrolyzed peptides","Cualquier hora; tendón: 30–60 min pre-ejercicio","Any time; tendon: 30–60 min pre-exercise","No aplica","Clínico (emergente)",
 "Ninguna relevante","None relevant",
 "Piel/articulaciones a 10–15 g. Tendón: 15 g + vit C antes de cargar.",
 "Skin/joints at 10–15 g. Tendon: 15 g + vit C before loading."),
("vite","Vitamina E","Vitamina liposoluble","Fat-soluble vitamin",
 "15 mg (22.4 UI)/día","≤268 mg (400 UI)/día","d-alfa-tocoferol (mezcla de tocoferoles)","d-alpha-tocopherol (mixed tocopherols)","Con comida grasa","With a fatty meal","1000 mg/día (UL)","Clínico",
 "Anticoagulantes (sangrado a dosis altas)","Anticoagulants (bleeding at high doses)",
 "Dosis altas aisladas pueden ser perjudiciales; preferir mezcla natural.",
 "High isolated doses may be harmful; prefer natural mixed form."),
("selenium","Selenio","Mineral traza","Trace mineral",
 "55 µg/día","100–200 µg/día (tiroides autoinmune)","Selenometionina","Selenomethionine","Con comida","With food","400 µg/día (UL)","Clínico",
 "Margen estrecho: no exceder UL","Narrow margin: do not exceed UL",
 "Útil en tiroiditis de Hashimoto. Tóxico por encima del UL.",
 "Useful in Hashimoto's thyroiditis. Toxic above UL."),
("iodine","Yodo","Mineral traza","Trace mineral",
 "150 µg/día","150–220 µg/día (embarazo/lactancia)","Yoduro potásico / algas dosificadas","Potassium iodide / dosed kelp","Cualquier hora","Any time","1100 µg/día (UL)","Clínico",
 "Antitiroideos; puede desencadenar disfunción tiroidea","Antithyroid drugs; may trigger thyroid dysfunction",
 "Exceso tan dañino como déficit. Cuidado con algas no dosificadas.",
 "Excess as harmful as deficiency. Beware undosed kelp."),
("potassium","Potasio","Electrolito","Electrolyte",
 "3500–4700 mg/día (dieta)","≤99 mg/dosis (suplemento OTC)","Citrato/cloruro (bajo control)","Citrate/chloride (monitored)","Con comida","With food","Suplemento limitado; riesgo cardíaco","Clínico",
 "IECA/ARA-II, diuréticos ahorradores: hiperpotasemia","ACEi/ARB, K-sparing diuretics: hyperkalemia",
 "Preferir dieta. Suplementar solo con control (arritmias).",
 "Prefer diet. Supplement only with monitoring (arrhythmia)."),
("vita","Vitamina A","Vitamina liposoluble","Fat-soluble vitamin",
 "700–900 µg RAE/día","≤3000 µg/día (déficit, con control)","Retinol / betacaroteno","Retinol / beta-carotene","Con comida grasa","With a fatty meal","3000 µg RAE/día (UL)","Clínico",
 "Retinoides; hepatotóxicos; teratógeno en embarazo","Retinoids; hepatotoxics; teratogen in pregnancy",
 "Betacaroteno más seguro (sin toxicidad aguda). Retinol: no exceder UL en embarazo.",
 "Beta-carotene safer (no acute toxicity). Retinol: don't exceed UL in pregnancy."),
("b1","Vitamina B1 (tiamina)","Vitamina hidrosoluble","Water-soluble vitamin",
 "1.1–1.2 mg/día","100–300 mg/día (déficit, alcoholismo)","Tiamina / benfotiamina","Thiamine / benfotiamine","Con comida","With food","No establecido (segura)","Clínico",
 "Ninguna relevante","None relevant",
 "Benfotiamina (liposoluble) mejor en neuropatía. Déficit común en alcoholismo.",
 "Benfotiamine (fat-soluble) better for neuropathy. Deficiency common in alcoholism."),
("b2","Vitamina B2 (riboflavina)","Vitamina hidrosoluble","Water-soluble vitamin",
 "1.1–1.3 mg/día","400 mg/día (profilaxis de migraña)","Riboflavina","Riboflavin","Con comida","With food","No establecido","Clínico",
 "Ninguna relevante","None relevant",
 "400 mg/día reduce frecuencia de migraña (efecto a 3 meses). Orina amarilla fluor.",
 "400 mg/day reduces migraine frequency (effect at 3 months). Bright yellow urine."),
("b3","Vitamina B3 (niacina)","Vitamina hidrosoluble","Water-soluble vitamin",
 "14–16 mg/día","500–2000 mg/día (dislipidemia, con control)","Niacina / nicotinamida","Niacin / nicotinamide","Con comida","With food","35 mg/día niacina como suplemento (UL flushing)","Clínico",
 "Estatinas (miopatía); hepatotoxicidad a dosis altas","Statins (myopathy); hepatotoxicity at high doses",
 "Niacina sube HDL/baja Lp(a) pero causa flushing; vigilar hígado y glucosa.",
 "Niacin raises HDL/lowers Lp(a) but causes flushing; monitor liver and glucose."),
("b6","Vitamina B6 (piridoxina)","Vitamina hidrosoluble","Water-soluble vitamin",
 "1.3–1.7 mg/día","10–50 mg/día (SPM, náusea gestacional)","Piridoxina / P5P","Pyridoxine / P5P","Con comida","With food","25 mg/día (UL EFSA)","Clínico",
 "Levodopa (sin carbidopa); antiepilépticos","Levodopa (without carbidopa); antiepileptics",
 "No exceder crónicamente: neuropatía sensitiva por exceso. P5P forma activa.",
 "Don't exceed chronically: sensory neuropathy from excess. P5P is active form."),
("biotin","Biotina (B7)","Vitamina hidrosoluble","Water-soluble vitamin",
 "30 µg/día","2.5–5 mg/día (pelo/uñas, evidencia limitada)","Biotina","Biotin","Con comida","With food","No establecido","Débil/clínico",
 "INTERFIERE en análisis de laboratorio (tiroides, troponina)","INTERFERES with lab assays (thyroid, troponin)",
 "Suspender 48–72 h antes de análisis de sangre (falsea resultados).",
 "Stop 48–72 h before blood tests (skews results)."),
("choline","Colina","Nutriente esencial","Essential nutrient",
 "425–550 mg/día","1–2 g/día (hígado graso, cognición)","Citicolina / alfa-GPC / bitartrato","Citicoline / alpha-GPC / bitartrate","Con comida","With food","3500 mg/día (UL)","Clínico",
 "Ninguna relevante","None relevant",
 "Alfa-GPC y citicolina para cognición. Exceso → olor corporal a pescado (TMAO).",
 "Alpha-GPC and citicoline for cognition. Excess → fishy body odor (TMAO)."),
("copper","Cobre","Mineral traza","Trace mineral",
 "0.9 mg/día","1–2 mg/día (con zinc crónico)","Bisglicinato de cobre","Copper bisglycinate","Con comida","With food","10 mg/día (UL)","Clínico",
 "Zinc en exceso deplece cobre","Excess zinc depletes copper",
 "Añadir si tomas zinc alto crónico. Ratio zinc:cobre ~10:1.",
 "Add if on chronic high zinc. Zinc:copper ratio ~10:1."),
("manganese","Manganeso","Mineral traza","Trace mineral",
 "1.8–2.3 mg/día","No suele suplementarse aislado","Gluconato/quelato","Gluconate/chelate","Con comida","With food","11 mg/día (UL)","Clínico",
 "Neurotoxicidad por exceso (parkinsonismo)","Neurotoxicity from excess (parkinsonism)",
 "Rara vez deficitario (abundante en dieta). No exceder UL.",
 "Rarely deficient (abundant in diet). Don't exceed UL."),
("boron","Boro","Mineral traza","Trace mineral",
 "1–3 mg/día","3–10 mg/día (hueso, testosterona)","Borato / fructoborato","Borate / fructoborate","Con comida","With food","20 mg/día (UL)","Clínico (limitado)",
 "Ninguna relevante","None relevant",
 "Modula vitamina D, magnesio y hormonas esteroideas. Dosis baja.",
 "Modulates vitamin D, magnesium and steroid hormones. Low dose."),
("tmg","Betaína (TMG)","Donante de metilo","Methyl donor",
 "1–3 g/día","3–6 g/día (homocisteína, rendimiento)","Trimetilglicina","Trimethylglycine","Con comida","With food","No establecido","Clínico",
 "Ninguna relevante","None relevant",
 "Baja homocisteína (sinergia con B12/folato). Puede subir LDL a dosis altas.",
 "Lowers homocysteine (synergy with B12/folate). May raise LDL at high doses."),
("beta_alanine","Beta-alanina","Aminoácido","Amino acid",
 "3–5 g/día (repartido)","4–6 g/día (rendimiento anaeróbico)","Beta-alanina","Beta-alanine","Repartido para evitar parestesia","Split to avoid paresthesia","No establecido (seguro)","Clínico (fuerte)",
 "Ninguna relevante","None relevant",
 "Sube carnosina muscular; mejora esfuerzos 1–4 min. Hormigueo (inofensivo) → repartir.",
 "Raises muscle carnosine; improves 1–4 min efforts. Tingling (harmless) → split."),
("citrulline","L-citrulina","Aminoácido","Amino acid",
 "3–6 g/día","6–8 g/día (rendimiento, malato)","L-citrulina / citrulina malato","L-citrulline / citrulline malate","30–60 min pre-ejercicio","30–60 min pre-exercise","No establecido (segura)","Clínico",
 "Antihipertensivos; PDE5 (sildenafilo)","Antihypertensives; PDE5 (sildenafil)",
 "Sube óxido nítrico (mejor que arginina oral). Flujo sanguíneo y bomba.",
 "Raises nitric oxide (better than oral arginine). Blood flow and pump."),
("carnitine","L-carnitina","Aminoácido derivado","Amino acid derivative",
 "500–2000 mg/día","2–4 g/día (según objetivo)","L-carnitina / tartrato / ALCAR","L-carnitine / tartrate / ALCAR","Con carbohidrato para absorción","With a carb for absorption","No establecido","Clínico (mixto)",
 "Hormona tiroidea (antagonismo leve); anticoagulantes","Thyroid hormone (mild antagonism); anticoagulants",
 "ALCAR cruza BHE (cognición); tartrato para recuperación. TMAO en exceso.",
 "ALCAR crosses BBB (cognition); tartrate for recovery. TMAO in excess."),
("tyrosine","L-tirosina","Aminoácido","Amino acid",
 "500–2000 mg","100–150 mg/kg (estrés agudo/cognición)","L-tirosina","L-tyrosine","En ayunas, antes de estrés","Fasting, before stressor","No establecido","Clínico",
 "IMAO (crisis hipertensiva); hormona tiroidea","MAOIs (hypertensive crisis); thyroid hormone",
 "Precursor de dopamina/noradrenalina; útil bajo estrés/privación de sueño.",
 "Dopamine/noradrenaline precursor; useful under stress/sleep loss."),
("bacopa","Bacopa monnieri","Nootrópico (hierba)","Nootropic (herb)",
 "300 mg/día (50% bacósidos)","300–450 mg/día (memoria)","Extracto estandarizado","Standardized extract","Con comida grasa","With a fatty meal","No establecido","Clínico",
 "Sedantes; tiroides; anticolinérgicos","Sedatives; thyroid; anticholinergics",
 "Mejora memoria a 8–12 semanas (efecto lento). Puede dar molestia GI.",
 "Improves memory at 8–12 weeks (slow onset). May cause GI upset."),
("lions_mane","Melena de león","Hongo funcional","Functional mushroom",
 "500–1000 mg/día","1–3 g/día (cognición/nervio)","Extracto de Hericium erinaceus","Hericium erinaceus extract","Con comida","With food","No establecido","Preclínico/clínico",
 "Anticoagulantes (teórico)","Anticoagulants (theoretical)",
 "NGF/neurogénesis in vitro; evidencia humana emergente. Buscar cuerpo fructífero.",
 "NGF/neurogenesis in vitro; emerging human evidence. Seek fruiting body."),
("cordyceps","Cordyceps","Hongo funcional","Functional mushroom",
 "1–3 g/día","3–4.5 g/día (rendimiento/energía)","CS-4 / militaris","CS-4 / militaris","Con comida","With food","No establecido","Clínico (limitado)",
 "Anticoagulantes; inmunosupresores","Anticoagulants; immunosuppressants",
 "VO2max/energía; evidencia moderada. Militaris con más cordicepina.",
 "VO2max/energy; moderate evidence. Militaris has more cordycepin."),
("spirulina","Espirulina","Alga (superalimento)","Algae (superfood)",
 "1–3 g/día","4–8 g/día (lípidos/alergia)","Polvo/comprimido (fuente segura)","Powder/tablet (safe source)","Con comida","With food","No establecido","Clínico (moderado)",
 "Inmunosupresores; anticoagulantes","Immunosuppressants; anticoagulants",
 "Baja LDL levemente; antioxidante. Riesgo de contaminación → marca certificada.",
 "Mildly lowers LDL; antioxidant. Contamination risk → certified brand."),
("boswellia","Boswellia (incienso)","Antiinflamatorio (hierba)","Anti-inflammatory (herb)",
 "300–400 mg 2–3×/día","100–250 mg AKBA/día (artrosis)","Extracto (30–65% ác. boswélicos, AKBA)","Extract (30–65% boswellic acids, AKBA)","Con comida grasa","With a fatty meal","No establecido","Clínico",
 "Antiinflamatorios; sustratos CYP","Anti-inflammatories; CYP substrates",
 "Inhibe 5-LOX; útil en artrosis y EII. Buscar alto AKBA.",
 "Inhibits 5-LOX; useful in osteoarthritis and IBD. Seek high AKBA."),
("msm","MSM (metilsulfonilmetano)","Compuesto azufrado","Sulfur compound",
 "1–3 g/día","3–6 g/día (artrosis, dolor)","MSM","MSM","Con comida","With food","No establecido (seguro)","Clínico (moderado)",
 "Anticoagulantes (teórico)","Anticoagulants (theoretical)",
 "Dolor articular y rango de movimiento; sinergia con glucosamina.",
 "Joint pain and range of motion; synergy with glucosamine."),
("lutein","Luteína + zeaxantina","Carotenoide","Carotenoid",
 "10 mg luteína + 2 mg zeaxantina/día","20 mg/día (DMAE)","Con comida grasa","With a fatty meal","Con comida grasa","With a fatty meal","No establecido","Clínico (AREDS2)",
 "Ninguna relevante","None relevant",
 "Protección macular (AREDS2). Ratio 5:1 luteína:zeaxantina.",
 "Macular protection (AREDS2). 5:1 lutein:zeaxanthin ratio."),
("astaxanthin","Astaxantina","Carotenoide","Carotenoid",
 "4–6 mg/día","8–12 mg/día (piel/recuperación)","De Haematococcus pluvialis","From Haematococcus pluvialis","Con comida grasa","With a fatty meal","No establecido","Clínico (limitado)",
 "Anticoagulantes (teórico); 5-alfa-reductasa","Anticoagulants (theoretical); 5-alpha-reductase",
 "Antioxidante potente; fotoprotección de piel. Liposoluble.",
 "Potent antioxidant; skin photoprotection. Fat-soluble."),
("pqq","PQQ","Cofactor redox","Redox cofactor",
 "10–20 mg/día","20 mg/día (mitocondrial/cognición)","Pirroloquinolina quinona","Pyrroloquinoline quinone","Con comida","With food","No establecido","Preclínico/clínico",
 "Ninguna relevante","None relevant",
 "Biogénesis mitocondrial; sinergia con CoQ10. Evidencia emergente.",
 "Mitochondrial biogenesis; synergy with CoQ10. Emerging evidence."),
("nmn","NMN","Precursor de NAD+","NAD+ precursor",
 "250–500 mg/día","500–1000 mg/día (longevidad, estudios)","Nicotinamida mononucleótido","Nicotinamide mononucleotide","Mañana, en ayunas","Morning, fasting","No establecido","Preclínico (clínico emergente)",
 "Ninguna relevante conocida","None known",
 "Sube NAD+; evidencia humana temprana. Estatus regulatorio variable.",
 "Raises NAD+; early human evidence. Regulatory status varies."),
("nr","Nicotinamida ribósido (NR)","Precursor de NAD+","NAD+ precursor",
 "250–300 mg/día","300–1000 mg/día","Niagen","Niagen","Mañana","Morning","300 mg/día (evaluado seguro)","Clínico",
 "Ninguna relevante conocida","None known",
 "Sube NAD+ de forma robusta en humanos; buen perfil de seguridad.",
 "Robustly raises NAD+ in humans; good safety profile."),
("dmannose","D-manosa","Azúcar simple","Simple sugar",
 "2 g/día (prevención ITU)","1.5 g 2–3×/día (ITU aguda)","D-manosa","D-mannose","Con agua abundante","With plenty of water","No establecido (bien tolerada)","Clínico (moderado)",
 "Antidiabéticos (mínimo impacto glucémico)","Antidiabetics (minimal glycemic impact)",
 "Previene ITU por E. coli (impide adhesión). No sustituye antibiótico en ITU grave.",
 "Prevents E. coli UTI (blocks adhesion). Not a substitute for antibiotics in severe UTI."),
("cranberry","Arándano rojo","Fitoterapia (fruta)","Phytotherapy (fruit)",
 "36 mg PAC/día","36–72 mg proantocianidinas (PAC)/día","Extracto estandarizado en PAC","PAC-standardized extract","Con comida","With food","No establecido","Clínico (moderado)",
 "Warfarina (posible aumento de INR)","Warfarin (possible INR increase)",
 "Prevención de ITU recurrente. Estandarizar por PAC, no por 'mg de fruta'.",
 "Recurrent UTI prevention. Standardize by PAC, not 'mg of fruit'."),
("elderberry","Saúco (elderberry)","Fitoterapia (fruta)","Phytotherapy (fruit)",
 "300–600 mg extracto/día","3.8–15 mL jarabe 2–4×/día (resfriado)","Extracto de Sambucus nigra","Sambucus nigra extract","A los primeros síntomas","At first symptoms","No establecido","Clínico (limitado)",
 "Inmunosupresores (teórico)","Immunosuppressants (theoretical)",
 "Puede acortar síntomas de gripe/resfriado. Solo fruta cocida (cruda es tóxica).",
 "May shorten cold/flu symptoms. Cooked fruit only (raw is toxic)."),
("echinacea","Equinácea","Inmunomodulador (hierba)","Immunomodulator (herb)",
 "300–500 mg 3×/día","Al inicio del resfriado, corto plazo","Extracto de E. purpurea","E. purpurea extract","A los primeros síntomas","At first symptoms","Uso ≤10 días","Clínico (mixto)",
 "Inmunosupresores; sustratos CYP1A2/3A4","Immunosuppressants; CYP1A2/3A4 substrates",
 "Evidencia inconsistente; posible reducción leve de duración. No en autoinmunidad.",
 "Inconsistent evidence; possible mild duration reduction. Not in autoimmunity."),
("valerian","Valeriana","Sedante (hierba)","Sedative (herb)",
 "300–600 mg/día","400–900 mg 30–60 min antes de dormir","Extracto de raíz","Root extract","Antes de dormir","Before bed","No establecido","Clínico (mixto)",
 "Sedantes, alcohol, benzodiacepinas (aditivo)","Sedatives, alcohol, benzodiazepines (additive)",
 "Insomnio de inicio; efecto puede tardar 2 semanas. Somnolencia matutina posible.",
 "Sleep-onset insomnia; effect may take 2 weeks. Possible morning grogginess."),
("lemon_balm","Melisa (toronjil)","Ansiolítico (hierba)","Anxiolytic (herb)",
 "300–600 mg/día","600 mg (estrés agudo) / 900 mg dividido","Extracto de Melissa officinalis","Melissa officinalis extract","Según necesidad; noche para sueño","As needed; evening for sleep","No establecido","Clínico (limitado)",
 "Sedantes; hormona tiroidea (teórico)","Sedatives; thyroid hormone (theoretical)",
 "Calma y sueño; sinergia con valeriana. Buen perfil de seguridad.",
 "Calm and sleep; synergy with valerian. Good safety profile."),
("ps","Fosfatidilserina","Fosfolípido","Phospholipid",
 "100 mg 3×/día (300 mg/día)","300 mg/día (cognición/cortisol)","PS de girasol","Sunflower-derived PS","Con comida","With food","No establecido","Clínico (moderado)",
 "Anticoagulantes; anticolinesterásicos","Anticoagulants; cholinesterase inhibitors",
 "Cognición en mayores y amortigua cortisol por ejercicio. Preferir de girasol.",
 "Cognition in elderly and blunts exercise cortisol. Prefer sunflower source."),
("fenugreek","Fenogreco","Fitoterapia (hierba)","Phytotherapy (herb)",
 "500–1000 mg/día","5–10 g semilla/día (glucemia, lactancia)","Extracto o semilla","Extract or seed","Con comidas","With meals","No establecido","Clínico (moderado)",
 "Antidiabéticos (aditivo); anticoagulantes","Antidiabetics (additive); anticoagulants",
 "Baja glucosa posprandial; galactogogo. Puede dar olor a jarabe de arce.",
 "Lowers postprandial glucose; galactagogue. May cause maple-syrup odor."),
("maca","Maca","Adaptógeno (raíz)","Adaptogen (root)",
 "1.5–3 g/día","3 g/día (libido, energía)","Polvo de raíz gelatinizado","Gelatinized root powder","Con comida","With food","No establecido","Clínico (limitado)",
 "Hormonal (teórico)","Hormonal (theoretical)",
 "Libido y energía; no altera hormonas directamente. Gelatinizada mejor tolerada.",
 "Libido and energy; doesn't directly alter hormones. Gelatinized better tolerated."),
("nitrate","Remolacha (nitrato)","Nitrato dietético","Dietary nitrate",
 "300–600 mg nitrato/día","6.4–12.8 mmol nitrato (rendimiento)","Zumo de remolacha / concentrado","Beetroot juice / concentrate","2–3 h antes de ejercicio","2–3 h before exercise","No establecido","Clínico (fuerte)",
 "PDE5, antihipertensivos; evita enjuague bucal antibacteriano","PDE5, antihypertensives; avoid antibacterial mouthwash",
 "Sube óxido nítrico → resistencia y presión. No usar colutorio (mata bacterias orales).",
 "Raises nitric oxide → endurance and BP. Skip mouthwash (kills oral bacteria)."),
("bromelain","Bromelina","Enzima proteolítica","Proteolytic enzyme",
 "500 mg/día","500–2000 mg/día (inflamación/edema)","De tallo de piña (GDU/MCU)","From pineapple stem (GDU/MCU)","En ayunas (antiinflamatorio)","Fasting (anti-inflammatory)","No establecido","Clínico (moderado)",
 "Anticoagulantes; antibióticos (aumenta absorción)","Anticoagulants; antibiotics (increases absorption)",
 "Antiinflamatorio/antiedema (postquirúrgico). En ayunas para efecto sistémico.",
 "Anti-inflammatory/anti-edema (post-surgery). Fasting for systemic effect."),
("saffron","Azafrán","Fitoterapia (especia)","Phytotherapy (spice)",
 "30 mg/día","30 mg/día (ánimo, dividido)","Extracto estandarizado (safranal/crocina)","Standardized extract (safranal/crocin)","Con comida, dividido","With food, divided","≤1.5 g/día (dosis altas tóxicas)","Clínico (moderado)",
 "Antidepresivos (aditivo); anticoagulantes","Antidepressants (additive); anticoagulants",
 "30 mg/día comparable a ISRS leve en depresión leve-moderada. No exceder dosis.",
 "30 mg/day comparable to mild SSRI in mild-moderate depression. Don't exceed dose."),
("vitk1","Vitamina K1 (filoquinona)","Vitamina liposoluble","Fat-soluble vitamin",
 "90–120 µg/día","1–10 mg (revertir sobre-anticoagulación, médico)","Filoquinona","Phylloquinone","Con comida grasa","With a fatty meal","No establecido","Clínico",
 "Antagoniza warfarina (mantener ingesta CONSTANTE)","Antagonizes warfarin (keep intake CONSTANT)",
 "En warfarina no suspender de golpe: mantener aporte estable de vitamina K.",
 "On warfarin don't stop abruptly: keep vitamin K intake stable."),
("lysine","L-lisina","Aminoácido esencial","Essential amino acid",
 "1 g/día","1–3 g/día (herpes labial)","L-lisina","L-lysine","En ayunas","Fasting","No establecido","Clínico (moderado)",
 "Ninguna relevante","None relevant",
 "Reduce recurrencia de herpes simple. Compite con arginina.",
 "Reduces herpes simplex recurrence. Competes with arginine."),
("glutamine","L-glutamina","Aminoácido","Amino acid",
 "5 g/día","10–30 g/día (intestino, catabolismo)","L-glutamina","L-glutamine","Repartido, en ayunas","Split, fasting","No establecido","Clínico (mixto)",
 "Ninguna relevante","None relevant",
 "Integridad intestinal en estrés/quemados; evidencia deportiva débil.",
 "Gut integrity in stress/burns; weak sports evidence."),
("hmb","HMB","Metabolito de leucina","Leucine metabolite",
 "3 g/día","3 g/día (anti-catabólico)","Beta-hidroxi-beta-metilbutirato","Beta-hydroxy-beta-methylbutyrate","Repartido con comidas","Split with meals","No establecido","Clínico",
 "Ninguna relevante","None relevant",
 "Reduce catabolismo muscular (mayores, déficit calórico). Efecto modesto en entrenados.",
 "Reduces muscle catabolism (elderly, caloric deficit). Modest effect in trained."),
("bcaa","BCAA / EAA","Aminoácidos ramificados/esenciales","Branched/essential amino acids",
 "5–10 g BCAA","10–15 g EAA (mejor que BCAA)","EAA completos preferidos","Complete EAAs preferred","Alrededor del ejercicio","Around exercise","No establecido","Clínico",
 "Ninguna relevante","None relevant",
 "EAA > BCAA para síntesis proteica. Innecesario si proteína dietética es suficiente.",
 "EAA > BCAA for protein synthesis. Unnecessary if dietary protein is sufficient."),
("caffeine","Cafeína","Estimulante","Stimulant",
 "40–200 mg","3–6 mg/kg (rendimiento)","Anhidra / natural","Anhydrous / natural","30–60 min pre-ejercicio; evitar 8 h antes de dormir","30–60 min pre-exercise; avoid 8 h before bed","400 mg/día (adultos)","Clínico (fuerte)",
 "Estimulantes; teofilina; ISRS; litio","Stimulants; theophylline; SSRIs; lithium",
 "Ergogénico robusto. Cortar 8 h antes de dormir para no dañar el sueño.",
 "Robust ergogenic. Cut 8 h before bed to protect sleep."),
("mucuna","Mucuna pruriens","Fitoterapia (L-DOPA)","Phytotherapy (L-DOPA)",
 "5% L-DOPA: ~200–500 mg L-DOPA/día","Según objetivo (Parkinson: con médico)","Extracto estandarizado en L-DOPA","L-DOPA-standardized extract","En ayunas","Fasting","No establecido","Clínico (limitado)",
 "Levodopa, IMAO, antipsicóticos","Levodopa, MAOIs, antipsychotics",
 "Fuente natural de L-DOPA (dopamina). Cuidado con fármacos dopaminérgicos.",
 "Natural L-DOPA source (dopamine). Caution with dopaminergic drugs."),
("tulsi","Tulsi (albahaca sagrada)","Adaptógeno (hierba)","Adaptogen (herb)",
 "300–600 mg/día","600–1200 mg/día (estrés/glucemia)","Extracto de Ocimum sanctum","Ocimum sanctum extract","Con comida","With food","No establecido","Clínico (limitado)",
 "Antidiabéticos; anticoagulantes","Antidiabetics; anticoagulants",
 "Reduce estrés y glucosa levemente. Buen perfil de seguridad.",
 "Reduces stress and glucose mildly. Good safety profile."),
("schisandra","Schisandra","Adaptógeno (baya)","Adaptogen (berry)",
 "500–2000 mg/día","1–3 g/día (hígado/estrés)","Extracto estandarizado (esquisandrinas)","Standardized extract (schisandrins)","Con comida","With food","No establecido","Clínico (limitado)",
 "Sustratos CYP3A4 (induce/inhibe según dosis)","CYP3A4 substrates (induces/inhibits by dose)",
 "Hepatoprotector y anti-estrés. Puede alterar metabolismo de fármacos.",
 "Hepatoprotector and anti-stress. May alter drug metabolism."),
("eleuthero","Eleuterococo (ginseng siberiano)","Adaptógeno (hierba)","Adaptogen (herb)",
 "300–1200 mg/día","2–4 g raíz/día (fatiga)","Extracto de Eleutherococcus","Eleutherococcus extract","Mañana","Morning","No establecido; ciclar","Clínico (mixto)",
 "Digoxina (falsea niveles); anticoagulantes; antidiabéticos","Digoxin (falsifies levels); anticoagulants; antidiabetics",
 "Anti-fatiga/resistencia. Evitar en hipertensión no controlada.",
 "Anti-fatigue/endurance. Avoid in uncontrolled hypertension."),
("astragalus","Astrágalo","Inmunomodulador (hierba)","Immunomodulator (herb)",
 "500 mg 2–3×/día","2–4 g/día (inmune)","Extracto de Astragalus membranaceus","Astragalus membranaceus extract","Con comida","With food","No establecido","Clínico (limitado)",
 "Inmunosupresores; anticoagulantes; litio","Immunosuppressants; anticoagulants; lithium",
 "Inmunotónico; no usar en autoinmunidad ni trasplantados.",
 "Immune tonic; avoid in autoimmunity and transplant patients."),
("andrographis","Andrographis","Inmunomodulador (hierba)","Immunomodulator (herb)",
 "400 mg 3×/día","60–200 mg andrografólido/día (resfriado)","Extracto (andrografólidos)","Extract (andrographolides)","A los primeros síntomas","At first symptoms","Uso corto plazo","Clínico (moderado)",
 "Anticoagulantes; antihipertensivos; inmunosupresores","Anticoagulants; antihypertensives; immunosuppressants",
 "Reduce síntomas de infección respiratoria alta. No en embarazo.",
 "Reduces upper respiratory infection symptoms. Not in pregnancy."),
("dim","DIM (diindolilmetano)","Metabolito de crucíferas","Cruciferous metabolite",
 "100 mg/día","100–200 mg/día (equilibrio estrogénico)","Diindolilmetano","Diindolylmethane","Con comida grasa","With a fatty meal","No establecido","Preclínico/clínico",
 "Sustratos CYP; hormonal","CYP substrates; hormonal",
 "Modula metabolismo de estrógenos. Derivado de I3C del brócoli.",
 "Modulates estrogen metabolism. Derived from broccoli I3C."),
("glutathione","Glutatión","Antioxidante","Antioxidant",
 "250–500 mg/día","500–1000 mg/día (liposomal/acetilado)","Liposomal o S-acetil-glutatión","Liposomal or S-acetyl-glutathione","En ayunas","Fasting","No establecido","Clínico (mixto)",
 "Ninguna relevante","None relevant",
 "Baja absorción oral → liposomal/acetilado o precursor NAC. Antioxidante maestro.",
 "Poor oral absorption → liposomal/acetylated or NAC precursor. Master antioxidant."),
("tudca","TUDCA","Ácido biliar","Bile acid",
 "250–500 mg/día","1000–1750 mg/día (colestasis, médico)","Ácido tauroursodesoxicólico","Tauroursodeoxycholic acid","Con comida","With food","No establecido","Clínico (limitado)",
 "Secuestrantes de ácidos biliares","Bile acid sequestrants",
 "Hepatoprotector y del retículo endoplásmico. Uso clínico en colestasis.",
 "Hepatoprotector and ER-stress protectant. Clinical use in cholestasis."),
("artichoke","Alcachofa","Fitoterapia (hierba)","Phytotherapy (herb)",
 "300–640 mg 3×/día","1800 mg/día (dispepsia/lípidos)","Extracto de hoja (cinarina)","Leaf extract (cynarin)","Antes de comidas","Before meals","No establecido","Clínico (moderado)",
 "Obstrucción biliar (contraindicado)","Bile duct obstruction (contraindicated)",
 "Digestivo y baja colesterol levemente. Evitar en cálculos biliares.",
 "Digestive and mildly lowers cholesterol. Avoid in gallstones."),
("red_yeast_rice","Levadura roja de arroz","Fitoterapia (estatina natural)","Phytotherapy (natural statin)",
 "1200–2400 mg/día","2400 mg/día (~10 mg monacolina K)","Estandarizado en monacolina K","Standardized in monacolin K","Noche, con comida","Evening, with food","≤10 mg monacolina K/día (EFSA)","Clínico",
 "Estatinas (NO combinar); fibratos; sustratos CYP3A4; toronja","Statins (do NOT combine); fibrates; CYP3A4 substrates; grapefruit",
 "Es una estatina natural (lovastatina). Añadir CoQ10; vigilar hígado/CK.",
 "It IS a natural statin (lovastatin). Add CoQ10; monitor liver/CK."),
("plant_sterols","Fitoesteroles","Esterol vegetal","Plant sterol",
 "2 g/día","2–3 g/día (LDL)","Esteroles/estanoles","Sterols/stanols","Con las comidas grasas","With fatty meals","≤3 g/día","Clínico (fuerte)",
 "Ezetimiba (aditivo); reduce absorción de carotenoides","Ezetimibe (additive); reduces carotenoid absorption",
 "Bajan LDL 8–10%. Repartir con comidas. Compensar carotenoides.",
 "Lower LDL 8–10%. Split with meals. Offset carotenoids."),
("bergamot","Bergamota (Citrus bergamia)","Fitoterapia (polifenol)","Phytotherapy (polyphenol)",
 "500 mg/día","500–1000 mg/día (lípidos)","Extracto polifenólico estandarizado","Standardized polyphenolic extract","Antes de comidas","Before meals","No establecido","Clínico (moderado)",
 "Estatinas (aditivo); sustratos CYP","Statins (additive); CYP substrates",
 "Baja LDL y triglicéridos; alternativa/complemento a estatina.",
 "Lowers LDL and triglycerides; statin alternative/complement."),
("chondroitin","Condroitina","Glicosaminoglicano","Glycosaminoglycan",
 "800–1200 mg/día","1200 mg/día (artrosis, con glucosamina)","Sulfato de condroitina","Chondroitin sulfate","Con comida","With food","No establecido","Clínico (mixto)",
 "Warfarina (posible aumento INR)","Warfarin (possible INR increase)",
 "Sinergia con glucosamina; efecto lento (semanas).",
 "Synergy with glucosamine; slow onset (weeks)."),
("hyaluronic","Ácido hialurónico","Glicosaminoglicano","Glycosaminoglycan",
 "120–240 mg/día","200 mg/día (piel/articulación)","Oral (bajo peso molecular)","Oral (low molecular weight)","Con comida","With food","No establecido","Clínico (moderado)",
 "Ninguna relevante","None relevant",
 "Hidratación de piel y confort articular. Bajo peso molecular se absorbe mejor.",
 "Skin hydration and joint comfort. Low molecular weight absorbs better."),
("glucomannan","Glucomanano","Fibra soluble","Soluble fiber",
 "1 g 3×/día antes de comidas","3–4 g/día (saciedad/LDL/glucosa)","Konjac","Konjac","15–30 min antes con 1–2 vasos de agua","15–30 min before with 1–2 glasses of water","No aplica","Clínico",
 "Separar de fármacos 1–2 h; riesgo de obstrucción si poco agua","Separate from drugs 1–2 h; obstruction risk with little water",
 "Saciedad y LDL. SIEMPRE con agua abundante (riesgo de atragantamiento).",
 "Satiety and LDL. ALWAYS with plenty of water (choking risk)."),
("capsaicin","Capsaicina","Fitoquímico (pimiento)","Phytochemical (chili)",
 "2–4 mg/día (oral)","Tópico 0.025–0.075% (dolor)","Cápsula oral o crema tópica","Oral capsule or topical cream","Con comida (oral)","With food (oral)","No establecido","Clínico (tópico)",
 "Antihipertensivos; irritación GI","Antihypertensives; GI irritation",
 "Tópico para dolor neuropático/artrósico. Termogénico leve oral.",
 "Topical for neuropathic/osteoarthritic pain. Mild thermogenic orally."),
("cla","CLA (ácido linoleico conjugado)","Ácido graso","Fatty acid",
 "3–4 g/día","3.4–6 g/día (composición corporal)","Isómeros c9,t11 / t10,c12","c9,t11 / t10,c12 isomers","Con comida","With food","No establecido","Clínico (mixto)",
 "Puede empeorar resistencia a insulina a dosis altas","May worsen insulin resistance at high doses",
 "Efecto modesto en grasa corporal; evidencia inconsistente.",
 "Modest effect on body fat; inconsistent evidence."),
("mct","Aceite MCT","Ácido graso","Fatty acid",
 "1 cucharada (14 g)/día","15–30 g/día (cetosis/energía)","C8/C10 (caprílico/cáprico)","C8/C10 (caprylic/capric)","Empezar bajo (tolerancia GI)","Start low (GI tolerance)","No establecido","Clínico",
 "Ninguna relevante","None relevant",
 "Energía rápida y cetonas. Subir gradual para evitar diarrea. C8 más cetogénico.",
 "Fast energy and ketones. Titrate up to avoid diarrhea. C8 most ketogenic."),
("gotu_kola","Centella asiática (gotu kola)","Fitoterapia (hierba)","Phytotherapy (herb)",
 "60–180 mg/día (triterpenos)","120–450 mg/día (venoso/piel)","Extracto estandarizado","Standardized extract","Con comida","With food","No establecido","Clínico (moderado)",
 "Hepatotóxicos; sedantes; antidiabéticos","Hepatotoxics; sedatives; antidiabetics",
 "Insuficiencia venosa y cicatrización. Cursos de ≤6 semanas.",
 "Venous insufficiency and wound healing. Courses ≤6 weeks."),
("sulforaphane","Sulforafano","Isotiocianato","Isothiocyanate",
 "10–30 mg/día","30–60 mg/día (Nrf2/detox)","Brotes de brócoli / mirosinasa activa","Broccoli sprouts / active myrosinase","Con comida","With food","No establecido","Clínico (emergente)",
 "Ninguna relevante","None relevant",
 "Activa Nrf2 (antioxidante/detox). Necesita mirosinasa para convertirse.",
 "Activates Nrf2 (antioxidant/detox). Needs myrosinase to convert."),
("policosanol","Policosanol","Alcohol graso (caña)","Fatty alcohol (sugarcane)",
 "5–10 mg/día","10–20 mg/día (lípidos)","De cera de caña de azúcar","From sugarcane wax","Noche","Evening","No establecido","Clínico (controvertido)",
 "Anticoagulantes (efecto antiplaquetario)","Anticoagulants (antiplatelet effect)",
 "Evidencia sobre LDL mixta (positiva sobre todo en estudios cubanos).",
 "LDL evidence mixed (positive mainly in Cuban studies)."),
("apigenin","Apigenina","Flavonoide","Flavonoid",
 "50 mg/día","50–100 mg/día (sueño/ansiedad)","De manzanilla/perejil","From chamomile/parsley","Noche","Evening","No establecido","Preclínico",
 "Sedantes; sustratos CYP","Sedatives; CYP substrates",
 "Ligando de receptores GABA/benzodiacepina (calma). Evidencia preclínica.",
 "GABA/benzodiazepine receptor ligand (calming). Preclinical evidence."),
]

FIELDS = ["slug","name","category_es","category_en","standard_dose","therapeutic_dose",
          "form_es","form_en","timing_es","timing_en","upper_limit","evidence",
          "interactions_es","interactions_en","notes_es","notes_en"]

# ── Capa de SEGURIDAD / HORARIO (reducir efectos adversos) ───────────────────
# slug -> {stop_days_before_surgery, bleeding_risk, oncology_caution_es/en, separate_from}
SAFETY = {
    "omega3": {"stop_days_before_surgery": 7, "bleeding_risk": True},
    "vite":   {"stop_days_before_surgery": 7, "bleeding_risk": True},
    "vitk1":  {"note_es": "Antagoniza warfarina: mantener ingesta constante.", "note_en": "Antagonizes warfarin: keep intake constant."},
    "k2":     {"note_es": "Contraindicado con warfarina.", "note_en": "Contraindicated with warfarin."},
    "ginkgo": {"stop_days_before_surgery": 10, "bleeding_risk": True},
    "garlic": {"stop_days_before_surgery": 10, "bleeding_risk": True},
    "ginseng":{"stop_days_before_surgery": 7, "bleeding_risk": True},
    "curcumin":{"stop_days_before_surgery": 7, "bleeding_risk": True},
    "quercetin":{"bleeding_risk": True},
    "resveratrol":{"stop_days_before_surgery": 7, "bleeding_risk": True},
    "bromelain":{"stop_days_before_surgery": 7, "bleeding_risk": True},
    "policosanol":{"bleeding_risk": True},
    "vitc":   {"oncology_caution_es": "Dosis altas antioxidantes pueden interferir con radio/quimio pro-oxidante — separar del ciclo.",
               "oncology_caution_en": "High antioxidant doses may blunt pro-oxidant chemo/radiotherapy — separate from cycle."},
    "vite2":  {},
    "astaxanthin":{"oncology_caution_es": "Antioxidante potente: consultar oncólogo durante radio/quimio.",
                   "oncology_caution_en": "Potent antioxidant: consult oncologist during chemo/radiotherapy."},
    "nac":    {"oncology_caution_es": "Antioxidante: puede interferir con quimio pro-oxidante — supervisión oncológica.",
               "oncology_caution_en": "Antioxidant: may interfere with pro-oxidant chemo — oncology supervision."},
    "glutathione":{"oncology_caution_es": "Antioxidante: separar de ciclos de quimio pro-oxidante.",
                   "oncology_caution_en": "Antioxidant: separate from pro-oxidant chemo cycles."},
    "hypericum":{"oncology_caution_es": "Inductor potente de CYP3A4: BAJA niveles de muchos citostáticos.",
                 "oncology_caution_en": "Potent CYP3A4 inducer: LOWERS many chemo drug levels."},
    "iron":   {"separate_from_es": "Separar 4 h de levotiroxina, calcio, café/té y quinolonas.",
               "separate_from_en": "Separate 4 h from levothyroxine, calcium, coffee/tea and quinolones."},
    "calcium":{"separate_from_es": "Separar 4 h de levotiroxina, hierro y quinolonas/tetraciclinas.",
               "separate_from_en": "Separate 4 h from levothyroxine, iron and quinolones/tetracyclines."},
    "magnesium":{"separate_from_es": "Separar 2–4 h de antibióticos (quinolonas/tetraciclinas) y bifosfonatos.",
                 "separate_from_en": "Separate 2–4 h from antibiotics (quinolones/tetracyclines) and bisphosphonates."},
    "zinc":   {"separate_from_es": "Separar 2 h de quinolonas y del hierro.",
               "separate_from_en": "Separate 2 h from quinolones and iron."},
    "psyllium":{"separate_from_es": "Separar 2–4 h de cualquier fármaco (reduce absorción).",
                "separate_from_en": "Separate 2–4 h from any drug (reduces absorption)."},
    "glucomannan":{"separate_from_es": "Separar 1–2 h de fármacos.",
                   "separate_from_en": "Separate 1–2 h from drugs."},
    "red_yeast_rice":{"oncology_caution_es": "Es lovastatina: NO combinar con estatinas.",
                      "oncology_caution_en": "It is lovastatin: do NOT combine with statins."},
    "biotin": {"note_es": "Suspender 48–72 h antes de análisis de sangre (falsea resultados).",
               "note_en": "Stop 48–72 h before blood tests (skews results)."},
    "vita":   {"note_es": "Retinol teratógeno: no exceder en embarazo.",
               "note_en": "Retinol is teratogenic: don't exceed in pregnancy."},
}

def main():
    data = []
    for row in R:
        d = dict(zip(FIELDS, row))
        d["name_es"] = d["name"]; d["name_en"] = d["name"]
        if d["slug"] in SAFETY:
            d["safety"] = SAFETY[d["slug"]]
        data.append(d)
    out = {"version": "1.0", "count": len(data),
           "sources": "EFSA, NIH-ODS, EMA/HMPC, Examine, Cochrane, MSK About Herbs",
           "disclaimer_es": "Dosis educativas basadas en literatura. No sustituye criterio clínico.",
           "disclaimer_en": "Educational doses based on literature. Not a substitute for clinical judgment.",
           "items": data}
    dst = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                       "local_db", "supplement_dosing.json")
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    with open(dst, "w", encoding="utf-8") as f:
        json.dump(out, f, ensure_ascii=False, indent=2)
    print(f"OK: {len(data)} suplementos/hierbas -> {dst}")

if __name__ == "__main__":
    main()
